var searchData=
[
  ['c_0',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['c_20implementation_20actually_20relies_20on_1',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md150',1,'']]],
  ['c_20style_2',['C++ Style',['../coding.html#autotoc_md17',1,'']]],
  ['caches_20must_20move_20out_20of_20the_20node_3',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md159',1,'']]],
  ['calling_20annexes_4',['Calling Annexes',['../dev.html#autotoc_md33',1,'']]],
  ['capacity_5',['Capacity',['../ord.html#autotoc_md386',1,'']]],
  ['casts_6',['Further Casts',['../dev.html#autotoc_md47',1,'']]],
  ['cat_7',['cat',['../tuple.html#autotoc_md468',1,'cat'],['../vec.html#autotoc_md483',1,'cat']]],
  ['catching_20exceptions_8',['Catching Exceptions',['../coding.html#autotoc_md28',1,'']]],
  ['caveats_9',['Two honest caveats',['../md_docs_2why-cpp.html#autotoc_md164',1,'']]],
  ['ceildiv_20floordiv_20rem_10',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md180',1,'']]],
  ['check_11',['check',['../refly.html#autotoc_md407',1,'']]],
  ['check_5fbot_12',['check_bot',['../refly.html#autotoc_md406',1,'']]],
  ['choosing_20the_20right_20base_20class_13',['Choosing the Right Base Class',['../phases.html#autotoc_md110',1,'']]],
  ['class_14',['Choosing the Right Base Class',['../phases.html#autotoc_md110',1,'']]],
  ['class_20ir_20values_15',['Loop nests as first-class IR values',['../btensor.html#autotoc_md207',1,'']]],
  ['classical_20picture_16',['The classical picture',['../phases.html#autotoc_md105',1,'']]],
  ['cleanup_17',['Cleanup',['../phases.html#autotoc_md93',1,'']]],
  ['clos_20plugin_18',['The clos Plugin',['../clos.html',1,'']]],
  ['closedmutphase_19',['ClosedMutPhase',['../phases.html#phases_closed_mut_phase',1,'']]],
  ['closure_20attribute_20',['Closure Attribute',['../clos.html#autotoc_md238',1,'']]],
  ['cls_21',['cls.*',['../regex.html#autotoc_md420',1,'']]],
  ['cmake_20style_22',['CMake Style',['../coding.html#autotoc_md20',1,'']]],
  ['cmp_23',['cmp',['../math.html#autotoc_md339',1,'']]],
  ['code_24',['Code',['../refly.html#autotoc_md396',1,'']]],
  ['coding_20style_25',['Coding Style',['../coding.html#autotoc_md16',1,'Coding Style'],['../coding.html#autotoc_md22',1,'M⁠im Coding Style']]],
  ['command_20line_20reference_26',['Command-Line Reference',['../cli.html',1,'']]],
  ['comments_27',['Comments',['../langref.html#autotoc_md63',1,'']]],
  ['community_28',['💬 Community',['../index.html#autotoc_md138',1,'']]],
  ['compilation_20pipelines_20in_20m⁠im_29',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md113',1,'']]],
  ['compile_30',['compile',['../cli.html#xarg_compile',1,'']]],
  ['compile_20plugin_31',['The compile Plugin',['../compile.html',1,'']]],
  ['concat_32',['concat',['../btensor.html#autotoc_md215',1,'concat'],['../tensor.html#autotoc_md448',1,'concat']]],
  ['cond_33',['cond',['../compile.html#autotoc_md246',1,'']]],
  ['conditional_20breakpoints_34',['Conditional Breakpoints',['../coding.html#autotoc_md27',1,'']]],
  ['conj_35',['conj',['../regex.html#autotoc_md413',1,'']]],
  ['consing_20is_20inherently_20impure_36',['Hash-consing is inherently impure',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['const_5fidx_37',['const_idx',['../demo.html#autotoc_md282',1,'']]],
  ['construction_20with_20arena_20rollback_38',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['constructors_39',['Constructors',['../compile.html#autotoc_md248',1,'Constructors'],['../option.html#autotoc_md371',1,'Constructors'],['../ord.html#autotoc_md383',1,'Constructors']]],
  ['contains_40',['contains',['../ord.html#autotoc_md391',1,'contains'],['../tuple.html#autotoc_md471',1,'contains']]],
  ['context_41',['Context',['../gpu.html#autotoc_md290',1,'']]],
  ['continuations_42',['Functions and Continuations',['../langref.html#autotoc_md67',1,'']]],
  ['contributing_20debugging_43',['Contributing &amp;amp; Debugging',['../coding.html',1,'']]],
  ['contributor_20quick_20start_44',['Contributor Quick Start',['../coding.html#building',1,'']]],
  ['conv_45',['conv',['../core.html#autotoc_md268',1,'conv'],['../cps.html#autotoc_md280',1,'conv'],['../math.html#autotoc_md341',1,'conv'],['../tensor.html#autotoc_md449',1,'conv']]],
  ['conversions_46',['Conversions',['../core.html#autotoc_md267',1,'']]],
  ['copy_47',['copy',['../buffer.html#autotoc_md229',1,'']]],
  ['copy_5fto_5fdevice_20asyn_48',['copy_to_device(block) / copy_to_device(asyn)',['../gpu.html#autotoc_md302',1,'']]],
  ['copy_5fto_5fdevice_20block_20copy_5fto_5fdevice_20asyn_49',['copy_to_device(block) / copy_to_device(asyn)',['../gpu.html#autotoc_md302',1,'']]],
  ['copy_5fto_5fhost_20asyn_50',['copy_to_host(block) / copy_to_host(asyn)',['../gpu.html#autotoc_md303',1,'']]],
  ['copy_5fto_5fhost_20block_20copy_5fto_5fhost_20asyn_51',['copy_to_host(block) / copy_to_host(asyn)',['../gpu.html#autotoc_md303',1,'']]],
  ['core_20plugin_52',['The core Plugin',['../core.html',1,'']]],
  ['core_5ficmp_5fxygle_53',['autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md201',1,'']]],
  ['core_5fwrap_5fadd_54',['autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md202',1,'']]],
  ['core_5fwrap_5fmul_55',['autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md203',1,'']]],
  ['costs_56',['Non-performance costs',['../md_docs_2why-cpp.html#autotoc_md163',1,'']]],
  ['coverage_57',['Coverage',['../python.html#autotoc_md126',1,'']]],
  ['cps_58',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['cps_20plugin_59',['The CPS Plugin',['../cps.html',1,'']]],
  ['cps2ds_60',['cps2ds',['../cps.html#autotoc_md278',1,'']]],
  ['create_61',['create',['../ord.html#autotoc_md385',1,'']]],
  ['create_20a_20new_20in_20tree_20plugin_62',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md119',1,'']]],
  ['create_20a_20third_20party_20plugin_63',['Create a Third-Party Plugin',['../plugins.html#autotoc_md120',1,'']]],
  ['cut_20tree_20mutates_20in_20place_64',['The link-cut tree mutates in place',['../md_docs_2why-cpp.html#autotoc_md153',1,'']]]
];
