var searchData=
[
  ['range_0',['range',['../regex.html#autotoc_md416',1,'']]],
  ['re_1',['RE',['../regex.html#autotoc_md411',1,'']]],
  ['read_2',['read',['../buffer.html#autotoc_md224',1,'']]],
  ['recommended_20design_20pattern_3',['Recommended Design Pattern',['../phases.html#autotoc_md111',1,'']]],
  ['reference_4',['Reference',['../cli.html',1,'Command-Line Reference'],['../langref.html',1,'Mim Language Reference']]],
  ['reflect_5',['Reify / Reflect',['../refly.html#autotoc_md397',1,'']]],
  ['reflect_6',['reflect',['../refly.html#autotoc_md399',1,'']]],
  ['refly_20plugin_7',['The refly Plugin',['../refly.html',1,'']]],
  ['regex_20plugin_8',['The regex Plugin',['../regex.html',1,'']]],
  ['registered_20phases_9',['Registered Phases',['../compile.html#autotoc_md250',1,'']]],
  ['registered_20translations_10',['Registered translations',['../autodiff.html#autotoc_md199',1,'']]],
  ['registry_11',['Plugin Registry',['../plugins.html#autotoc_md118',1,'']]],
  ['reify_12',['reify',['../refly.html#autotoc_md398',1,'']]],
  ['reify_20reflect_13',['Reify / Reflect',['../refly.html#autotoc_md397',1,'']]],
  ['relies_20on_14',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md150',1,'']]],
  ['rem_15',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md180',1,'']]],
  ['remem_16',['remem',['../mem.html#autotoc_md352',1,'']]],
  ['repeat_17',['repeat',['../tensor.html#autotoc_md443',1,'']]],
  ['reset_20between_20iterations_18',['Reset Between Iterations',['../phases.html#autotoc_md86',1,'']]],
  ['reshape_19',['reshape',['../tensor.html#autotoc_md444',1,'']]],
  ['restrictions_20',['Restrictions',['../phases.html#autotoc_md95',1,'']]],
  ['results_21',['Analysis Results',['../phases.html#autotoc_md89',1,'']]],
  ['rewriter_22',['Rewriter',['../rewriting.html#rewriter',1,'']]],
  ['rewriter_20vs_20varrewriter_23',['Rewriter vs. VarRewriter',['../rewriting.html#autotoc_md147',1,'']]],
  ['rewrites_24',['Rewrites',['../phases.html#autotoc_md92',1,'Deferred Rewrites'],['../rewriting.html#autotoc_md142',1,'Mutable Rewrites']]],
  ['rewriting_25',['Rewriting',['../rewriting.html',1,'']]],
  ['right_20base_20class_26',['Choosing the Right Base Class',['../phases.html#autotoc_md110',1,'']]],
  ['ring_27',['Ring',['../btensor.html#autotoc_md206',1,'Ring'],['../tensor.html#autotoc_md429',1,'Ring']]],
  ['rollback_28',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['roots_29',['Roots',['../phases.html#autotoc_md91',1,'Roots'],['../phases.html#autotoc_md97',1,'Roots']]],
  ['roughly_20performance_20parity_30',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md167',1,'']]],
  ['round_31',['round',['../math.html#autotoc_md337',1,'']]],
  ['rrt_32',['rrt',['../math.html#autotoc_md344',1,'']]],
  ['rt_33',['rt',['../math.html#autotoc_md332',1,'']]],
  ['runtime_20wrappers_34',['Runtime Wrappers',['../plugins.html#plugin_runtime',1,'']]],
  ['rust_35',['What about Rust?',['../md_docs_2why-cpp.html#autotoc_md166',1,'']]],
  ['rust_20genuinely_20wins_36',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md168',1,'']]],
  ['rust_20would_20land_20at_20roughly_20performance_20parity_37',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md167',1,'']]],
  ['rwbase_38',['RWBase',['../phases.html#phases_rwbase',1,'']]],
  ['rwphase_39',['RWPhase',['../phases.html#phases_rwphase',1,'']]]
];
