var searchData=
[
  ['dbg_0',['dbg',['../refly.html#autotoc_md403',1,'']]],
  ['debugging_1',['Debugging',['../coding.html',1,'Contributing &amp; Debugging'],['../coding.html#autotoc_md24',1,'Debugging']]],
  ['declaration_20blocks_2',['Local Declaration Blocks',['../langref.html#autotoc_md69',1,'']]],
  ['declarations_3',['Declarations',['../langref.html#decl',1,'Declarations'],['../langref.html#autotoc_md71',1,'Declarations']]],
  ['default_20pipeline_4',['The default pipeline',['../opt.html#autotoc_md367',1,'']]],
  ['defeats_20the_20purpose_5',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md165',1,'']]],
  ['deferred_20rewrites_6',['Deferred Rewrites',['../phases.html#autotoc_md92',1,'']]],
  ['definitions_7',['Other Definitions',['../mimir.html#autotoc_md80',1,'']]],
  ['defs_20are_20placed_20in_20them_8',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md154',1,'']]],
  ['deinit_9',['deinit',['../gpu.html#autotoc_md292',1,'']]],
  ['delinearize_10',['delinearize',['../affine.html#autotoc_md185',1,'']]],
  ['demo_20plugin_11',['demo Plugin',['../plugins.html#autotoc_md115',1,'Example: demo Plugin'],['../demo.html',1,'The demo Plugin']]],
  ['dep_12',['&lt;span class=&quot;tt&quot;&gt;Dep&lt;/span&gt;',['../dev.html#autotoc_md41',1,'']]],
  ['dependencies_13',['Dependencies',['../coding.html#autotoc_md13',1,'Dependencies'],['../affine.html#autotoc_md172',1,'Dependencies'],['../autodiff.html#autotoc_md189',1,'Dependencies'],['../btensor.html#autotoc_md204',1,'Dependencies'],['../buffer.html#autotoc_md219',1,'Dependencies'],['../clos.html#autotoc_md232',1,'Dependencies'],['../core.html#autotoc_md251',1,'Dependencies'],['../cps.html#autotoc_md276',1,'Dependencies'],['../gpu.html#autotoc_md283',1,'Dependencies'],['../ll.html#autotoc_md315',1,'Dependencies'],['../ll_nvptx.html#autotoc_md320',1,'Dependencies'],['../mem.html#autotoc_md346',1,'Dependencies'],['../nvptx.html#autotoc_md362',1,'Dependencies'],['../opt.html#autotoc_md366',1,'Dependencies'],['../option.html#autotoc_md368',1,'Dependencies'],['../ord.html#autotoc_md379',1,'Dependencies'],['../refly.html#autotoc_md394',1,'Dependencies'],['../regex.html#autotoc_md409',1,'Dependencies'],['../tensor.html#autotoc_md427',1,'Dependencies'],['../tuple.html#autotoc_md465',1,'Dependencies'],['../vec.html#autotoc_md473',1,'Dependencies']]],
  ['deprecated_20list_14',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20pattern_15',['Recommended Design Pattern',['../phases.html#autotoc_md111',1,'']]],
  ['developer_20guide_16',['Developer Guide',['../dev.html',1,'']]],
  ['developer_20options_17',['Developer Options',['../cli.html#autotoc_md7',1,'']]],
  ['diagnostics_18',['Diagnostics',['../cli.html#autotoc_md4',1,'Diagnostics'],['../cli.html#clidiag',1,'Diagnostics']]],
  ['diff_19',['diff',['../autodiff.html#autotoc_md200',1,'diff'],['../vec.html#autotoc_md484',1,'diff']]],
  ['diff_20core_5ficmp_5fxygle_20',['autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md201',1,'']]],
  ['diff_20core_5fwrap_5fadd_21',['autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md202',1,'']]],
  ['diff_20core_5fwrap_5fmul_22',['autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md203',1,'']]],
  ['differentiation_20plugin_23',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['discovery_24',['Third-Party Plugin Discovery',['../plugins.html#extra_plugins',1,'']]],
  ['discussion_25',['Discussion',['../phases.html#autotoc_md109',1,'']]],
  ['disj_26',['disj',['../regex.html#autotoc_md414',1,'']]],
  ['displaying_20dot_20graphs_27',['Displaying DOT Graphs',['../coding.html#autotoc_md26',1,'']]],
  ['div_28',['div',['../core.html#autotoc_md263',1,'']]],
  ['dividend_20does_20not_20apply_20here_29',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md162',1,'']]],
  ['does_20not_20apply_20here_30',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md162',1,'']]],
  ['dominance_31',['Dominance',['../index.html#autotoc_md136',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['dot_20graphs_32',['Displaying DOT Graphs',['../coding.html#autotoc_md26',1,'']]],
  ['dot_20output_33',['DOT Output',['../cli.html#autotoc_md3',1,'']]],
  ['dot_5fproduct_34',['dot_product',['../tensor.html#autotoc_md451',1,'']]],
  ['downcast_35',['General Downcast',['../dev.html#autotoc_md43',1,'']]],
  ['downcast_20to_20immutables_36',['Downcast to Immutables',['../dev.html#autotoc_md44',1,'']]],
  ['downcast_20to_20mutables_37',['Downcast to Mutables',['../dev.html#autotoc_md45',1,'']]],
  ['downcasts_20for_20built_20ins_38',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['doxygen_20style_39',['Doxygen Style',['../coding.html#autotoc_md18',1,'']]],
  ['dsl_40',['Embedded Python DSL',['../python.html#autotoc_md127',1,'']]],
  ['dumping_41',['Dumping',['../coding.html#autotoc_md25',1,'']]]
];
