var searchData=
[
  ['icmp_0',['%core.icmp',['../core.html#autotoc_md170',1,'']]],
  ['icmp_20xygle_20eq_1',['%core.icmp.xYgLE (eq)',['../autodiff.html#autotoc_md139',1,'']]],
  ['idx_2',['%core.idx',['../core.html#autotoc_md164',1,'']]],
  ['immutables_3',['Immutables',['../dev.html#autotoc_md27',1,'Downcast to Immutables'],['../dev.html#autotoc_md20',1,'Immutables']]],
  ['immutables_20vs_20mutables_4',['Immutables vs. Mutables',['../dev.html#mut',1,'']]],
  ['in_20m⁠im_5',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md81',1,'']]],
  ['in_20tree_20plugin_6',['In Tree Plugin',['../plugins.html#autotoc_md84',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md87',1,'Extract an Existing In-Tree Plugin']]],
  ['index_7',['%affine.index',['../affine.html#autotoc_md119',1,'']]],
  ['index_20operations_8',['Affine Index Operations',['../affine.html#autotoc_md118',1,'']]],
  ['indices_9',['Working with Indices',['../dev.html#autotoc_md34',1,'']]],
  ['init_10',['init',['../matrix.html#autotoc_md248',1,'%matrix.init'],['../ord.html#autotoc_md295',1,'%ord.init']]],
  ['innovations_11',['🔥 Key Innovations',['../index.html#autotoc_md100',1,'']]],
  ['ins_12',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['insert_13',['insert',['../matrix.html#autotoc_md246',1,'%matrix.insert'],['../ord.html#autotoc_md304',1,'%ord.insert']]],
  ['inspect_14',['Inspect',['../refly.html#autotoc_md310',1,'']]],
  ['install_20optional_15',['📦 Install (Optional)',['../index.html#autotoc_md99',1,'']]],
  ['integer_20operations_16',['Integer Operations',['../core.html#autotoc_md162',1,'']]],
  ['ir_17',['Matching IR',['../dev.html#autotoc_md25',1,'']]],
  ['is_5fempty_18',['%ord.is_empty',['../ord.html#autotoc_md299',1,'']]],
  ['is_5ffinite_19',['%math.is_finite',['../math.html#autotoc_md232',1,'']]],
  ['is_5floaded_20',['%compile.is_loaded',['../compile.html#autotoc_md151',1,'']]],
  ['is_5fsome_21',['%option.is_some',['../option.html#autotoc_md287',1,'']]],
  ['is_5funique_22',['%vec.is_unique',['../vec.html#autotoc_md373',1,'']]],
  ['item_20synchronization_23',['Work-Item Synchronization',['../gpu.html#autotoc_md212',1,'']]],
  ['iterating_20over_20the_20program_24',['Iterating over the Program',['../dev.html#autotoc_md40',1,'']]],
  ['iterations_25',['Reset Between Iterations',['../phases.html#autotoc_md65',1,'']]],
  ['iterators_26',['Iterators',['../vec.html#autotoc_md366',1,'']]]
];
