var searchData=
[
  ['named_0',['named',['../compile.html#autotoc_md286',1,'']]],
  ['names_20of_20sigmas_1',['Field Names of Sigmas',['../langref.html#field',1,'']]],
  ['naming_3a_20mimir_20vs_20mim_2',['🐉 Naming: MimIR vs. Mim',['../index.html#autotoc_md153',1,'']]],
  ['nat_3',['nat',['../core.html#autotoc_md301',1,'']]],
  ['nat_20operations_4',['Nat Operations',['../core.html#autotoc_md300',1,'']]],
  ['native_20mim_20first_5',['A native &lt;span class=&quot;tt&quot;&gt;mim&lt;/span&gt; first',['../playground.html#autotoc_md124',1,'']]],
  ['navigating_6',['Navigating',['../playground.html#autotoc_md128',1,'']]],
  ['ncmp_7',['ncmp',['../core.html#autotoc_md302',1,'']]],
  ['neg_8',['op(neg)',['../affine.html#autotoc_md195',1,'']]],
  ['neg_5flookahead_9',['neg_lookahead',['../regex.html#autotoc_md478',1,'']]],
  ['nesting_10',['Scope &amp;amp; Nesting',['../dev.html#autotoc_md40',1,'']]],
  ['nestphase_11',['NestPhase',['../phases.html#phases_nest_phase',1,'']]],
  ['nests_12',['Loop Nests',['../btensor.html#autotoc_md242',1,'']]],
  ['nestt_13',['NestT',['../btensor.html#autotoc_md248',1,'']]],
  ['new_20in_20tree_20plugin_14',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md135',1,'']]],
  ['node_15',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md175',1,'']]],
  ['nodes_16',['🌊 Sea of Nodes',['../index.html#autotoc_md151',1,'']]],
  ['non_20performance_20costs_17',['Non-performance costs',['../md_docs_2why-cpp.html#autotoc_md179',1,'']]],
  ['none_18',['none',['../option.html#autotoc_md430',1,'']]],
  ['normalizations_19',['Normalizations',['../langref.html#normalization',1,'']]],
  ['not_20apply_20here_20',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md178',1,'']]],
  ['not_20better_21',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['not_5f_22',['not_',['../regex.html#autotoc_md477',1,'']]],
  ['notation_23',['Notation',['../langref.html#autotoc_md58',1,'']]],
  ['null_24',['null',['../compile.html#autotoc_md294',1,'']]],
  ['numerical_20operations_25',['Numerical Operations',['../math.html#autotoc_md381',1,'']]],
  ['nvptx_20plugin_26',['The nvptx Plugin',['../nvptx.html',1,'']]]
];
