var searchData=
[
  ['valgrind_20gdb_0',['Valgrind &amp;amp; GDB',['../coding.html#autotoc_md29',1,'']]],
  ['values_1',['Values',['../mimir.html#mimir_dep',1,'Types Are Values'],['../regex.html#autotoc_md418',1,'Values']]],
  ['values_2',['Loop nests as first-class IR values',['../btensor.html#autotoc_md210',1,'']]],
  ['variables_3',['Variables',['../cli.html#autotoc_md8',1,'Environment Variables'],['../cli.html#clipluginenv',1,'Environment Variables'],['../dev.html#free_vars',1,'Free Variables'],['../cli.html#autotoc_md10',1,'Plugin Environment Variables'],['../dev.html#autotoc_md37',1,'Variables']]],
  ['variants_4',['Thresholded Variants',['../dev.html#autotoc_md54',1,'']]],
  ['varrewriter_5',['VarRewriter',['../rewriting.html#autotoc_md150',1,'Rewriter vs. VarRewriter'],['../rewriting.html#varrewriter',1,'VarRewriter']]],
  ['vec_6',['%ll.vec',['../ll.html#autotoc_md325',1,'']]],
  ['vec_20cat_7',['%vec.cat',['../vec.html#autotoc_md484',1,'']]],
  ['vec_20diff_8',['%vec.diff',['../vec.html#autotoc_md485',1,'']]],
  ['vec_20first_20vec_20last_9',['%vec.first / %vec.last',['../vec.html#autotoc_md480',1,'']]],
  ['vec_20fold_10',['%vec.fold',['../vec.html#autotoc_md476',1,'']]],
  ['vec_20is_5funique_11',['%vec.is_unique',['../vec.html#autotoc_md482',1,'']]],
  ['vec_20last_12',['%vec.first / %vec.last',['../vec.html#autotoc_md480',1,'']]],
  ['vec_20len_13',['%vec.len',['../vec.html#autotoc_md481',1,'']]],
  ['vec_20plugin_14',['The vec Plugin',['../vec.html',1,'']]],
  ['vec_20scan_15',['%vec.scan',['../vec.html#autotoc_md479',1,'']]],
  ['vec_20zip_16',['%vec.zip',['../vec.html#autotoc_md477',1,'']]],
  ['verdict_17',['Verdict',['../md_docs_2why-cpp.html#autotoc_md173',1,'']]],
  ['via_20cps_18',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['vs_20global_19',['Local vs. Global',['../dev.html#autotoc_md38',1,'']]],
  ['vs_20mim_20',['🐉 Naming: MimIR vs. Mim',['../index.html#autotoc_md140',1,'']]],
  ['vs_20mutables_21',['Immutables vs. Mutables',['../dev.html#mut',1,'']]],
  ['vs_20varrewriter_22',['Rewriter vs. VarRewriter',['../rewriting.html#autotoc_md150',1,'']]]
];
