var searchData=
[
  ['dbg_0',['%refly.dbg',['../refly.html#autotoc_md386',1,'']]],
  ['debugging_1',['Debugging',['../coding.html',1,'Contributing &amp; Debugging'],['../coding.html#autotoc_md13',1,'Debugging']]],
  ['debugging_20features_2',['Debugging Features',['../cli.html#clidebug',1,'']]],
  ['declaration_20blocks_3',['Local Declaration Blocks',['../langref.html#autotoc_md58',1,'']]],
  ['declarations_4',['Declarations',['../langref.html#decl',1,'Declarations'],['../langref.html#autotoc_md61',1,'Declarations']]],
  ['default_20pipeline_5',['The default pipeline',['../opt.html#autotoc_md351',1,'']]],
  ['defeats_20the_20purpose_6',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['deferred_20rewrites_7',['Deferred Rewrites',['../phases.html#autotoc_md84',1,'']]],
  ['definitions_8',['Other Definitions',['../mimir.html#autotoc_md72',1,'']]],
  ['defs_20are_20placed_20in_20them_9',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['deinit_10',['%gpu.deinit',['../gpu.html#autotoc_md279',1,'']]],
  ['delinearize_11',['%affine.delinearize',['../affine.html#autotoc_md178',1,'']]],
  ['demo_20const_5fidx_12',['%demo.const_idx',['../demo.html#autotoc_md269',1,'']]],
  ['demo_20plugin_13',['demo Plugin',['../plugins.html#autotoc_md107',1,'Example: demo Plugin'],['../demo.html',1,'The demo Plugin']]],
  ['dep_14',['&lt;span class=&quot;tt&quot;&gt;Dep&lt;/span&gt;',['../dev.html#autotoc_md30',1,'']]],
  ['dependencies_15',['Dependencies',['../coding.html#autotoc_md2',1,'Dependencies'],['../affine.html#autotoc_md165',1,'Dependencies'],['../autodiff.html#autotoc_md182',1,'Dependencies'],['../btensor.html#autotoc_md197',1,'Dependencies'],['../buffer.html#autotoc_md208',1,'Dependencies'],['../clos.html#autotoc_md221',1,'Dependencies'],['../core.html#autotoc_md240',1,'Dependencies'],['../cps.html#autotoc_md263',1,'Dependencies'],['../gpu.html#autotoc_md270',1,'Dependencies'],['../ll.html#autotoc_md304',1,'Dependencies'],['../ll_nvptx.html#autotoc_md307',1,'Dependencies'],['../mem.html#autotoc_md330',1,'Dependencies'],['../nvptx.html#autotoc_md346',1,'Dependencies'],['../opt.html#autotoc_md350',1,'Dependencies'],['../option.html#autotoc_md352',1,'Dependencies'],['../ord.html#autotoc_md362',1,'Dependencies'],['../refly.html#autotoc_md377',1,'Dependencies'],['../regex.html#autotoc_md392',1,'Dependencies'],['../tensor.html#autotoc_md410',1,'Dependencies'],['../tuple.html#autotoc_md439',1,'Dependencies'],['../vec.html#autotoc_md447',1,'Dependencies']]],
  ['deprecated_20list_16',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20pattern_17',['Recommended Design Pattern',['../phases.html#autotoc_md103',1,'']]],
  ['developer_20guide_18',['Developer Guide',['../dev.html',1,'']]],
  ['diff_19',['diff',['../autodiff.html#autotoc_md193',1,'%autodiff.diff'],['../vec.html#autotoc_md458',1,'%vec.diff']]],
  ['diff_20core_5ficmp_5fxygle_20',['%autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md194',1,'']]],
  ['diff_20core_5fwrap_5fadd_21',['%autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md195',1,'']]],
  ['diff_20core_5fwrap_5fmul_22',['%autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md196',1,'']]],
  ['differentiation_20plugin_23',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['discovery_24',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md113',1,'']]],
  ['discussion_25',['Discussion',['../phases.html#autotoc_md101',1,'']]],
  ['disj_26',['%regex.disj',['../regex.html#autotoc_md397',1,'']]],
  ['displaying_20dot_20graphs_27',['Displaying DOT Graphs',['../coding.html#autotoc_md15',1,'']]],
  ['div_28',['%core.div',['../core.html#autotoc_md252',1,'']]],
  ['dividend_20does_20not_20apply_20here_29',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['does_20not_20apply_20here_30',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['dominance_31',['Dominance',['../index.html#autotoc_md129',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['dot_20graphs_32',['Displaying DOT Graphs',['../coding.html#autotoc_md15',1,'']]],
  ['dot_5fproduct_33',['%tensor.dot_product',['../tensor.html#autotoc_md427',1,'']]],
  ['downcast_34',['General Downcast',['../dev.html#autotoc_md32',1,'']]],
  ['downcast_20to_20immutables_35',['Downcast to Immutables',['../dev.html#autotoc_md33',1,'']]],
  ['downcast_20to_20mutables_36',['Downcast to Mutables',['../dev.html#autotoc_md34',1,'']]],
  ['downcasts_20for_20built_20ins_37',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['doxygen_20style_38',['Doxygen Style',['../coding.html#autotoc_md7',1,'']]],
  ['dsl_39',['Embedded Python DSL',['../python.html#autotoc_md120',1,'']]],
  ['dumping_40',['Dumping',['../coding.html#autotoc_md14',1,'']]]
];
