var searchData=
[
  ['package_20layout_0',['Package Layout',['../python.html#autotoc_md108',1,'']]],
  ['pad_1',['pad',['../btensor.html#autotoc_md173',1,'%btensor.pad'],['../tensor.html#autotoc_md393',1,'%tensor.pad']]],
  ['page_2',['Generated Markdown Page',['../plugins.html#autotoc_md101',1,'']]],
  ['partial_20evaluation_3',['Partial Evaluation',['../dev.html#autotoc_md25',1,'']]],
  ['party_20builds_4',['Standalone Third-Party Builds',['../plugins.html#autotoc_md107',1,'']]],
  ['party_20plugin_5',['Create a Third-Party Plugin',['../plugins.html#autotoc_md104',1,'']]],
  ['party_20plugin_20discovery_6',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md105',1,'']]],
  ['passing_20arguments_20to_20plugins_7',['Passing Arguments to Plugins',['../cli.html#clipluginargs',1,'']]],
  ['pattern_8',['Recommended Design Pattern',['../phases.html#autotoc_md95',1,'']]],
  ['pattern_20terminals_9',['Pattern Terminals',['../langref.html#autotoc_md51',1,'']]],
  ['patterns_10',['Patterns',['../langref.html#ptrn',1,'']]],
  ['pe_11',['%core.pe',['../core.html#autotoc_md229',1,'']]],
  ['phase_12',['Phase',['../compile.html#autotoc_md199',1,'%compile.Phase'],['../phases.html#phases_phase',1,'Phase']]],
  ['phaseman_13',['PhaseMan',['../phases.html#phases_phase_man',1,'']]],
  ['phases_14',['Phases',['../phases.html',1,'Phases'],['../affine.html#autotoc_md147',1,'Phases'],['../autodiff.html#autotoc_md159',1,'Phases'],['../btensor.html#autotoc_md175',1,'Phases'],['../buffer.html#autotoc_md187',1,'Phases'],['../clos.html#autotoc_md197',1,'Phases'],['../compile.html#autotoc_md207',1,'Phases'],['../cps.html#autotoc_md234',1,'Phases'],['../gpu.html#autotoc_md270',1,'Phases'],['../ll.html#autotoc_md273',1,'Phases'],['../ll_nvptx.html#autotoc_md276',1,'Phases'],['../mem.html#autotoc_md313',1,'Phases'],['../nvptx.html#autotoc_md317',1,'Phases'],['../refly.html#autotoc_md361',1,'Phases'],['../regex.html#autotoc_md378',1,'Phases'],['../tensor.html#autotoc_md408',1,'Phases']]],
  ['phases_15',['%compile.phases',['../compile.html#autotoc_md206',1,'']]],
  ['picture_16',['picture',['../phases.html#autotoc_md89',1,'The classical picture'],['../phases.html#autotoc_md90',1,'The MimIR picture']]],
  ['pipeline_17',['The default pipeline',['../opt.html#autotoc_md319',1,'']]],
  ['pipelines_18',['Pipelines',['../gpu.html#autotoc_md271',1,'']]],
  ['pipelines_20in_20m⁠im_19',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md97',1,'']]],
  ['plugin_20',['Plugin',['../plugins.html#autotoc_md103',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md104',1,'Create a Third-Party Plugin'],['../plugins.html#autotoc_md99',1,'Example: demo Plugin'],['../plugins.html#autotoc_md106',1,'Extract an Existing In-Tree Plugin'],['../affine.html',1,'The affine Plugin'],['../autodiff.html',1,'The automatic differentiation Plugin'],['../btensor.html',1,'The btensor Plugin'],['../buffer.html',1,'The buffer Plugin'],['../clos.html',1,'The clos Plugin'],['../compile.html',1,'The compile Plugin'],['../core.html',1,'The core Plugin'],['../cps.html',1,'The CPS Plugin'],['../demo.html',1,'The demo Plugin'],['../gpu.html',1,'The gpu Plugin'],['../ll.html',1,'The ll Plugin'],['../ll_nvptx.html',1,'The ll_nvptx Plugin'],['../math.html',1,'The math Plugin'],['../mem.html',1,'The mem Plugin'],['../nvptx.html',1,'The nvptx Plugin'],['../opt.html',1,'The opt Plugin'],['../option.html',1,'The option Plugin'],['../ord.html',1,'The ord Plugin'],['../refly.html',1,'The refly Plugin'],['../regex.html',1,'The regex Plugin'],['../tensor.html',1,'The tensor Plugin'],['../tuple.html',1,'The tuple Plugin'],['../vec.html',1,'The vec Plugin']]],
  ['plugin_20discovery_21',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md105',1,'']]],
  ['plugin_20interfaces_22',['Generating Plugin Interfaces',['../cli.html#cligen',1,'']]],
  ['plugin_20registry_23',['Plugin Registry',['../plugins.html#autotoc_md102',1,'']]],
  ['plugins_24',['Plugins',['../index.html#autotoc_md119',1,'🧩 Plugins'],['../python.html#pyplugins',1,'Loading Plugins'],['../cli.html#clipluginargs',1,'Passing Arguments to Plugins'],['../plugins.html',1,'Plugins'],['../mimir.html#mimir_plugins',1,'Plugins']]],
  ['point_20iteration_25',['Sparse Fixed-Point Iteration',['../phases.html#autotoc_md76',1,'']]],
  ['pointer_20types_26',['Pointer Types',['../gpu.html#autotoc_md242',1,'']]],
  ['polymorphic_20iteration_27',['Polymorphic Iteration',['../mimir.html#mimir_iter',1,'']]],
  ['pool_28',['%tensor.pool',['../tensor.html#autotoc_md396',1,'']]],
  ['pow_29',['%math.pow',['../math.html#autotoc_md284',1,'']]],
  ['pre_20analysis_30',['Optional Pre-Analysis',['../phases.html#autotoc_md80',1,'']]],
  ['precedence_31',['Precedence',['../langref.html#autotoc_md58',1,'']]],
  ['prepend_32',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md413',1,'']]],
  ['preserving_20metadata_33',['Preserving Metadata',['../rewriting.html#autotoc_md128',1,'']]],
  ['primary_20terminals_34',['Primary Terminals',['../langref.html#autotoc_md48',1,'']]],
  ['product_5f2d_35',['product_2d',['../btensor.html#autotoc_md170',1,'%btensor.product_2d'],['../tensor.html#autotoc_md398',1,'%tensor.product_2d']]],
  ['products_20sequences_20unions_20and_20matching_36',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md56',1,'']]],
  ['profiling_37',['Profiling',['../coding.html#profiling',1,'']]],
  ['program_38',['Iterating over the Program',['../dev.html#autotoc_md46',1,'']]],
  ['projs_39',['Projs',['../dev.html#autotoc_md42',1,'']]],
  ['ptr_40',['%mem.Ptr',['../mem.html#autotoc_md300',1,'']]],
  ['publications_41',['📖 Publications',['../index.html#autotoc_md125',1,'']]],
  ['python_20bindings_42',['Python Bindings',['../python.html',1,'']]],
  ['python_20dsl_43',['Embedded Python DSL',['../python.html#autotoc_md112',1,'']]],
  ['python_20module_44',['Generated Python Module',['../plugins.html#autotoc_md100',1,'']]]
];
