var searchData=
[
  ['range_0',['%regex.range',['../regex.html#autotoc_md320',1,'']]],
  ['re_1',['RE',['../regex.html#autotoc_md315',1,'']]],
  ['read_2',['%matrix.read',['../matrix.html#autotoc_md234',1,'']]],
  ['recommended_20design_20pattern_3',['Recommended Design Pattern',['../phases.html#autotoc_md79',1,'']]],
  ['reduce_4',['%tensor.reduce',['../tensor.html#autotoc_md342',1,'']]],
  ['reference_5',['Reference',['../cli.html',1,'Command-Line Reference'],['../langref.html',1,'Mim Language Reference']]],
  ['refine_6',['%refly.refine',['../refly.html#autotoc_md310',1,'']]],
  ['reflect_7',['Reify / Reflect',['../refly.html#autotoc_md297',1,'']]],
  ['reflect_8',['%refly.reflect',['../refly.html#autotoc_md299',1,'']]],
  ['refly_20check_9',['%refly.check',['../refly.html#autotoc_md307',1,'']]],
  ['refly_20check_5fbot_10',['%refly.check_bot',['../refly.html#autotoc_md306',1,'']]],
  ['refly_20dbg_11',['%refly.dbg',['../refly.html#autotoc_md303',1,'']]],
  ['refly_20equiv_12',['%refly.equiv',['../refly.html#autotoc_md305',1,'']]],
  ['refly_20gid_13',['%refly.gid',['../refly.html#autotoc_md302',1,'']]],
  ['refly_20plugin_14',['The refly Plugin',['../refly.html',1,'']]],
  ['refly_20refine_15',['%refly.refine',['../refly.html#autotoc_md310',1,'']]],
  ['refly_20reflect_16',['%refly.reflect',['../refly.html#autotoc_md299',1,'']]],
  ['refly_20reify_17',['%refly.reify',['../refly.html#autotoc_md298',1,'']]],
  ['refly_20type_18',['%refly.type',['../refly.html#autotoc_md301',1,'']]],
  ['refly_20vars_19',['%refly.vars',['../refly.html#autotoc_md308',1,'']]],
  ['regex_20any_20',['%regex.any',['../regex.html#autotoc_md325',1,'']]],
  ['regex_20cls_21',['%regex.cls.*',['../regex.html#autotoc_md324',1,'']]],
  ['regex_20conj_22',['%regex.conj',['../regex.html#autotoc_md317',1,'']]],
  ['regex_20disj_23',['%regex.disj',['../regex.html#autotoc_md318',1,'']]],
  ['regex_20empty_24',['%regex.empty',['../regex.html#autotoc_md326',1,'']]],
  ['regex_20lit_25',['%regex.lit',['../regex.html#autotoc_md321',1,'']]],
  ['regex_20neg_5flookahead_26',['%regex.neg_lookahead',['../regex.html#autotoc_md323',1,'']]],
  ['regex_20not_5f_27',['%regex.not_',['../regex.html#autotoc_md322',1,'']]],
  ['regex_20plugin_28',['The regex Plugin',['../regex.html',1,'']]],
  ['regex_20quant_29',['%regex.quant.*',['../regex.html#autotoc_md328',1,'']]],
  ['regex_20range_30',['%regex.range',['../regex.html#autotoc_md320',1,'']]],
  ['registered_20translations_31',['Registered translations',['../autodiff.html#autotoc_md129',1,'']]],
  ['registry_32',['Plugin Registry',['../plugins.html#autotoc_md83',1,'']]],
  ['reify_33',['%refly.reify',['../refly.html#autotoc_md298',1,'']]],
  ['reify_20reflect_34',['Reify / Reflect',['../refly.html#autotoc_md297',1,'']]],
  ['related_20to_20longjmp_35',['Operations related to longjmp',['../clos.html#autotoc_md134',1,'']]],
  ['remem_36',['%mem.remem',['../mem.html#autotoc_md253',1,'']]],
  ['repls_37',['Repls',['../autodiff.html#autotoc_md127',1,'Repls'],['../compile.html#autotoc_md146',1,'Repls'],['../gpu.html#autotoc_md207',1,'Repls'],['../mem.html#autotoc_md263',1,'Repls'],['../refly.html#autotoc_md312',1,'Repls']]],
  ['reset_20between_20iterations_38',['Reset Between Iterations',['../phases.html#autotoc_md65',1,'']]],
  ['reshape_39',['reshape',['../tensor.html#autotoc_md338',1,'%tensor.reshape'],['../mem.html#autotoc_md265',1,'mem.reshape']]],
  ['results_40',['Analysis Results',['../phases.html#autotoc_md69',1,'']]],
  ['rewriter_41',['Rewriter',['../rewriting.html#rewriter',1,'']]],
  ['rewriter_20vs_20varrewriter_42',['Rewriter vs. VarRewriter',['../rewriting.html#autotoc_md114',1,'']]],
  ['rewrites_43',['Mutable Rewrites',['../rewriting.html#autotoc_md109',1,'']]],
  ['rewriting_44',['Rewriting',['../rewriting.html',1,'']]],
  ['right_20base_20class_45',['Choosing the Right Base Class',['../phases.html#autotoc_md78',1,'']]],
  ['round_46',['%math.round',['../math.html#autotoc_md220',1,'']]],
  ['rrt_47',['%math.rrt',['../math.html#autotoc_md226',1,'']]],
  ['rt_48',['%math.rt',['../math.html#autotoc_md215',1,'']]],
  ['rwphase_49',['RWPhase',['../phases.html#phases_rwphase',1,'']]]
];
