var searchData=
[
  ['named_0',['%compile.named',['../compile.html#autotoc_md244',1,'']]],
  ['names_20of_20sigmas_1',['Field Names of Sigmas',['../langref.html#autotoc_md77',1,'']]],
  ['naming_3a_20mimir_20vs_20mim_2',['🐉 Naming: MimIR vs. Mim',['../index.html#autotoc_md138',1,'']]],
  ['nat_3',['%core.nat',['../core.html#autotoc_md252',1,'']]],
  ['nat_20operations_4',['Nat Operations',['../core.html#autotoc_md251',1,'']]],
  ['ncmp_5',['%core.ncmp',['../core.html#autotoc_md253',1,'']]],
  ['neg_6',['%affine.op(neg)',['../affine.html#autotoc_md180',1,'']]],
  ['neg_5flookahead_7',['%regex.neg_lookahead',['../regex.html#autotoc_md420',1,'']]],
  ['nesting_8',['Scope &amp;amp; Nesting',['../dev.html#autotoc_md38',1,'']]],
  ['nestphase_9',['NestPhase',['../phases.html#phases_nest_phase',1,'']]],
  ['nests_20as_20first_20class_20ir_20values_10',['Loop nests as first-class IR values',['../btensor.html#autotoc_md208',1,'']]],
  ['new_20in_20tree_20plugin_11',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md120',1,'']]],
  ['node_12',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md160',1,'']]],
  ['nodes_13',['🌊 Sea of Nodes',['../index.html#autotoc_md136',1,'']]],
  ['non_20performance_20costs_14',['Non-performance costs',['../md_docs_2why-cpp.html#autotoc_md164',1,'']]],
  ['none_15',['%option.none',['../option.html#autotoc_md374',1,'']]],
  ['not_20apply_20here_16',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md163',1,'']]],
  ['not_20better_17',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md170',1,'']]],
  ['not_5f_18',['%regex.not_',['../regex.html#autotoc_md419',1,'']]],
  ['notation_19',['Notation',['../langref.html#autotoc_md56',1,'']]],
  ['numerical_20operations_20',['Numerical Operations',['../math.html#autotoc_md329',1,'']]],
  ['nvptx_20plugin_21',['The nvptx Plugin',['../nvptx.html',1,'']]]
];
