var searchData=
[
  ['s_20patricia_20tree_0',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; measured against OCaml&apos;s &lt;span class=&quot;tt&quot;&gt;patricia-tree&lt;/span&gt;',['../md_docs_2why-cpp.html#autotoc_md172',1,'']]],
  ['scalarize_1',['scalarize',['../compile.html#autotoc_md299',1,'']]],
  ['scan_2',['scan',['../vec.html#autotoc_md617',1,'']]],
  ['scanning_3',['Scanning',['../vec.html#autotoc_md616',1,'']]],
  ['scatter_4',['scatter',['../btensor.html#autotoc_md244',1,'scatter'],['../tensor.html#autotoc_md537',1,'scatter']]],
  ['scatter_5fstep_5fimpl_5',['scatter_step_impl',['../tensor.html#autotoc_md589',1,'']]],
  ['sccp_6',['Example: SCCP',['../phases.html#autotoc_md110',1,'']]],
  ['sched_5fid_7',['sched_id',['../tensor.html#autotoc_md559',1,'']]],
  ['schedt_8',['SchedT',['../tensor.html#autotoc_md503',1,'']]],
  ['schedule_9',['Schedule',['../tensor.html#autotoc_md558',1,'']]],
  ['schedules_10',['Schedules',['../tensor.html#autotoc_md557',1,'']]],
  ['scope_20nesting_11',['Scope &amp;amp; Nesting',['../dev.html#autotoc_md40',1,'']]],
  ['scoped_20substitution_12',['Scoped Substitution',['../rewriting.html#autotoc_md164',1,'']]],
  ['scopeless_20binders_13',['Scopeless Binders',['../mimir.html#mimir_scopeless',1,'']]],
  ['scoping_14',['Scoping',['../langref.html#autotoc_md75',1,'Scoping'],['../rewriting.html#autotoc_md158',1,'Scoping']]],
  ['sea_20of_20nodes_15',['🌊 Sea of Nodes',['../index.html#autotoc_md152',1,'']]],
  ['search_20paths_16',['Search Paths',['../cli.html#autotoc_md12',1,'']]],
  ['secondary_20terminals_17',['Secondary Terminals',['../langref.html#autotoc_md60',1,'']]],
  ['select_18',['Select',['../core.html#autotoc_md326',1,'']]],
  ['select_19',['select',['../core.html#autotoc_md325',1,'select'],['../tensor.html#autotoc_md525',1,'select']]],
  ['select_5fimpl_20',['select_impl',['../tensor.html#autotoc_md596',1,'']]],
  ['semiop_20mul_20ceildiv_20floordiv_20rem_21',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md199',1,'']]],
  ['seo_22',['seo',['../mem.html#autotoc_md420',1,'']]],
  ['set_20map_23',['Set / Map',['../ord.html#autotoc_md443',1,'']]],
  ['setjmp_24',['setjmp',['../clos.html#autotoc_md272',1,'']]],
  ['sgn_25',['sgn',['../math.html#autotoc_md401',1,'']]],
  ['shape_26',['Shape',['../dev.html#autotoc_md55',1,'Shape'],['../phases.html#autotoc_md89',1,'Typical Shape'],['../phases.html#autotoc_md102',1,'Typical Shape'],['../phases.html#autotoc_md107',1,'Typical Shape'],['../phases.html#autotoc_md108',1,'Typical Shape'],['../phases.html#autotoc_md109',1,'Typical Shape']]],
  ['shape_27',['shape',['../buffer.html#autotoc_md264',1,'shape'],['../tensor.html#autotoc_md499',1,'shape']]],
  ['shape_20operations_28',['Shape Operations',['../btensor.html#autotoc_md233',1,'Shape Operations'],['../tensor.html#autotoc_md507',1,'Shape Operations']]],
  ['shapes_29',['Shapes',['../langref.html#autotoc_md78',1,'']]],
  ['shift_5fax_30',['shift_ax',['../tensor.html#autotoc_md551',1,'']]],
  ['shr_31',['shr',['../core.html#autotoc_md313',1,'']]],
  ['side_20effects_32',['Side Effects',['../mem.html#autotoc_md407',1,'Operations w/ Side Effects'],['../mem.html#autotoc_md416',1,'Operations w/o Side Effects']]],
  ['sigmas_33',['Field Names of Sigmas',['../langref.html#field',1,'']]],
  ['single_5ferasure_34',['single_erasure',['../compile.html#autotoc_md300',1,'']]],
  ['singletons_35',['Singletons',['../langref.html#single',1,'']]],
  ['size_36',['size',['../ord.html#autotoc_md448',1,'']]],
  ['slf_37',['slf',['../math.html#autotoc_md400',1,'']]],
  ['slice_38',['slice',['../tensor.html#autotoc_md518',1,'']]],
  ['slice_5fimpl_39',['slice_impl',['../tensor.html#autotoc_md591',1,'']]],
  ['slice_5fmap_40',['slice_map',['../tensor.html#autotoc_md590',1,'']]],
  ['slot_41',['slot',['../mem.html#autotoc_md412',1,'']]],
  ['some_42',['some',['../option.html#autotoc_md433',1,'']]],
  ['some_5fif_43',['some_if',['../option.html#autotoc_md435',1,'']]],
  ['spaces_44',['Address Spaces',['../gpu.html#autotoc_md337',1,'']]],
  ['sparse_20fixed_20point_20iteration_45',['Sparse Fixed-Point Iteration',['../phases.html#autotoc_md92',1,'']]],
  ['specifically_46',['Haskell specifically',['../md_docs_2why-cpp.html#autotoc_md179',1,'']]],
  ['speculative_20construction_20with_20arena_20rollback_47',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md174',1,'']]],
  ['splat_48',['splat',['../tensor.html#autotoc_md495',1,'']]],
  ['split_5fapply_49',['split_apply',['../gpu.html#autotoc_md370',1,'']]],
  ['split_5fbounds_50',['split_bounds',['../tensor.html#autotoc_md552',1,'']]],
  ['split_5fiota_51',['split_iota',['../tensor.html#autotoc_md553',1,'']]],
  ['split_5fomega_52',['split_omega',['../tensor.html#autotoc_md554',1,'']]],
  ['ssa_20via_20cps_53',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['ssa_20without_20dominance_54',['SSA without Dominance',['../index.html#autotoc_md153',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['standalone_20third_20party_20builds_55',['Standalone Third-Party Builds',['../plugins.html#autotoc_md139',1,'']]],
  ['start_56',['Start',['../index.html#autotoc_md148',1,'🚀 Quick Start'],['../coding.html#building',1,'Contributor Quick Start']]],
  ['static_5farg_5fopt_57',['static_arg_opt',['../compile.html#autotoc_md301',1,'']]],
  ['steps_58',['First Steps',['../python.html#autotoc_md141',1,'']]],
  ['store_59',['store',['../mem.html#autotoc_md409',1,'']]],
  ['story_20is_20worse_20not_20better_60',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md188',1,'']]],
  ['stream_5fdeinit_61',['stream_deinit',['../gpu.html#autotoc_md348',1,'']]],
  ['stream_5fimpl_5frepl_62',['stream_impl_repl',['../nvptx.html#autotoc_md426',1,'']]],
  ['stream_5finit_63',['stream_init',['../gpu.html#autotoc_md347',1,'']]],
  ['stream_5fsync_64',['stream_sync',['../gpu.html#autotoc_md349',1,'']]],
  ['streams_65',['Streams',['../gpu.html#autotoc_md340',1,'Streams'],['../gpu.html#autotoc_md346',1,'Streams'],['../nvptx.html#autotoc_md424',1,'Streams']]],
  ['strip_20mining_66',['Strip-Mining',['../tensor.html#autotoc_md549',1,'']]],
  ['strip_5fmine_5fpar_67',['strip_mine_par',['../tensor.html#autotoc_md555',1,'']]],
  ['strip_5fmine_5fred_68',['strip_mine_red',['../tensor.html#autotoc_md556',1,'']]],
  ['struc_69',['struc',['../refly.html#autotoc_md466',1,'']]],
  ['structure_70',['Lexical Structure',['../langref.html#lex',1,'']]],
  ['style_71',['Style',['../coding.html#autotoc_md17',1,'C++ Style'],['../coding.html#autotoc_md20',1,'CMake Style'],['../coding.html#autotoc_md16',1,'Coding Style'],['../coding.html#autotoc_md18',1,'Doxygen Style'],['../coding.html#includes',1,'Include Style'],['../coding.html#autotoc_md22',1,'M⁠im Coding Style'],['../coding.html#autotoc_md21',1,'Markdown Style']]],
  ['style_20is_20much_20worse_72',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md175',1,'']]],
  ['sub_73',['op(add,sub)',['../affine.html#autotoc_md197',1,'']]],
  ['substitution_74',['Scoped Substitution',['../rewriting.html#autotoc_md164',1,'']]],
  ['subtags_75',['Subtags',['../dev.html#autotoc_md49',1,'With Subtags'],['../dev.html#autotoc_md48',1,'Without Subtags']]],
  ['sum_76',['sum',['../autodiff.html#autotoc_md215',1,'']]],
  ['sum_20type_20in_20one_20machine_20word_77',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md171',1,'']]],
  ['summary_78',['Summary',['../dev.html#autotoc_md46',1,'Summary'],['../dev.html#autotoc_md50',1,'Summary'],['../dev.html#autotoc_md56',1,'Summary'],['../phases.html#autotoc_md122',1,'Summary'],['../md_docs_2why-cpp.html#autotoc_md190',1,'Summary']]],
  ['summary_3a_20functions_20and_20types_79',['Summary: Functions and Types',['../langref.html#autotoc_md70',1,'']]],
  ['sync_5fwork_5fitems_80',['sync_work_items',['../gpu.html#autotoc_md363',1,'']]],
  ['synced_5fscope_81',['synced_scope',['../gpu.html#autotoc_md364',1,'']]],
  ['synchronization_82',['Work-Item Synchronization',['../gpu.html#autotoc_md362',1,'']]],
  ['syntax_83',['Syntax',['../mimir.html#autotoc_md84',1,'']]],
  ['syntax_20highlighting_84',['Syntax Highlighting',['../coding.html#autotoc_md23',1,'']]]
];
