var searchData=
[
  ['tail_0',['%tuple.head / %tuple.tail',['../tuple.html#autotoc_md440',1,'']]],
  ['tangent_1',['%autodiff.Tangent',['../autodiff.html#autotoc_md178',1,'']]],
  ['taste_20of_20mim_2',['✨ A Taste of Mim',['../index.html#autotoc_md121',1,'']]],
  ['tensor_20binary_3',['%tensor.binary',['../tensor.html#autotoc_md432',1,'']]],
  ['tensor_20bmm_4',['%tensor.bmm',['../tensor.html#autotoc_md425',1,'']]],
  ['tensor_20broadcast_5',['%tensor.broadcast',['../tensor.html#autotoc_md428',1,'']]],
  ['tensor_20broadcast_5fin_5fdim_6',['tensor broadcast_in_dim',['../tensor.html#autotoc_md429',1,'%tensor.broadcast_in_dim'],['../todo.html#_todo000003',1,'%tensor.broadcast_in_dim']]],
  ['tensor_20concat_7',['%tensor.concat',['../tensor.html#autotoc_md420',1,'']]],
  ['tensor_20conv_8',['%tensor.conv',['../tensor.html#autotoc_md421',1,'']]],
  ['tensor_20dot_5fproduct_9',['%tensor.dot_product',['../tensor.html#autotoc_md423',1,'']]],
  ['tensor_20flip_10',['%tensor.flip',['../tensor.html#autotoc_md418',1,'']]],
  ['tensor_20get_11',['%tensor.get',['../tensor.html#autotoc_md410',1,'']]],
  ['tensor_20map_12',['%tensor.map',['../tensor.html#autotoc_md430',1,'']]],
  ['tensor_20map_5freduce_13',['%tensor.map_reduce',['../tensor.html#autotoc_md414',1,'']]],
  ['tensor_20pad_14',['%tensor.pad',['../tensor.html#autotoc_md419',1,'']]],
  ['tensor_20plugin_15',['The tensor Plugin',['../tensor.html',1,'']]],
  ['tensor_20pool_16',['%tensor.pool',['../tensor.html#autotoc_md422',1,'']]],
  ['tensor_20product_5f2d_17',['%tensor.product_2d',['../tensor.html#autotoc_md424',1,'']]],
  ['tensor_20repeat_18',['%tensor.repeat',['../tensor.html#autotoc_md415',1,'']]],
  ['tensor_20reshape_19',['%tensor.reshape',['../tensor.html#autotoc_md416',1,'']]],
  ['tensor_20ring_20',['%tensor.Ring',['../tensor.html#autotoc_md408',1,'']]],
  ['tensor_20select_21',['%tensor.select',['../tensor.html#autotoc_md433',1,'']]],
  ['tensor_20set_22',['%tensor.set',['../tensor.html#autotoc_md411',1,'']]],
  ['tensor_20shape_23',['%tensor.shape',['../tensor.html#autotoc_md413',1,'']]],
  ['tensor_20slice_24',['%tensor.slice',['../tensor.html#autotoc_md417',1,'']]],
  ['tensor_20splat_25',['%tensor.splat',['../tensor.html#autotoc_md412',1,'']]],
  ['tensor_20transpose_26',['%tensor.transpose',['../tensor.html#autotoc_md426',1,'']]],
  ['tensor_20transpose_5f2d_27',['%tensor.transpose_2d',['../tensor.html#autotoc_md427',1,'']]],
  ['tensor_20unary_28',['%tensor.unary',['../tensor.html#autotoc_md431',1,'']]],
  ['terminals_29',['Terminals',['../langref.html#autotoc_md51',1,'Pattern Terminals'],['../langref.html#autotoc_md48',1,'Primary Terminals'],['../langref.html#autotoc_md49',1,'Secondary Terminals'],['../langref.html#terminals',1,'Terminals']]],
  ['testing_30',['Testing',['../coding.html#testing',1,'Testing'],['../refly.html#autotoc_md381',1,'Testing']]],
  ['tests_31',['lit Tests',['../coding.html#autotoc_md3',1,'']]],
  ['the_20affine_20plugin_32',['The affine Plugin',['../affine.html',1,'']]],
  ['the_20automatic_20differentiation_20plugin_33',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['the_20bindings_34',['Extending the Bindings',['../python.html#python_extending',1,'']]],
  ['the_20btensor_20plugin_35',['The btensor Plugin',['../btensor.html',1,'']]],
  ['the_20buffer_20plugin_36',['The buffer Plugin',['../buffer.html',1,'']]],
  ['the_20c_20implementation_20actually_20relies_20on_37',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md142',1,'']]],
  ['the_20classical_20picture_38',['The classical picture',['../phases.html#autotoc_md96',1,'']]],
  ['the_20clos_20plugin_39',['The clos Plugin',['../clos.html',1,'']]],
  ['the_20compile_20plugin_40',['The compile Plugin',['../compile.html',1,'']]],
  ['the_20core_20plugin_41',['The core Plugin',['../core.html',1,'']]],
  ['the_20cps_20plugin_42',['The CPS Plugin',['../cps.html',1,'']]],
  ['the_20default_20pipeline_43',['The default pipeline',['../opt.html#autotoc_md345',1,'']]],
  ['the_20demo_20plugin_44',['The demo Plugin',['../demo.html',1,'']]],
  ['the_20empirical_20argument_45',['The empirical argument',['../md_docs_2why-cpp.html#autotoc_md153',1,'']]],
  ['the_20escape_20hatch_20and_20why_20it_20defeats_20the_20purpose_46',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md157',1,'']]],
  ['the_20gpu_20plugin_47',['The gpu Plugin',['../gpu.html',1,'']]],
  ['the_20guard_20exists_20at_20all_48',['Why the guard exists at all',['../phases.html#autotoc_md95',1,'']]],
  ['the_20idiomatic_20dividend_20does_20not_20apply_20here_49',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md154',1,'']]],
  ['the_20link_20cut_20tree_20mutates_20in_20place_50',['The link-cut tree mutates in place',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['the_20ll_20plugin_51',['The ll Plugin',['../ll.html',1,'']]],
  ['the_20ll_5fnvptx_20plugin_52',['The ll_nvptx Plugin',['../ll_nvptx.html',1,'']]],
  ['the_20math_20plugin_53',['The math Plugin',['../math.html',1,'']]],
  ['the_20mem_20plugin_54',['The mem Plugin',['../mem.html',1,'']]],
  ['the_20mimir_20picture_55',['The MimIR picture',['../phases.html#autotoc_md97',1,'']]],
  ['the_20node_56',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md151',1,'']]],
  ['the_20nvptx_20plugin_57',['The nvptx Plugin',['../nvptx.html',1,'']]],
  ['the_20opt_20plugin_58',['The opt Plugin',['../opt.html',1,'']]],
  ['the_20option_20plugin_59',['The option Plugin',['../option.html',1,'']]],
  ['the_20ord_20plugin_60',['The ord Plugin',['../ord.html',1,'']]],
  ['the_20program_61',['Iterating over the Program',['../dev.html#autotoc_md46',1,'']]],
  ['the_20purpose_62',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md157',1,'']]],
  ['the_20refly_20plugin_63',['The refly Plugin',['../refly.html',1,'']]],
  ['the_20regex_20plugin_64',['The regex Plugin',['../regex.html',1,'']]],
  ['the_20right_20base_20class_65',['Choosing the Right Base Class',['../phases.html#autotoc_md101',1,'']]],
  ['the_20tensor_20plugin_66',['The tensor Plugin',['../tensor.html',1,'']]],
  ['the_20tuple_20plugin_67',['The tuple Plugin',['../tuple.html',1,'']]],
  ['the_20vec_20plugin_68',['The vec Plugin',['../vec.html',1,'']]],
  ['them_69',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md146',1,'']]],
  ['third_20party_20builds_70',['Standalone Third-Party Builds',['../plugins.html#autotoc_md114',1,'']]],
  ['third_20party_20plugin_71',['Create a Third-Party Plugin',['../plugins.html#autotoc_md111',1,'']]],
  ['third_20party_20plugin_20discovery_72',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md112',1,'']]],
  ['this_20is_20hard_20elsewhere_73',['Why this is hard elsewhere',['../phases.html#autotoc_md98',1,'']]],
  ['thresholded_20variants_74',['Thresholded Variants',['../dev.html#autotoc_md43',1,'']]],
  ['to_20immutables_75',['Downcast to Immutables',['../dev.html#autotoc_md33',1,'']]],
  ['to_20mutables_76',['Downcast to Mutables',['../dev.html#autotoc_md34',1,'']]],
  ['to_20plugins_77',['Passing Arguments to Plugins',['../cli.html#clipluginargs',1,'']]],
  ['todo_20list_78',['Todo List',['../todo.html',1,'']]],
  ['tour_20of_20mimir_79',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['trait_80',['%core.trait',['../core.html#autotoc_md254',1,'']]],
  ['transformation_81',['Transformation',['../phases.html#autotoc_md99',1,'']]],
  ['translations_82',['Registered translations',['../autodiff.html#autotoc_md186',1,'']]],
  ['transpose_83',['%tensor.transpose',['../tensor.html#autotoc_md426',1,'']]],
  ['transpose_5f2d_84',['transpose_2d',['../btensor.html#autotoc_md197',1,'%btensor.transpose_2d'],['../tensor.html#autotoc_md427',1,'%tensor.transpose_2d']]],
  ['tree_20mutates_20in_20place_85',['The link-cut tree mutates in place',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['tree_20plugin_86',['Tree Plugin',['../plugins.html#autotoc_md110',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md113',1,'Extract an Existing In-Tree Plugin']]],
  ['tri_87',['%math.tri',['../math.html#autotoc_md309',1,'']]],
  ['triggering_20breakpoints_88',['Triggering Breakpoints',['../coding.html#autotoc_md19',1,'']]],
  ['tuple_20append_20tuple_20prepend_89',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md439',1,'']]],
  ['tuple_20cat_90',['%tuple.cat',['../tuple.html#autotoc_md438',1,'']]],
  ['tuple_20contains_91',['%tuple.contains',['../tuple.html#autotoc_md441',1,'']]],
  ['tuple_20head_20tuple_20tail_92',['%tuple.head / %tuple.tail',['../tuple.html#autotoc_md440',1,'']]],
  ['tuple_20plugin_93',['The tuple Plugin',['../tuple.html',1,'']]],
  ['tuple_20prepend_94',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md439',1,'']]],
  ['tuple_20tail_95',['%tuple.head / %tuple.tail',['../tuple.html#autotoc_md440',1,'']]],
  ['tuple_20typecat_96',['%tuple.typecat',['../tuple.html#autotoc_md437',1,'']]],
  ['tuple_20zip_97',['%tuple.zip',['../tuple.html#autotoc_md442',1,'']]],
  ['two_20honest_20caveats_98',['Two honest caveats',['../md_docs_2why-cpp.html#autotoc_md156',1,'']]],
  ['type_99',['%refly.type',['../refly.html#autotoc_md378',1,'']]],
  ['type_20in_20one_20machine_20word_100',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md144',1,'']]],
  ['typecat_101',['%tuple.typecat',['../tuple.html#autotoc_md437',1,'']]],
  ['types_102',['Types',['../python.html#python_bindable',1,'Bindable Types'],['../langref.html#autotoc_md63',1,'Function Types'],['../langref.html#autotoc_md53',1,'Kinds and Builtin Types'],['../gpu.html#autotoc_md267',1,'Memory Types'],['../gpu.html#autotoc_md268',1,'Pointer Types'],['../langref.html#autotoc_md59',1,'Summary: Functions and Types'],['../autodiff.html#autotoc_md177',1,'Types'],['../btensor.html#autotoc_md192',1,'Types'],['../buffer.html#autotoc_md203',1,'Types'],['../compile.html#autotoc_md224',1,'Types'],['../gpu.html#autotoc_md265',1,'Types'],['../math.html#autotoc_md304',1,'Types'],['../mem.html#autotoc_md325',1,'Types'],['../nvptx.html#autotoc_md341',1,'Types'],['../option.html#autotoc_md347',1,'Types'],['../ord.html#autotoc_md357',1,'Types'],['../refly.html#autotoc_md372',1,'Types'],['../regex.html#autotoc_md389',1,'Types'],['../tensor.html#autotoc_md407',1,'Types']]],
  ['types_20are_20values_103',['Types Are Values',['../mimir.html#mimir_dep',1,'']]],
  ['typical_20shape_104',['Typical Shape',['../phases.html#autotoc_md73',1,'Typical Shape'],['../phases.html#autotoc_md85',1,'Typical Shape'],['../phases.html#autotoc_md90',1,'Typical Shape'],['../phases.html#autotoc_md91',1,'Typical Shape'],['../phases.html#autotoc_md92',1,'Typical Shape']]],
  ['typical_20usage_105',['Typical Usage',['../rewriting.html#autotoc_md136',1,'Typical Usage'],['../rewriting.html#autotoc_md138',1,'Typical Usage']]]
];
