var searchData=
[
  ['tail_0',['head / tail',['../tuple.html#autotoc_md620',1,'']]],
  ['tangent_1',['Tangent',['../autodiff.html#autotoc_md220',1,'']]],
  ['taste_20of_20mim_2',['✨ A Taste of Mim',['../index.html#autotoc_md145',1,'']]],
  ['telescopes_3',['Telescopes',['../langref.html#ptrn',1,'Patterns and Telescopes'],['../tutorial.html#autotoc_md193',1,'Patterns and Telescopes']]],
  ['tensor_4',['&lt;a class=&quot;el&quot; href=&quot;tensor.html&quot; title=&quot;The tensor Plugin&quot;&gt;tensor&lt;/a&gt;',['../cli.html#xarg_tensor',1,'']]],
  ['tensor_20plugin_5',['The tensor Plugin',['../tensor.html',1,'']]],
  ['tensor_20tensor_6',['&lt;a class=&quot;el&quot; href=&quot;tensor.html&quot; title=&quot;The tensor Plugin&quot;&gt;tensor&lt;/a&gt;',['../cli.html#xarg_tensor',1,'']]],
  ['tensor_5fcopy_7',['tensor_copy',['../tensor.html#autotoc_md578',1,'']]],
  ['terminals_8',['Terminals',['../langref.html#autotoc_md60',1,'Lexical Terminals'],['../langref.html#autotoc_md57',1,'Primary Terminals'],['../langref.html#autotoc_md58',1,'Secondary Terminals'],['../langref.html#terminals',1,'Terminals']]],
  ['testing_9',['Testing',['../coding.html#testing',1,'Testing'],['../refly.html#autotoc_md476',1,'Testing']]],
  ['tests_10',['Tests',['../coding.html#autotoc_md12',1,'lit Tests'],['../coding.html#autotoc_md13',1,'Unit Tests']]],
  ['the_20affine_20plugin_11',['The affine Plugin',['../affine.html',1,'']]],
  ['the_20automatic_20differentiation_20plugin_12',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['the_20bindings_13',['Extending the Bindings',['../python.html#python_extending',1,'']]],
  ['the_20btensor_20plugin_14',['The btensor Plugin',['../btensor.html',1,'']]],
  ['the_20buffer_20plugin_15',['The buffer Plugin',['../buffer.html',1,'']]],
  ['the_20c_20implementation_20actually_20relies_20on_16',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md168',1,'']]],
  ['the_20classical_20picture_17',['The classical picture',['../phases.html#autotoc_md112',1,'']]],
  ['the_20clos_20plugin_18',['The clos Plugin',['../clos.html',1,'']]],
  ['the_20compile_20plugin_19',['The compile Plugin',['../compile.html',1,'']]],
  ['the_20core_20plugin_20',['The core Plugin',['../core.html',1,'']]],
  ['the_20cps_20plugin_21',['The CPS Plugin',['../cps.html',1,'']]],
  ['the_20default_20pipeline_22',['The default pipeline',['../opt.html#autotoc_md439',1,'']]],
  ['the_20demo_20plugin_23',['The demo Plugin',['../demo.html',1,'']]],
  ['the_20empirical_20argument_24',['The empirical argument',['../md_docs_2why-cpp.html#autotoc_md179',1,'']]],
  ['the_20escape_20hatch_20and_20why_20it_20defeats_20the_20purpose_25',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md183',1,'']]],
  ['the_20gpu_20plugin_26',['The gpu Plugin',['../gpu.html',1,'']]],
  ['the_20guard_20exists_20at_20all_27',['Why the guard exists at all',['../phases.html#autotoc_md111',1,'']]],
  ['the_20idiomatic_20dividend_20does_20not_20apply_20here_28',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md180',1,'']]],
  ['the_20ll_20plugin_29',['The ll Plugin',['../ll.html',1,'']]],
  ['the_20ll_5fnvptx_20plugin_30',['The ll_nvptx Plugin',['../ll_nvptx.html',1,'']]],
  ['the_20math_20plugin_31',['The math Plugin',['../math.html',1,'']]],
  ['the_20mem_20plugin_32',['The mem Plugin',['../mem.html',1,'']]],
  ['the_20mimir_20picture_33',['The MimIR picture',['../phases.html#autotoc_md113',1,'']]],
  ['the_20node_34',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md177',1,'']]],
  ['the_20nvptx_20plugin_35',['The nvptx Plugin',['../nvptx.html',1,'']]],
  ['the_20opt_20plugin_36',['The opt Plugin',['../opt.html',1,'']]],
  ['the_20option_20plugin_37',['The option Plugin',['../option.html',1,'']]],
  ['the_20ord_20plugin_38',['The ord Plugin',['../ord.html',1,'']]],
  ['the_20plugin_20story_20is_20worse_20not_20better_39',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md187',1,'']]],
  ['the_20program_40',['Iterating over the Program',['../dev.html#autotoc_md55',1,'']]],
  ['the_20purpose_41',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md183',1,'']]],
  ['the_20refly_20plugin_42',['The refly Plugin',['../refly.html',1,'']]],
  ['the_20regex_20plugin_43',['The regex Plugin',['../regex.html',1,'']]],
  ['the_20right_20base_20class_44',['Choosing the Right Base Class',['../phases.html#autotoc_md117',1,'']]],
  ['the_20tensor_20plugin_45',['The tensor Plugin',['../tensor.html',1,'']]],
  ['the_20tuple_20plugin_46',['The tuple Plugin',['../tuple.html',1,'']]],
  ['the_20vec_20plugin_47',['The vec Plugin',['../vec.html',1,'']]],
  ['them_48',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md172',1,'']]],
  ['third_20party_20builds_49',['Standalone Third-Party Builds',['../plugins.html#autotoc_md138',1,'']]],
  ['third_20party_20plugin_50',['Create a Third-Party Plugin',['../plugins.html#autotoc_md136',1,'']]],
  ['third_20party_20plugin_20discovery_51',['Third-Party Plugin Discovery',['../plugins.html#extra_plugins',1,'']]],
  ['this_20is_20hard_20elsewhere_52',['Why this is hard elsewhere',['../phases.html#autotoc_md114',1,'']]],
  ['thresholded_20variants_53',['Thresholded Variants',['../dev.html#autotoc_md52',1,'']]],
  ['tileable_54',['Tileable',['../tensor.html#autotoc_md553',1,'']]],
  ['tiling_55',['Tiling',['../tensor.html#autotoc_md552',1,'']]],
  ['to_20immutables_56',['Downcast to Immutables',['../dev.html#autotoc_md42',1,'']]],
  ['to_20mutables_57',['Downcast to Mutables',['../dev.html#autotoc_md43',1,'']]],
  ['todo_20list_58',['Todo List',['../todo.html',1,'']]],
  ['tour_20of_20mimir_59',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['trait_60',['trait',['../core.html#autotoc_md334',1,'']]],
  ['transformation_61',['Transformation',['../phases.html#autotoc_md115',1,'']]],
  ['translations_62',['Registered translations',['../autodiff.html#autotoc_md230',1,'']]],
  ['transpose_63',['transpose',['../tensor.html#autotoc_md531',1,'']]],
  ['transpose_5f2d_64',['transpose_2d',['../btensor.html#autotoc_md249',1,'transpose_2d'],['../tensor.html#autotoc_md532',1,'transpose_2d']]],
  ['transpose_5f2d_5fimpl_65',['transpose_2d_impl',['../tensor.html#autotoc_md605',1,'']]],
  ['transpose_5fimpl_66',['transpose_impl',['../tensor.html#autotoc_md604',1,'']]],
  ['transpose_5fmap_67',['transpose_map',['../tensor.html#autotoc_md603',1,'']]],
  ['transpose_5fshape_68',['transpose_shape',['../tensor.html#autotoc_md530',1,'']]],
  ['tree_69',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; measured against OCaml&apos;s &lt;span class=&quot;tt&quot;&gt;patricia-tree&lt;/span&gt;',['../md_docs_2why-cpp.html#autotoc_md171',1,'']]],
  ['tree_20plugin_70',['Tree Plugin',['../plugins.html#autotoc_md135',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md137',1,'Extract an Existing In-Tree Plugin']]],
  ['tri_71',['tri',['../math.html#autotoc_md399',1,'']]],
  ['triggering_20breakpoints_72',['Triggering Breakpoints',['../coding.html#autotoc_md28',1,'']]],
  ['tuple_20plugin_73',['The tuple Plugin',['../tuple.html',1,'']]],
  ['tuple_20types_74',['Tuple Types',['../langref.html#mutsigma',1,'Dependent Tuple Types'],['../tutorial.html#autotoc_md195',1,'Dependent Tuple Types']]],
  ['tutorial_75',['Tutorial',['../tutorial.html',1,'']]],
  ['two_20honest_20caveats_76',['Two honest caveats',['../md_docs_2why-cpp.html#autotoc_md182',1,'']]],
  ['type_77',['type',['../refly.html#autotoc_md473',1,'']]],
  ['type_20in_20one_20machine_20word_78',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md170',1,'']]],
  ['typecat_79',['typecat',['../tuple.html#autotoc_md617',1,'']]],
  ['types_80',['Types',['../python.html#python_bindable',1,'Bindable Types'],['../langref.html#mutsigma',1,'Dependent Tuple Types'],['../tutorial.html#autotoc_md195',1,'Dependent Tuple Types'],['../langref.html#autotoc_md72',1,'Function Types'],['../langref.html#autotoc_md64',1,'Kinds and Builtin Types'],['../tutorial.html#autotoc_md192',1,'Kinds and Builtin Types'],['../gpu.html#autotoc_md349',1,'Memory Types'],['../gpu.html#autotoc_md350',1,'Pointer Types'],['../gpu.html#autotoc_md351',1,'Stream Types'],['../langref.html#autotoc_md68',1,'Summary: Functions and Types'],['../autodiff.html#autotoc_md219',1,'Types'],['../btensor.html#autotoc_md236',1,'Types'],['../buffer.html#autotoc_md267',1,'Types'],['../compile.html#autotoc_md294',1,'Types'],['../gpu.html#autotoc_md347',1,'Types'],['../math.html#autotoc_md392',1,'Types'],['../mem.html#autotoc_md416',1,'Types'],['../nvptx.html#autotoc_md434',1,'Types'],['../option.html#autotoc_md441',1,'Types'],['../ord.html#autotoc_md452',1,'Types'],['../refly.html#autotoc_md467',1,'Types'],['../regex.html#autotoc_md484',1,'Types'],['../tensor.html#autotoc_md502',1,'Types']]],
  ['types_20are_20values_81',['Types Are Values',['../mimir.html#mimir_dep',1,'']]],
  ['typical_20shape_82',['Typical Shape',['../phases.html#autotoc_md88',1,'Typical Shape'],['../phases.html#autotoc_md101',1,'Typical Shape'],['../phases.html#autotoc_md106',1,'Typical Shape'],['../phases.html#autotoc_md107',1,'Typical Shape'],['../phases.html#autotoc_md108',1,'Typical Shape']]],
  ['typical_20usage_83',['Typical Usage',['../rewriting.html#autotoc_md162',1,'Typical Usage'],['../rewriting.html#autotoc_md164',1,'Typical Usage']]]
];
