var searchData=
[
  ['package_20layout_0',['Package Layout',['../python.html#autotoc_md141',1,'']]],
  ['pad_1',['pad',['../btensor.html#autotoc_md250',1,'pad'],['../tensor.html#autotoc_md529',1,'pad']]],
  ['pad_5fshape_2',['pad_shape',['../tensor.html#autotoc_md528',1,'']]],
  ['page_3',['Generated Markdown Page',['../plugins.html#autotoc_md135',1,'']]],
  ['parity_4',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md187',1,'']]],
  ['partial_20evaluation_5',['Partial Evaluation',['../dev.html#autotoc_md35',1,'']]],
  ['party_20builds_6',['Standalone Third-Party Builds',['../plugins.html#autotoc_md140',1,'']]],
  ['party_20plugin_7',['Create a Third-Party Plugin',['../plugins.html#autotoc_md138',1,'']]],
  ['party_20plugin_20discovery_8',['Third-Party Plugin Discovery',['../plugins.html#extra_plugins',1,'']]],
  ['paths_9',['Search Paths',['../cli.html#autotoc_md10',1,'']]],
  ['paths_20and_20modules_10',['Paths and Modules',['../langref.html#path',1,'']]],
  ['patricia_20tree_11',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; measured against OCaml&apos;s &lt;span class=&quot;tt&quot;&gt;patricia-tree&lt;/span&gt;',['../md_docs_2why-cpp.html#autotoc_md173',1,'']]],
  ['patricia_3a_3aset_20—_20a_20four_20way_20sum_20type_20in_20one_20machine_20word_12',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md172',1,'']]],
  ['patricia_3a_3aset_20measured_20against_20ocaml_20s_20patricia_20tree_13',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; measured against OCaml&apos;s &lt;span class=&quot;tt&quot;&gt;patricia-tree&lt;/span&gt;',['../md_docs_2why-cpp.html#autotoc_md173',1,'']]],
  ['pattern_14',['Recommended Design Pattern',['../phases.html#autotoc_md120',1,'']]],
  ['patterns_20and_20telescopes_15',['Patterns and Telescopes',['../langref.html#ptrn',1,'Patterns and Telescopes'],['../tutorial.html#autotoc_md195',1,'Patterns and Telescopes']]],
  ['pe_16',['pe',['../core.html#autotoc_md338',1,'']]],
  ['performance_20costs_17',['Non-performance costs',['../md_docs_2why-cpp.html#autotoc_md183',1,'']]],
  ['performance_20parity_18',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md187',1,'']]],
  ['phase_19',['Phase',['../phases.html#phases_phase',1,'Phase'],['../compile.html#autotoc_md298',1,'Phase']]],
  ['phaseman_20',['PhaseMan',['../phases.html#phases_phase_man',1,'']]],
  ['phases_21',['Phases',['../phases.html',1,'Phases'],['../affine.html#autotoc_md218',1,'Phases'],['../autodiff.html#autotoc_md230',1,'Phases'],['../btensor.html#autotoc_md267',1,'Phases'],['../buffer.html#autotoc_md280',1,'Phases'],['../clos.html#autotoc_md290',1,'Phases'],['../compile.html#autotoc_md305',1,'Phases'],['../cps.html#autotoc_md345',1,'Phases'],['../gpu.html#autotoc_md379',1,'Phases'],['../ll.html#autotoc_md388',1,'Phases'],['../ll_nvptx.html#autotoc_md393',1,'Phases'],['../mem.html#autotoc_md432',1,'Phases'],['../nvptx.html#autotoc_md439',1,'Phases'],['../refly.html#autotoc_md484',1,'Phases'],['../regex.html#autotoc_md502',1,'Phases'],['../tensor.html#autotoc_md612',1,'Phases']]],
  ['phases_22',['phases',['../compile.html#autotoc_md304',1,'']]],
  ['picture_23',['picture',['../phases.html#autotoc_md114',1,'The classical picture'],['../phases.html#autotoc_md115',1,'The MimIR picture']]],
  ['pipeline_24',['The default pipeline',['../opt.html#autotoc_md442',1,'']]],
  ['pipelines_25',['Pipelines',['../gpu.html#autotoc_md386',1,'']]],
  ['pipelines_20in_20m⁠im_26',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md122',1,'']]],
  ['placed_20in_20them_27',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md174',1,'']]],
  ['playground_28',['Playground',['../playground.html',1,'']]],
  ['plugin_29',['Plugin',['../plugins.html#autotoc_md137',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md138',1,'Create a Third-Party Plugin'],['../plugins.html#autotoc_md133',1,'Example: demo Plugin'],['../plugins.html#autotoc_md139',1,'Extract an Existing In-Tree Plugin'],['../affine.html',1,'The affine Plugin'],['../autodiff.html',1,'The automatic differentiation Plugin'],['../btensor.html',1,'The btensor Plugin'],['../buffer.html',1,'The buffer Plugin'],['../clos.html',1,'The clos Plugin'],['../compile.html',1,'The compile Plugin'],['../core.html',1,'The core Plugin'],['../cps.html',1,'The CPS Plugin'],['../demo.html',1,'The demo Plugin'],['../gpu.html',1,'The gpu Plugin'],['../ll.html',1,'The ll Plugin'],['../ll_nvptx.html',1,'The ll_nvptx Plugin'],['../math.html',1,'The math Plugin'],['../mem.html',1,'The mem Plugin'],['../nvptx.html',1,'The nvptx Plugin'],['../opt.html',1,'The opt Plugin'],['../option.html',1,'The option Plugin'],['../ord.html',1,'The ord Plugin'],['../refly.html',1,'The refly Plugin'],['../regex.html',1,'The regex Plugin'],['../tensor.html',1,'The tensor Plugin'],['../tuple.html',1,'The tuple Plugin'],['../vec.html',1,'The vec Plugin']]],
  ['plugin_20arguments_30',['Plugin Arguments',['../cli.html#xargs',1,'']]],
  ['plugin_20discovery_31',['Third-Party Plugin Discovery',['../plugins.html#extra_plugins',1,'']]],
  ['plugin_20environment_20variables_32',['Plugin Environment Variables',['../cli.html#envs',1,'']]],
  ['plugin_20registry_33',['Plugin Registry',['../plugins.html#autotoc_md136',1,'']]],
  ['plugin_20story_20is_20worse_20not_20better_34',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md189',1,'']]],
  ['plugins_35',['Plugins',['../index.html#autotoc_md152',1,'🧩 Plugins'],['../python.html#pyplugins',1,'Loading Plugins'],['../plugins.html',1,'Plugins'],['../cli.html#autotoc_md9',1,'Plugins'],['../mimir.html#mimir_plugins',1,'Plugins']]],
  ['point_20iteration_36',['Sparse Fixed-Point Iteration',['../phases.html#autotoc_md93',1,'']]],
  ['pointer_20types_37',['Pointer Types',['../gpu.html#autotoc_md353',1,'']]],
  ['pointers_20become_20map_20lookups_38',['Pointers become map lookups',['../md_docs_2why-cpp.html#autotoc_md177',1,'']]],
  ['points_39',['Fixed Points',['../phases.html#autotoc_md107',1,'']]],
  ['polymorphic_20iteration_40',['Polymorphic Iteration',['../mimir.html#mimir_iter',1,'']]],
  ['pool_41',['pool',['../tensor.html#autotoc_md547',1,'']]],
  ['pool2d_5fin_5fmap_42',['pool2d_in_map',['../tensor.html#autotoc_md589',1,'']]],
  ['pool_5ffun_43',['pool_fun',['../tensor.html#autotoc_md588',1,'']]],
  ['pool_5fimpl_44',['pool_impl',['../tensor.html#autotoc_md590',1,'']]],
  ['pool_5fschedule_45',['pool_schedule',['../tensor.html#autotoc_md579',1,'']]],
  ['pow_46',['pow',['../math.html#autotoc_md403',1,'']]],
  ['pre_20analysis_47',['Optional Pre-Analysis',['../phases.html#autotoc_md96',1,'']]],
  ['precedence_48',['Precedence',['../langref.html#prec',1,'']]],
  ['prepend_49',['append / prepend',['../tuple.html#autotoc_md622',1,'']]],
  ['preserving_20metadata_50',['Preserving Metadata',['../rewriting.html#autotoc_md163',1,'']]],
  ['primary_20terminals_51',['Primary Terminals',['../langref.html#autotoc_md58',1,'']]],
  ['product_5f2d_52',['product_2d',['../btensor.html#autotoc_md255',1,'product_2d'],['../tensor.html#autotoc_md548',1,'product_2d']]],
  ['product_5f2d_5ffun_53',['product_2d_fun',['../btensor.html#autotoc_md254',1,'']]],
  ['product_5f2d_5fimpl_54',['product_2d_impl',['../tensor.html#autotoc_md602',1,'']]],
  ['products_55',['Products',['../langref.html#prod',1,'']]],
  ['profiling_56',['Profiling',['../cli.html#autotoc_md5',1,'Profiling'],['../coding.html#profiling',1,'Profiling']]],
  ['program_57',['Iterating over the Program',['../dev.html#autotoc_md56',1,'']]],
  ['proj_5fmap_58',['proj_map',['../btensor.html#autotoc_md246',1,'proj_map'],['../tensor.html#autotoc_md520',1,'proj_map']]],
  ['projs_59',['Projs',['../dev.html#autotoc_md52',1,'']]],
  ['pruning_60',['Pruning',['../phases.html#autotoc_md105',1,'']]],
  ['ptr_61',['Ptr',['../mem.html#autotoc_md420',1,'']]],
  ['publications_62',['📖 Publications',['../index.html#autotoc_md158',1,'']]],
  ['purpose_63',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['python_20bindings_64',['Python Bindings',['../python.html',1,'']]],
  ['python_20dsl_65',['Embedded Python DSL',['../python.html#autotoc_md145',1,'']]],
  ['python_20module_66',['Generated Python Module',['../plugins.html#autotoc_md134',1,'']]]
];
