var searchData=
[
  ['gamma_0',['math.gamma',['../math.html#autotoc_md332',1,'']]],
  ['gather_1',['gather',['../btensor.html#autotoc_md216',1,'gather'],['../tensor.html#autotoc_md458',1,'gather']]],
  ['gdb_2',['Valgrind &amp;amp; GDB',['../coding.html#autotoc_md29',1,'']]],
  ['general_20downcast_3',['General Downcast',['../dev.html#autotoc_md43',1,'']]],
  ['generated_20header_4',['Generated Header',['../plugins.html#plugin_h',1,'']]],
  ['generated_20interfaces_5',['Generated Interfaces',['../plugins.html#plugin_codegen',1,'']]],
  ['generated_20markdown_20page_6',['Generated Markdown Page',['../plugins.html#autotoc_md117',1,'']]],
  ['generated_20python_20module_7',['Generated Python Module',['../plugins.html#autotoc_md116',1,'']]],
  ['genuinely_20wins_8',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md168',1,'']]],
  ['get_9',['get',['../tensor.html#autotoc_md427',1,'get'],['../ord.html#autotoc_md386',1,'ord.get']]],
  ['gid_10',['refly.gid',['../refly.html#autotoc_md398',1,'']]],
  ['global_11',['Local vs. Global',['../dev.html#autotoc_md38',1,'']]],
  ['gpu_20alloc_20asyn_12',['gpu.alloc(block) / gpu.alloc(asyn)',['../gpu.html#autotoc_md299',1,'']]],
  ['gpu_20alloc_20block_20gpu_20alloc_20asyn_13',['gpu.alloc(block) / gpu.alloc(asyn)',['../gpu.html#autotoc_md299',1,'']]],
  ['gpu_20alloc_5fcopy_20asyn_14',['gpu.alloc_copy(block) / gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md303',1,'']]],
  ['gpu_20alloc_5fcopy_20block_20gpu_20alloc_5fcopy_20asyn_15',['gpu.alloc_copy(block) / gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md303',1,'']]],
  ['gpu_20auto_5fdeinit_16',['gpu.auto_init / gpu.auto_deinit',['../gpu.html#autotoc_md292',1,'']]],
  ['gpu_20auto_5finit_20gpu_20auto_5fdeinit_17',['gpu.auto_init / gpu.auto_deinit',['../gpu.html#autotoc_md292',1,'']]],
  ['gpu_20buf_5falloc_5fcopy_18',['gpu.buf_alloc_copy',['../gpu.html#autotoc_md305',1,'']]],
  ['gpu_20buf_5fcopy_5fto_5fhost_19',['gpu.buf_copy_to_host',['../gpu.html#autotoc_md306',1,'']]],
  ['gpu_20copy_5fto_5fdevice_20asyn_20',['gpu.copy_to_device(block) / gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md301',1,'']]],
  ['gpu_20copy_5fto_5fdevice_20block_20gpu_20copy_5fto_5fdevice_20asyn_21',['gpu.copy_to_device(block) / gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md301',1,'']]],
  ['gpu_20copy_5fto_5fhost_20asyn_22',['gpu.copy_to_host(block) / gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md302',1,'']]],
  ['gpu_20copy_5fto_5fhost_20block_20gpu_20copy_5fto_5fhost_20asyn_23',['gpu.copy_to_host(block) / gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md302',1,'']]],
  ['gpu_20deinit_24',['gpu.deinit',['../gpu.html#autotoc_md291',1,'']]],
  ['gpu_20free_20asyn_25',['gpu.free(block) / gpu.free(asyn)',['../gpu.html#autotoc_md300',1,'']]],
  ['gpu_20free_20block_20gpu_20free_20asyn_26',['gpu.free(block) / gpu.free(asyn)',['../gpu.html#autotoc_md300',1,'']]],
  ['gpu_20init_27',['gpu.init',['../gpu.html#autotoc_md290',1,'']]],
  ['gpu_20launch_28',['gpu.launch',['../gpu.html#autotoc_md308',1,'']]],
  ['gpu_20plugin_29',['The gpu Plugin',['../gpu.html',1,'']]],
  ['gpu_20stream_5fdeinit_30',['gpu.stream_deinit',['../gpu.html#autotoc_md295',1,'']]],
  ['gpu_20stream_5finit_31',['gpu.stream_init',['../gpu.html#autotoc_md294',1,'']]],
  ['gpu_20stream_5fsync_32',['gpu.stream_sync',['../gpu.html#autotoc_md296',1,'']]],
  ['gpu_20sync_5fwork_5fitems_33',['gpu.sync_work_items',['../gpu.html#autotoc_md310',1,'']]],
  ['gpu_20synced_5fscope_34',['gpu.synced_scope',['../gpu.html#autotoc_md311',1,'']]],
  ['gpu_20with_5fstreams_35',['gpu.with_streams',['../gpu.html#autotoc_md297',1,'']]],
  ['grammar_36',['Grammar',['../langref.html#grammar',1,'']]],
  ['graphs_37',['Displaying DOT Graphs',['../coding.html#autotoc_md26',1,'']]],
  ['guard_20exists_20at_20all_38',['Why the guard exists at all',['../phases.html#autotoc_md104',1,'']]],
  ['guide_39',['Developer Guide',['../dev.html',1,'']]]
];
