var searchData=
[
  ['gamma_0',['%math.gamma',['../math.html#autotoc_md240',1,'']]],
  ['gdb_1',['Valgrind &amp;amp; GDB',['../coding.html#autotoc_md17',1,'']]],
  ['general_20downcast_2',['General Downcast',['../dev.html#autotoc_md26',1,'']]],
  ['get_3',['get',['../ord.html#autotoc_md309',1,'%ord.get'],['../tensor.html#autotoc_md351',1,'tensor.get']]],
  ['gid_4',['%refly.gid',['../refly.html#autotoc_md320',1,'']]],
  ['googletest_5',['GoogleTest',['../coding.html#autotoc_md3',1,'']]],
  ['gpu_20alloc_20asyn_6',['%gpu.alloc(asyn)',['../gpu.html#autotoc_md213',1,'']]],
  ['gpu_20alloc_20block_7',['%gpu.alloc(block)',['../gpu.html#autotoc_md207',1,'']]],
  ['gpu_20alloc_5fcopy_20asyn_8',['%gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md217',1,'']]],
  ['gpu_20alloc_5fcopy_20block_9',['%gpu.alloc_copy(block)',['../gpu.html#autotoc_md211',1,'']]],
  ['gpu_20copy_5fto_5fdevice_20asyn_10',['%gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md215',1,'']]],
  ['gpu_20copy_5fto_5fdevice_20block_11',['%gpu.copy_to_device(block)',['../gpu.html#autotoc_md209',1,'']]],
  ['gpu_20copy_5fto_5fhost_20asyn_12',['%gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md216',1,'']]],
  ['gpu_20copy_5fto_5fhost_20block_13',['%gpu.copy_to_host(block)',['../gpu.html#autotoc_md210',1,'']]],
  ['gpu_20deinit_14',['%gpu.deinit',['../gpu.html#autotoc_md200',1,'']]],
  ['gpu_20free_20asyn_15',['%gpu.free(asyn)',['../gpu.html#autotoc_md214',1,'']]],
  ['gpu_20free_20block_16',['%gpu.free(block)',['../gpu.html#autotoc_md208',1,'']]],
  ['gpu_20init_17',['%gpu.init',['../gpu.html#autotoc_md199',1,'']]],
  ['gpu_20launch_18',['%gpu.launch',['../gpu.html#autotoc_md219',1,'']]],
  ['gpu_20plugin_19',['The gpu Plugin',['../gpu.html',1,'']]],
  ['gpu_20stream_5fdeinit_20',['%gpu.stream_deinit',['../gpu.html#autotoc_md203',1,'']]],
  ['gpu_20stream_5finit_21',['%gpu.stream_init',['../gpu.html#autotoc_md202',1,'']]],
  ['gpu_20stream_5fsync_22',['%gpu.stream_sync',['../gpu.html#autotoc_md204',1,'']]],
  ['gpu_20sync_5fwork_5fitems_23',['%gpu.sync_work_items',['../gpu.html#autotoc_md221',1,'']]],
  ['gpu_20synced_5fscope_24',['%gpu.synced_scope',['../gpu.html#autotoc_md222',1,'']]],
  ['gpu_20with_5fstreams_25',['%gpu.with_streams',['../gpu.html#autotoc_md205',1,'']]],
  ['grammar_26',['Grammar',['../langref.html#grammar',1,'']]],
  ['graphs_27',['Displaying DOT Graphs',['../coding.html#autotoc_md14',1,'']]],
  ['guide_28',['Developer Guide',['../dev.html',1,'']]]
];
