var searchData=
[
  ['range_0',['range',['../regex.html#autotoc_md494',1,'']]],
  ['range_5fnest_1',['range_nest',['../btensor.html#autotoc_md264',1,'']]],
  ['range_5funroll_2',['range_unroll',['../btensor.html#autotoc_md265',1,'']]],
  ['re_3',['RE',['../regex.html#autotoc_md489',1,'']]],
  ['read_4',['read',['../buffer.html#autotoc_md275',1,'']]],
  ['reassoc_5',['reassoc',['../tensor.html#autotoc_md614',1,'']]],
  ['recommended_20design_20pattern_6',['Recommended Design Pattern',['../phases.html#autotoc_md121',1,'']]],
  ['reduce_7',['Reduce',['../btensor.html#autotoc_md242',1,'Map-Reduce'],['../tensor.html#autotoc_md515',1,'Map-Reduce']]],
  ['reductions_8',['Reductions',['../btensor.html#autotoc_md254',1,'Reductions'],['../tensor.html#autotoc_md542',1,'Reductions']]],
  ['reference_9',['Reference',['../cli.html',1,'Command-Line Reference'],['../langref.html',1,'Mim Language Reference']]],
  ['reflect_10',['Reify / Reflect',['../refly.html#autotoc_md473',1,'']]],
  ['reflect_11',['reflect',['../refly.html#autotoc_md475',1,'']]],
  ['reflection_12',['Reflection',['../tensor.html#autotoc_md553',1,'']]],
  ['refly_20plugin_13',['The refly Plugin',['../refly.html',1,'']]],
  ['regex_20plugin_14',['The regex Plugin',['../regex.html',1,'']]],
  ['registered_20translations_15',['Registered translations',['../autodiff.html#autotoc_md234',1,'']]],
  ['registry_16',['Plugin Registry',['../plugins.html#autotoc_md137',1,'']]],
  ['reify_17',['reify',['../refly.html#autotoc_md474',1,'']]],
  ['reify_20reflect_18',['Reify / Reflect',['../refly.html#autotoc_md473',1,'']]],
  ['relies_20on_19',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md171',1,'']]],
  ['rem_20',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md214',1,'']]],
  ['remove_5fdbg_5frepl_21',['remove_dbg_repl',['../refly.html#autotoc_md486',1,'']]],
  ['remove_5fdouble_5fsyncs_22',['remove_double_syncs',['../gpu.html#autotoc_md384',1,'']]],
  ['repeat_23',['repeat',['../tensor.html#autotoc_md531',1,'']]],
  ['repeat_5fimpl_24',['repeat_impl',['../tensor.html#autotoc_md593',1,'']]],
  ['repeat_5fmap_25',['repeat_map',['../tensor.html#autotoc_md592',1,'']]],
  ['reset_20between_20iterations_26',['Reset Between Iterations',['../phases.html#autotoc_md94',1,'']]],
  ['reshape_27',['reshape',['../tensor.html#autotoc_md532',1,'']]],
  ['reshape_5fimpl_28',['reshape_impl',['../tensor.html#autotoc_md595',1,'']]],
  ['reshape_5fmap_29',['reshape_map',['../tensor.html#autotoc_md594',1,'']]],
  ['reshaping_20aggregates_30',['Reshaping Aggregates',['../phases.html#autotoc_md102',1,'Reshaping Aggregates'],['../rewriting.html#autotoc_md162',1,'Reshaping Aggregates']]],
  ['restrictions_31',['Restrictions',['../phases.html#autotoc_md104',1,'']]],
  ['results_32',['Analysis Results',['../phases.html#autotoc_md97',1,'']]],
  ['ret_5fwrap_33',['ret_wrap',['../compile.html#autotoc_md313',1,'']]],
  ['rewriter_34',['Rewriter',['../rewriting.html#rewriter',1,'']]],
  ['rewriter_20vs_20varrewriter_35',['Rewriter vs. VarRewriter',['../rewriting.html#autotoc_md168',1,'']]],
  ['rewrites_36',['Rewrites',['../phases.html#autotoc_md100',1,'Deferred Rewrites'],['../rewriting.html#autotoc_md161',1,'Mutable Rewrites']]],
  ['rewriting_37',['Rewriting',['../rewriting.html',1,'']]],
  ['right_20base_20class_38',['Choosing the Right Base Class',['../phases.html#autotoc_md120',1,'']]],
  ['ring_39',['Ring',['../btensor.html#autotoc_md241',1,'Ring'],['../tensor.html#autotoc_md507',1,'Ring']]],
  ['rollback_40',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md176',1,'']]],
  ['roots_41',['Roots',['../phases.html#autotoc_md99',1,'Roots'],['../phases.html#autotoc_md106',1,'Roots']]],
  ['roughly_20performance_20parity_42',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md188',1,'']]],
  ['round_43',['round',['../math.html#autotoc_md410',1,'']]],
  ['round_20trip_20tests_44',['Round-Trip Tests',['../coding.html#autotoc_md13',1,'']]],
  ['rrt_45',['rrt',['../math.html#autotoc_md417',1,'']]],
  ['rt_46',['rt',['../math.html#autotoc_md405',1,'']]],
  ['rules_47',['Modules, Visibility, Annexes, Axioms, and Rules',['../tutorial.html#autotoc_md204',1,'']]],
  ['running_48',['Running',['../playground.html#autotoc_md129',1,'']]],
  ['runtime_20wrappers_49',['Runtime Wrappers',['../plugins.html#plugin_runtime',1,'']]],
  ['rust_50',['What about Rust?',['../md_docs_2why-cpp.html#autotoc_md187',1,'']]],
  ['rust_20genuinely_20wins_51',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md189',1,'']]],
  ['rust_20would_20land_20at_20roughly_20performance_20parity_52',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md188',1,'']]],
  ['rwbase_53',['RWBase',['../phases.html#phases_rwbase',1,'']]],
  ['rwphase_54',['RWPhase',['../phases.html#phases_rwphase',1,'']]]
];
