var searchData=
[
  ['w_20o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md337',1,'']]],
  ['w_20side_20effects_1',['Operations w/ Side Effects',['../mem.html#autotoc_md327',1,'']]],
  ['way_20sum_20type_20in_20one_20machine_20word_2',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md144',1,'']]],
  ['what_20the_20c_20implementation_20actually_20relies_20on_3',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md142',1,'']]],
  ['why_20idiomatic_20style_20is_20much_20worse_4',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md148',1,'']]],
  ['why_20is_20mimir_20implemented_20in_20c_5',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['why_20it_20defeats_20the_20purpose_6',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md157',1,'']]],
  ['why_20mimir_7',['💡 Why MimIR?',['../index.html#autotoc_md122',1,'']]],
  ['why_20the_20guard_20exists_20at_20all_8',['Why the guard exists at all',['../phases.html#autotoc_md95',1,'']]],
  ['why_20this_20is_20hard_20elsewhere_9',['Why this is hard elsewhere',['../phases.html#autotoc_md98',1,'']]],
  ['with_20arena_20rollback_10',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['with_20indices_11',['Working with Indices',['../dev.html#autotoc_md40',1,'']]],
  ['with_20subtags_12',['With Subtags',['../dev.html#autotoc_md38',1,'']]],
  ['with_5fstreams_13',['%gpu.with_streams',['../gpu.html#autotoc_md278',1,'']]],
  ['without_20dominance_14',['without Dominance',['../index.html#autotoc_md128',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['without_20subtags_15',['Without Subtags',['../dev.html#autotoc_md37',1,'']]],
  ['word_16',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md144',1,'']]],
  ['work_20item_20synchronization_17',['Work-Item Synchronization',['../gpu.html#autotoc_md293',1,'']]],
  ['working_20with_20indices_18',['Working with Indices',['../dev.html#autotoc_md40',1,'']]],
  ['worse_19',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md148',1,'']]],
  ['wrap_20',['%core.wrap',['../core.html#autotoc_md245',1,'']]],
  ['wrappers_21',['Runtime Wrappers',['../plugins.html#plugin_runtime',1,'']]],
  ['write_22',['%buffer.write',['../buffer.html#autotoc_md208',1,'']]]
];
