var searchData=
[
  ['named_0',['named',['../compile.html#autotoc_md308',1,'']]],
  ['names_20of_20sigmas_1',['Field Names of Sigmas',['../langref.html#field',1,'']]],
  ['naming_3a_20mimir_20vs_20mim_2',['🐉 Naming: MimIR vs. Mim',['../index.html#autotoc_md158',1,'']]],
  ['nan_3',['inf, neg_inf, nan',['../math.html#autotoc_md423',1,'']]],
  ['nat_4',['nat',['../core.html#autotoc_md327',1,'']]],
  ['nat_20operations_5',['Nat Operations',['../core.html#autotoc_md326',1,'']]],
  ['native_20mim_20first_6',['A native &lt;span class=&quot;tt&quot;&gt;mim&lt;/span&gt; first',['../playground.html#autotoc_md129',1,'']]],
  ['navigating_7',['Navigating',['../playground.html#autotoc_md133',1,'']]],
  ['ncmp_8',['ncmp',['../core.html#autotoc_md328',1,'']]],
  ['neg_9',['op(neg)',['../affine.html#autotoc_md218',1,'']]],
  ['neg_5finf_20nan_10',['inf, neg_inf, nan',['../math.html#autotoc_md423',1,'']]],
  ['neg_5flookahead_11',['neg_lookahead',['../regex.html#autotoc_md506',1,'']]],
  ['nesting_12',['Scope &amp;amp; Nesting',['../dev.html#autotoc_md40',1,'']]],
  ['nestphase_13',['NestPhase',['../phases.html#phases_nest_phase',1,'']]],
  ['nests_14',['Loop Nests',['../btensor.html#autotoc_md263',1,'']]],
  ['nestt_15',['NestT',['../btensor.html#autotoc_md270',1,'']]],
  ['new_20in_20tree_20plugin_16',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md140',1,'']]],
  ['newtypes_17',['Newtypes',['../langref.html#nominal',1,'Nominal Newtypes'],['../langref.html#autotoc_md85',1,'Nominal Newtypes'],['../tutorial.html#autotoc_md205',1,'Nominal Newtypes']]],
  ['node_18',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md182',1,'']]],
  ['nodes_19',['🌊 Sea of Nodes',['../index.html#autotoc_md156',1,'']]],
  ['nom_5ferasure_20',['nom_erasure',['../compile.html#autotoc_md317',1,'']]],
  ['nominal_20newtypes_21',['Nominal Newtypes',['../langref.html#nominal',1,'Nominal Newtypes'],['../langref.html#autotoc_md85',1,'Nominal Newtypes'],['../tutorial.html#autotoc_md205',1,'Nominal Newtypes']]],
  ['non_20performance_20costs_22',['Non-performance costs',['../md_docs_2why-cpp.html#autotoc_md186',1,'']]],
  ['none_23',['none',['../option.html#autotoc_md458',1,'']]],
  ['normalizations_24',['Normalizations',['../langref.html#normalization',1,'']]],
  ['not_20apply_20here_25',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['not_20better_26',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md192',1,'']]],
  ['not_5f_27',['not_',['../regex.html#autotoc_md505',1,'']]],
  ['notation_28',['Notation',['../langref.html#autotoc_md58',1,'']]],
  ['novec_29',['novec',['../ll.html#autotoc_md400',1,'']]],
  ['novec_5ffor_30',['novec_for',['../btensor.html#autotoc_md267',1,'']]],
  ['null_31',['null',['../compile.html#autotoc_md318',1,'']]],
  ['numerical_20operations_32',['Numerical Operations',['../math.html#autotoc_md408',1,'']]],
  ['nvptx_20plugin_33',['The nvptx Plugin',['../nvptx.html',1,'']]]
];
