var searchData=
[
  ['icmp_0',['icmp',['../core.html#autotoc_md338',1,'']]],
  ['id_1',['id',['../affine.html#autotoc_md221',1,'id'],['../btensor.html#autotoc_md246',1,'id'],['../tensor.html#autotoc_md525',1,'id']]],
  ['idiomatic_20dividend_20does_20not_20apply_20here_2',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['idiomatic_20style_20is_20much_20worse_3',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md179',1,'']]],
  ['idx_4',['idx',['../core.html#autotoc_md331',1,'']]],
  ['idx_5funsafe_5',['idx_unsafe',['../core.html#autotoc_md332',1,'']]],
  ['if_5fstatic_6',['if_static',['../tensor.html#autotoc_md564',1,'']]],
  ['immutables_7',['Immutables',['../dev.html#autotoc_md44',1,'Downcast to Immutables'],['../dev.html#autotoc_md32',1,'Immutables']]],
  ['immutables_20vs_20mutables_8',['Immutables vs. Mutables',['../dev.html#mut',1,'']]],
  ['implementation_20actually_20relies_20on_9',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md173',1,'']]],
  ['implementations_10',['Implementations',['../tensor.html#autotoc_md591',1,'']]],
  ['implemented_20in_20c_11',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['imports_12',['Files and Imports',['../langref.html#module',1,'']]],
  ['imports_20and_20modules_13',['Files, Imports, and Modules',['../tutorial.html#autotoc_md195',1,'']]],
  ['impure_14',['Hash-consing is inherently impure',['../md_docs_2why-cpp.html#autotoc_md181',1,'']]],
  ['in_20c_15',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['in_20m⁠im_16',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md125',1,'']]],
  ['in_20one_20machine_20word_17',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md175',1,'']]],
  ['in_20them_18',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md177',1,'']]],
  ['in_20tree_20plugin_19',['In Tree Plugin',['../plugins.html#autotoc_md140',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md142',1,'Extract an Existing In-Tree Plugin']]],
  ['include_20style_20',['Include Style',['../coding.html#includes',1,'']]],
  ['index_21',['Index',['../affine.html#autotoc_md215',1,'']]],
  ['index_20operations_22',['Affine Index Operations',['../affine.html#autotoc_md214',1,'']]],
  ['indexing_23',['Indexing',['../btensor.html#autotoc_md260',1,'Indexing'],['../tensor.html#autotoc_md559',1,'Indexing']]],
  ['indices_24',['Working with Indices',['../dev.html#autotoc_md51',1,'']]],
  ['inf_20neg_5finf_20nan_25',['inf, neg_inf, nan',['../math.html#autotoc_md423',1,'']]],
  ['infix_20operators_26',['Infix Operators',['../langref.html#infix',1,'Infix Operators'],['../tutorial.html#autotoc_md206',1,'Infix Operators']]],
  ['inherently_20impure_27',['Hash-consing is inherently impure',['../md_docs_2why-cpp.html#autotoc_md181',1,'']]],
  ['init_28',['init',['../buffer.html#autotoc_md281',1,'init'],['../gpu.html#autotoc_md365',1,'init'],['../ord.html#autotoc_md469',1,'init']]],
  ['innovations_29',['🔥 Key Innovations',['../index.html#autotoc_md154',1,'']]],
  ['inplacerwphase_30',['InplaceRWPhase',['../phases.html#phases_inplace_rw_phase',1,'']]],
  ['ins_31',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['insert_32',['Insert',['../langref.html#autotoc_md80',1,'']]],
  ['insert_33',['insert',['../ord.html#autotoc_md478',1,'']]],
  ['inspect_34',['Inspect',['../refly.html#autotoc_md485',1,'']]],
  ['install_20optional_35',['📦 Install (Optional)',['../index.html#autotoc_md153',1,'']]],
  ['integer_20operations_36',['Integer Operations',['../core.html#autotoc_md329',1,'']]],
  ['interchange_37',['interchange',['../tensor.html#autotoc_md569',1,'']]],
  ['interfaces_38',['Generated Interfaces',['../plugins.html#plugin_codegen',1,'']]],
  ['invalidation_39',['Invalidation',['../dev.html#autotoc_md39',1,'']]],
  ['ir_40',['Matching IR',['../dev.html#autotoc_md42',1,'']]],
  ['is_20hard_20elsewhere_41',['Why this is hard elsewhere',['../phases.html#autotoc_md118',1,'']]],
  ['is_20inherently_20impure_42',['Hash-consing is inherently impure',['../md_docs_2why-cpp.html#autotoc_md181',1,'']]],
  ['is_20mimir_20implemented_20in_20c_43',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['is_20much_20worse_44',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md179',1,'']]],
  ['is_20worse_20not_20better_45',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md192',1,'']]],
  ['is_5fempty_46',['is_empty',['../ord.html#autotoc_md473',1,'']]],
  ['is_5ffinite_47',['is_finite',['../math.html#autotoc_md421',1,'']]],
  ['is_5floaded_48',['is_loaded',['../compile.html#autotoc_md307',1,'']]],
  ['is_5fsome_49',['is_some',['../option.html#autotoc_md461',1,'']]],
  ['is_5funique_50',['is_unique',['../vec.html#autotoc_md648',1,'']]],
  ['it_51',['Using it',['../playground.html#autotoc_md132',1,'']]],
  ['it_20defeats_20the_20purpose_52',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md188',1,'']]],
  ['item_20synchronization_53',['Work-Item Synchronization',['../gpu.html#autotoc_md384',1,'']]],
  ['iterating_20over_20the_20program_54',['Iterating over the Program',['../dev.html#autotoc_md57',1,'']]],
  ['iteration_55',['Iteration',['../mimir.html#mimir_iter',1,'Polymorphic Iteration'],['../phases.html#autotoc_md95',1,'Sparse Fixed-Point Iteration']]],
  ['iterations_56',['Reset Between Iterations',['../phases.html#autotoc_md96',1,'']]],
  ['iterators_57',['Iterators',['../vec.html#autotoc_md641',1,'']]]
];
