var searchData=
[
  ['o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md252',1,'']]],
  ['of_20mutables_1',['Handling of Mutables',['../phases.html#autotoc_md64',1,'']]],
  ['of_20nodes_2',['🌊 Sea of Nodes',['../index.html#autotoc_md95',1,'']]],
  ['of_20sigmas_3',['Field Names of Sigmas',['../langref.html#autotoc_md61',1,'']]],
  ['operations_4',['Operations',['../gpu.html#autotoc_md187',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md181',1,'Blocking Memory Operations'],['../core.html#autotoc_md146',1,'Integer Operations'],['../core.html#autotoc_md143',1,'Nat Operations'],['../math.html#autotoc_md203',1,'Numerical Operations'],['../affine.html#autotoc_md109',1,'Operations'],['../autodiff.html#autotoc_md115',1,'Operations'],['../demo.html#autotoc_md164',1,'Operations'],['../direct.html#autotoc_md167',1,'Operations'],['../gpu.html#autotoc_md176',1,'Operations'],['../matrix.html#autotoc_md223',1,'Operations'],['../option.html#autotoc_md269',1,'Operations'],['../tensor.html#autotoc_md324',1,'Operations'],['../tuple.html#autotoc_md336',1,'Operations'],['../core.html#autotoc_md160',1,'Other Operations'],['../math.html#autotoc_md214',1,'Other Operations']]],
  ['operations_5',['High-level matrix operations',['../matrix.html#autotoc_md232',1,'']]],
  ['operations_20related_20to_20longjmp_6',['Operations related to longjmp',['../clos.html#autotoc_md127',1,'']]],
  ['operations_20w_20o_20side_20effects_7',['Operations w/o Side Effects',['../mem.html#autotoc_md252',1,'']]],
  ['operations_20w_20side_20effects_8',['Operations w/ Side Effects',['../mem.html#autotoc_md243',1,'']]],
  ['opt_20plugin_9',['The opt Plugin',['../opt.html',1,'']]],
  ['option_10',['option.Option',['../option.html#autotoc_md265',1,'']]],
  ['option_20is_5fsome_11',['%option.is_some',['../option.html#autotoc_md270',1,'']]],
  ['option_20none_12',['%option.none',['../option.html#autotoc_md268',1,'']]],
  ['option_20option_13',['option.Option',['../option.html#autotoc_md265',1,'']]],
  ['option_20plugin_14',['The option Plugin',['../option.html',1,'']]],
  ['option_20some_15',['%option.some',['../option.html#autotoc_md267',1,'']]],
  ['option_20unwrap_5for_16',['%option.unwrap_or',['../option.html#autotoc_md272',1,'']]],
  ['option_20unwrap_5funsafe_17',['%option.unwrap_unsafe',['../option.html#autotoc_md271',1,'']]],
  ['optional_18',['📦 Install (Optional)',['../index.html#autotoc_md92',1,'']]],
  ['optional_20pre_20analysis_19',['Optional Pre-Analysis',['../phases.html#autotoc_md68',1,'']]],
  ['ord_20contains_20',['%ord.contains',['../ord.html#autotoc_md285',1,'']]],
  ['ord_20create_21',['%ord.create',['../ord.html#autotoc_md279',1,'']]],
  ['ord_20get_22',['%ord.get',['../ord.html#autotoc_md284',1,'']]],
  ['ord_20init_23',['%ord.init',['../ord.html#autotoc_md278',1,'']]],
  ['ord_20insert_24',['%ord.insert',['../ord.html#autotoc_md287',1,'']]],
  ['ord_20is_5fempty_25',['%ord.is_empty',['../ord.html#autotoc_md282',1,'']]],
  ['ord_20key_26',['%ord.Key',['../ord.html#autotoc_md275',1,'']]],
  ['ord_20map_27',['%ord.Set / %ord.Map',['../ord.html#autotoc_md276',1,'']]],
  ['ord_20plugin_28',['The ord Plugin',['../ord.html',1,'']]],
  ['ord_20set_20ord_20map_29',['%ord.Set / %ord.Map',['../ord.html#autotoc_md276',1,'']]],
  ['ord_20size_30',['%ord.size',['../ord.html#autotoc_md281',1,'']]],
  ['other_20operations_31',['Other Operations',['../core.html#autotoc_md160',1,'Other Operations'],['../math.html#autotoc_md214',1,'Other Operations']]],
  ['over_20the_20program_32',['Iterating over the Program',['../dev.html#autotoc_md40',1,'']]],
  ['overview_33',['Overview',['../phases.html#autotoc_md62',1,'']]]
];
