var searchData=
[
  ['c_20style_0',['C++ Style',['../coding.html#autotoc_md6',1,'']]],
  ['calling_20annexes_1',['Calling Annexes',['../dev.html#autotoc_md22',1,'']]],
  ['capacity_2',['Capacity',['../ord.html#autotoc_md337',1,'']]],
  ['casts_3',['Further Casts',['../dev.html#autotoc_md36',1,'']]],
  ['cat_4',['cat',['../tuple.html#autotoc_md412',1,'%tuple.cat'],['../vec.html#autotoc_md427',1,'%vec.cat']]],
  ['catching_20exceptions_5',['Catching Exceptions',['../coding.html#autotoc_md17',1,'']]],
  ['ceildiv_20floordiv_20mod_6',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md141',1,'']]],
  ['cheap_20approximation_7',['&lt;span class=&quot;tt&quot;&gt;Dep&lt;/span&gt;: A Cheap Approximation',['../dev.html#autotoc_md30',1,'']]],
  ['check_8',['%refly.check',['../refly.html#autotoc_md358',1,'']]],
  ['check_5fbot_9',['%refly.check_bot',['../refly.html#autotoc_md357',1,'']]],
  ['choosing_20the_20right_20base_20class_10',['Choosing the Right Base Class',['../phases.html#autotoc_md94',1,'']]],
  ['class_11',['Choosing the Right Base Class',['../phases.html#autotoc_md94',1,'']]],
  ['classical_20picture_12',['The classical picture',['../phases.html#autotoc_md89',1,'']]],
  ['cleanup_13',['Cleanup',['../phases.html#autotoc_md78',1,'']]],
  ['clos_20alloc_5fjmpbuf_14',['%clos.alloc_jmpbuf',['../clos.html#autotoc_md192',1,'']]],
  ['clos_20attr_15',['%clos.attr',['../clos.html#autotoc_md196',1,'']]],
  ['clos_20bufptr_16',['%clos.BufPtr',['../clos.html#autotoc_md191',1,'']]],
  ['clos_20longjmp_17',['%clos.longjmp',['../clos.html#autotoc_md194',1,'']]],
  ['clos_20plugin_18',['The clos Plugin',['../clos.html',1,'']]],
  ['clos_20setjmp_19',['%clos.setjmp',['../clos.html#autotoc_md193',1,'']]],
  ['closedmutphase_20',['ClosedMutPhase',['../phases.html#phases_closed_mut_phase',1,'']]],
  ['closure_20attribute_21',['Closure Attribute',['../clos.html#autotoc_md195',1,'']]],
  ['cls_22',['%regex.cls.*',['../regex.html#autotoc_md373',1,'']]],
  ['cmake_20style_23',['CMake Style',['../coding.html#autotoc_md9',1,'']]],
  ['cmp_24',['%math.cmp',['../math.html#autotoc_md292',1,'']]],
  ['code_25',['%refly.Code',['../refly.html#autotoc_md347',1,'']]],
  ['coding_20style_26',['Coding Style',['../coding.html#autotoc_md5',1,'Coding Style'],['../coding.html#autotoc_md11',1,'M⁠im Coding Style']]],
  ['command_20line_20arguments_27',['Command Line Arguments',['../compile.html#compile_cli_args',1,'Command-Line Arguments'],['../ll.html#ll_cli_args',1,'Command-Line Arguments'],['../ll_nvptx.html#ll_nvptx_cli_args',1,'Command-Line Arguments']]],
  ['command_20line_20reference_28',['Command-Line Reference',['../cli.html',1,'']]],
  ['comments_29',['Comments',['../langref.html#autotoc_md52',1,'']]],
  ['community_30',['💬 Community',['../index.html#autotoc_md123',1,'']]],
  ['compilation_20pipelines_20in_20m⁠im_31',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md97',1,'']]],
  ['compile_20aggr_32',['%compile.aggr',['../compile.html#autotoc_md204',1,'']]],
  ['compile_20cond_33',['%compile.cond',['../compile.html#autotoc_md203',1,'']]],
  ['compile_20is_5floaded_34',['%compile.is_loaded',['../compile.html#autotoc_md201',1,'']]],
  ['compile_20named_35',['%compile.named',['../compile.html#autotoc_md202',1,'']]],
  ['compile_20phase_36',['%compile.Phase',['../compile.html#autotoc_md199',1,'']]],
  ['compile_20phases_37',['%compile.phases',['../compile.html#autotoc_md206',1,'']]],
  ['compile_20plugin_38',['The compile Plugin',['../compile.html',1,'']]],
  ['concat_39',['concat',['../btensor.html#autotoc_md174',1,'%btensor.concat'],['../tensor.html#autotoc_md394',1,'%tensor.concat']]],
  ['cond_40',['%compile.cond',['../compile.html#autotoc_md203',1,'']]],
  ['conditional_20breakpoints_41',['Conditional Breakpoints',['../coding.html#autotoc_md16',1,'']]],
  ['conj_42',['%regex.conj',['../regex.html#autotoc_md366',1,'']]],
  ['const_5fidx_43',['%demo.const_idx',['../demo.html#autotoc_md237',1,'']]],
  ['constant_44',['constant',['../affine.html#autotoc_md138',1,'%affine.constant'],['../buffer.html#autotoc_md184',1,'%buffer.constant']]],
  ['constructors_45',['Constructors',['../compile.html#autotoc_md205',1,'Constructors'],['../option.html#autotoc_md323',1,'Constructors'],['../ord.html#autotoc_md334',1,'Constructors']]],
  ['contains_46',['contains',['../ord.html#autotoc_md342',1,'%ord.contains'],['../tuple.html#autotoc_md415',1,'%tuple.contains']]],
  ['context_47',['Context',['../gpu.html#autotoc_md245',1,'']]],
  ['continuations_48',['Functions and Continuations',['../langref.html#autotoc_md55',1,'']]],
  ['contributing_20debugging_49',['Contributing &amp;amp; Debugging',['../coding.html',1,'']]],
  ['contributor_20quick_20start_50',['Contributor Quick Start',['../coding.html#building',1,'']]],
  ['conv_51',['conv',['../core.html#autotoc_md225',1,'%core.conv'],['../cps.html#autotoc_md235',1,'%cps.conv'],['../math.html#autotoc_md294',1,'%math.conv'],['../tensor.html#autotoc_md395',1,'%tensor.conv']]],
  ['conversions_52',['Conversions',['../core.html#autotoc_md224',1,'']]],
  ['copy_53',['%buffer.copy',['../buffer.html#autotoc_md186',1,'']]],
  ['copy_5fto_5fdevice_20asyn_54',['%gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md262',1,'']]],
  ['copy_5fto_5fdevice_20block_55',['%gpu.copy_to_device(block)',['../gpu.html#autotoc_md256',1,'']]],
  ['copy_5fto_5fhost_20asyn_56',['%gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md263',1,'']]],
  ['copy_5fto_5fhost_20block_57',['%gpu.copy_to_host(block)',['../gpu.html#autotoc_md257',1,'']]],
  ['core_20abs_58',['%core.abs',['../core.html#autotoc_md223',1,'']]],
  ['core_20bit1_59',['core bit1',['../core.html#autotoc_md216',1,'%core.bit1'],['../todo.html#_todo000001',1,'%core.bit1']]],
  ['core_20bit2_60',['core bit2',['../core.html#autotoc_md217',1,'%core.bit2'],['../todo.html#_todo000002',1,'%core.bit2']]],
  ['core_20bitcast_61',['%core.bitcast',['../core.html#autotoc_md226',1,'']]],
  ['core_20conv_62',['%core.conv',['../core.html#autotoc_md225',1,'']]],
  ['core_20div_63',['%core.div',['../core.html#autotoc_md220',1,'']]],
  ['core_20extrema_64',['%core.extrema',['../core.html#autotoc_md222',1,'']]],
  ['core_20icmp_65',['%core.icmp',['../core.html#autotoc_md221',1,'']]],
  ['core_20idx_66',['%core.idx',['../core.html#autotoc_md214',1,'']]],
  ['core_20idx_5funsafe_67',['%core.idx_unsafe',['../core.html#autotoc_md215',1,'']]],
  ['core_20nat_68',['%core.nat',['../core.html#autotoc_md210',1,'']]],
  ['core_20ncmp_69',['%core.ncmp',['../core.html#autotoc_md211',1,'']]],
  ['core_20pe_70',['%core.pe',['../core.html#autotoc_md229',1,'']]],
  ['core_20plugin_71',['The core Plugin',['../core.html',1,'']]],
  ['core_20select_72',['%core.select',['../core.html#autotoc_md230',1,'']]],
  ['core_20shr_73',['%core.shr',['../core.html#autotoc_md218',1,'']]],
  ['core_20trait_74',['%core.trait',['../core.html#autotoc_md228',1,'']]],
  ['core_20wrap_75',['%core.wrap',['../core.html#autotoc_md219',1,'']]],
  ['core_5ficmp_5fxygle_76',['%autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md162',1,'']]],
  ['core_5fwrap_5fadd_77',['%autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md163',1,'']]],
  ['core_5fwrap_5fmul_78',['%autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md164',1,'']]],
  ['coverage_79',['Coverage',['../python.html#autotoc_md111',1,'']]],
  ['cps_80',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['cps_20conv_81',['%cps.conv',['../cps.html#autotoc_md235',1,'']]],
  ['cps_20cps2ds_82',['%cps.cps2ds',['../cps.html#autotoc_md233',1,'']]],
  ['cps_20plugin_83',['The CPS Plugin',['../cps.html',1,'']]],
  ['cps2ds_84',['%cps.cps2ds',['../cps.html#autotoc_md233',1,'']]],
  ['create_85',['%ord.create',['../ord.html#autotoc_md336',1,'']]],
  ['create_20a_20new_20in_20tree_20plugin_86',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md103',1,'']]],
  ['create_20a_20third_20party_20plugin_87',['Create a Third-Party Plugin',['../plugins.html#autotoc_md104',1,'']]]
];
