var searchData=
[
  ['o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md396',1,'']]],
  ['of_20mim_1',['✨ A Taste of Mim',['../index.html#autotoc_md129',1,'']]],
  ['of_20mimir_2',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['of_20mutables_3',['Handling of Mutables',['../phases.html#autotoc_md84',1,'']]],
  ['of_20nodes_4',['🌊 Sea of Nodes',['../index.html#autotoc_md135',1,'']]],
  ['of_20sigmas_5',['Field Names of Sigmas',['../langref.html#field',1,'']]],
  ['of_20the_20node_6',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['on_7',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md150',1,'']]],
  ['one_20machine_20word_8',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md152',1,'']]],
  ['op_20add_20sub_9',['op(add,sub)',['../affine.html#autotoc_md177',1,'']]],
  ['op_20neg_10',['op(neg)',['../affine.html#autotoc_md178',1,'']]],
  ['operations_11',['Operations',['../affine.html#autotoc_md174',1,'Affine Index Operations'],['../gpu.html#autotoc_md330',1,'Blocking / Async Memory Operations'],['../gpu.html#autotoc_md336',1,'Buffer Operations'],['../tensor.html#autotoc_md502',1,'Element-wise Operations'],['../core.html#autotoc_md286',1,'Integer Operations'],['../core.html#autotoc_md283',1,'Nat Operations'],['../math.html#autotoc_md364',1,'Numerical Operations'],['../affine.html#autotoc_md172',1,'Operations'],['../autodiff.html#autotoc_md190',1,'Operations'],['../buffer.html#autotoc_md238',1,'Operations'],['../clos.html#autotoc_md249',1,'Operations'],['../compile.html#autotoc_md265',1,'Operations'],['../cps.html#autotoc_md308',1,'Operations'],['../demo.html#autotoc_md312',1,'Operations'],['../gpu.html#autotoc_md320',1,'Operations'],['../option.html#autotoc_md417',1,'Operations'],['../tuple.html#autotoc_md586',1,'Operations'],['../core.html#autotoc_md301',1,'Other Operations'],['../math.html#autotoc_md375',1,'Other Operations'],['../btensor.html#autotoc_md213',1,'Shape Operations'],['../tensor.html#autotoc_md487',1,'Shape Operations']]],
  ['operations_20w_20o_20side_20effects_12',['Operations w/o Side Effects',['../mem.html#autotoc_md396',1,'']]],
  ['operations_20w_20side_20effects_13',['Operations w/ Side Effects',['../mem.html#autotoc_md386',1,'']]],
  ['operators_14',['Operators',['../langref.html#infix',1,'Infix Operators'],['../core.html#autotoc_md306',1,'Operators'],['../math.html#autotoc_md382',1,'Operators']]],
  ['opt_15',['Opt',['../option.html#autotoc_md412',1,'']]],
  ['opt_20plugin_16',['The opt Plugin',['../opt.html',1,'']]],
  ['optimization_17',['Optimization',['../cli.html#autotoc_md6',1,'']]],
  ['option_20plugin_18',['The option Plugin',['../option.html',1,'']]],
  ['optional_19',['📦 Install (Optional)',['../index.html#autotoc_md132',1,'']]],
  ['optional_20pre_20analysis_20',['Optional Pre-Analysis',['../phases.html#autotoc_md88',1,'']]],
  ['options_21',['Options',['../cli.html#autotoc_md7',1,'Developer Options'],['../cli.html#autotoc_md1',1,'Options']]],
  ['ord_20plugin_22',['The ord Plugin',['../ord.html',1,'']]],
  ['other_20definitions_23',['Other Definitions',['../mimir.html#autotoc_md80',1,'']]],
  ['other_20operations_24',['Other Operations',['../core.html#autotoc_md301',1,'Other Operations'],['../math.html#autotoc_md375',1,'Other Operations']]],
  ['out_20of_20the_20node_25',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['output_26',['Output',['../cli.html#autotoc_md3',1,'DOT Output'],['../cli.html#autotoc_md2',1,'Output']]],
  ['over_20the_20program_27',['Iterating over the Program',['../dev.html#autotoc_md57',1,'']]],
  ['overview_28',['Overview',['../phases.html#autotoc_md81',1,'']]]
];
