var searchData=
[
  ['m⁠im_0',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md84',1,'']]],
  ['m⁠im_20coding_20style_1',['M⁠im Coding Style',['../coding.html#autotoc_md10',1,'']]],
  ['m_2',['%mem.M',['../mem.html#memM',1,'']]],
  ['malloc_3',['%mem.malloc',['../mem.html#autotoc_md278',1,'']]],
  ['manipulate_4',['Manipulate',['../refly.html#autotoc_md330',1,'']]],
  ['map_5',['%ord.Set / %ord.Map',['../ord.html#autotoc_md305',1,'']]],
  ['map_6',['map',['../affine.html#autotoc_md129',1,'%affine.map'],['../tensor.html#autotoc_md366',1,'%tensor.map']]],
  ['map_5freduce_7',['%tensor.map_reduce',['../tensor.html#autotoc_md357',1,'']]],
  ['map_5freduce_5faff_8',['%tensor.map_reduce_aff',['../tensor.html#autotoc_md359',1,'']]],
  ['map_5freduce_5fds_9',['%tensor.map_reduce_ds',['../tensor.html#autotoc_md358',1,'']]],
  ['markdown_20style_10',['Markdown Style',['../coding.html#autotoc_md9',1,'']]],
  ['mat_11',['%matrix.Mat',['../matrix.html#autotoc_md251',1,'']]],
  ['matching_12',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md50',1,'']]],
  ['matching_20axioms_13',['Matching Axioms',['../dev.html#cast_axm',1,'']]],
  ['matching_20ir_14',['Matching IR',['../dev.html#autotoc_md25',1,'']]],
  ['matching_20literals_15',['Matching Literals',['../dev.html#cast_lit',1,'']]],
  ['math_20abs_16',['%math.abs',['../math.html#autotoc_md240',1,'']]],
  ['math_20arith_17',['%math.arith',['../math.html#autotoc_md232',1,'']]],
  ['math_20cmp_18',['%math.cmp',['../math.html#autotoc_md243',1,'']]],
  ['math_20conv_19',['%math.conv',['../math.html#autotoc_md245',1,'']]],
  ['math_20er_20',['%math.er',['../math.html#autotoc_md238',1,'']]],
  ['math_20exp_21',['%math.exp',['../math.html#autotoc_md237',1,'']]],
  ['math_20extrema_22',['%math.extrema',['../math.html#autotoc_md233',1,'']]],
  ['math_20f_23',['%math.F',['../math.html#autotoc_md230',1,'']]],
  ['math_20gamma_24',['%math.gamma',['../math.html#autotoc_md239',1,'']]],
  ['math_20is_5ffinite_25',['%math.is_finite',['../math.html#autotoc_md244',1,'']]],
  ['math_20plugin_26',['The math Plugin',['../math.html',1,'']]],
  ['math_20pow_27',['%math.pow',['../math.html#autotoc_md235',1,'']]],
  ['math_20round_28',['%math.round',['../math.html#autotoc_md241',1,'']]],
  ['math_20rrt_29',['%math.rrt',['../math.html#autotoc_md248',1,'']]],
  ['math_20rt_30',['%math.rt',['../math.html#autotoc_md236',1,'']]],
  ['math_20sgn_31',['%math.sgn',['../math.html#autotoc_md247',1,'']]],
  ['math_20slf_32',['%math.slf',['../math.html#autotoc_md246',1,'']]],
  ['math_20tri_33',['%math.tri',['../math.html#autotoc_md234',1,'']]],
  ['matrix_20const_34',['%matrix.const',['../matrix.html#autotoc_md255',1,'']]],
  ['matrix_20init_35',['%matrix.init',['../matrix.html#autotoc_md260',1,'']]],
  ['matrix_20insert_36',['%matrix.insert',['../matrix.html#autotoc_md258',1,'']]],
  ['matrix_20mat_37',['%matrix.Mat',['../matrix.html#autotoc_md251',1,'']]],
  ['matrix_20operations_38',['High-level matrix operations',['../matrix.html#autotoc_md261',1,'']]],
  ['matrix_20plugin_39',['The matrix Plugin',['../matrix.html',1,'']]],
  ['matrix_20read_40',['%matrix.read',['../matrix.html#autotoc_md256',1,'']]],
  ['matrix_20shape_41',['%matrix.shape',['../matrix.html#autotoc_md253',1,'']]],
  ['mem_20alloc_42',['%mem.alloc',['../mem.html#autotoc_md276',1,'']]],
  ['mem_20free_43',['%mem.free',['../mem.html#autotoc_md279',1,'']]],
  ['mem_20lea_44',['%mem.lea',['../mem.html#autotoc_md282',1,'']]],
  ['mem_20load_45',['%mem.load',['../mem.html#autotoc_md273',1,'']]],
  ['mem_20m_46',['%mem.M',['../mem.html#memM',1,'']]],
  ['mem_20malloc_47',['%mem.malloc',['../mem.html#autotoc_md278',1,'']]],
  ['mem_20mslot_48',['%mem.mslot',['../mem.html#autotoc_md280',1,'']]],
  ['mem_20plugin_49',['The mem Plugin',['../mem.html',1,'']]],
  ['mem_20ptr_50',['%mem.Ptr',['../mem.html#autotoc_md271',1,'']]],
  ['mem_20remem_51',['%mem.remem',['../mem.html#autotoc_md275',1,'']]],
  ['mem_20reshape_52',['mem.reshape',['../mem.html#autotoc_md287',1,'']]],
  ['mem_20slot_53',['%mem.slot',['../mem.html#autotoc_md277',1,'']]],
  ['mem_20store_54',['%mem.store',['../mem.html#autotoc_md274',1,'']]],
  ['memory_20operations_55',['Memory Operations',['../gpu.html#autotoc_md213',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md207',1,'Blocking Memory Operations']]],
  ['memory_20types_56',['Memory Types',['../gpu.html#autotoc_md195',1,'']]],
  ['meta_57',['Meta',['../regex.html#autotoc_md337',1,'']]],
  ['metadata_58',['Preserving Metadata',['../rewriting.html#autotoc_md114',1,'']]],
  ['mim_59',['Mim',['../index.html#autotoc_md100',1,'✨ A Taste of Mim'],['../index.html#autotoc_md108',1,'🐉 Naming: MimIR vs. Mim']]],
  ['mim_20language_20reference_60',['Mim Language Reference',['../langref.html',1,'']]],
  ['mimir_61',['MimIR',['../index.html#autotoc_md101',1,'💡 Why MimIR?'],['../mimir.html',1,'A Tour of MimIR'],['../index.html',1,'MimIR']]],
  ['mimir_20vs_20mim_62',['🐉 Naming: MimIR vs. Mim',['../index.html#autotoc_md108',1,'']]],
  ['minimal_20examples_63',['Minimal Examples',['../phases.html#autotoc_md83',1,'']]],
  ['mod_64',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md127',1,'']]],
  ['mode_65',['Mode',['../core.html#autotoc_md169',1,'']]],
  ['model_66',['Execution Model',['../phases.html#autotoc_md70',1,'']]],
  ['modifiers_67',['Modifiers',['../ord.html#autotoc_md315',1,'Modifiers'],['../vec.html#autotoc_md386',1,'Modifiers']]],
  ['module_68',['Module',['../langref.html#module',1,'']]],
  ['mslot_69',['%mem.mslot',['../mem.html#autotoc_md280',1,'']]],
  ['mul_70',['mul',['../affine.html#autotoc_md128',1,'%affine.op(mul)'],['../autodiff.html#autotoc_md145',1,'%core.wrap.mul']]],
  ['mul_20ceildiv_20floordiv_20mod_71',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md127',1,'']]],
  ['mutable_20rewrites_72',['Mutable Rewrites',['../rewriting.html#autotoc_md113',1,'']]],
  ['mutables_73',['Mutables',['../dev.html#autotoc_md28',1,'Downcast to Mutables'],['../phases.html#autotoc_md67',1,'Handling of Mutables'],['../dev.html#mut',1,'Immutables vs. Mutables'],['../dev.html#autotoc_md21',1,'Mutables']]]
];
