var searchData=
[
  ['ballpark_20estimates_0',['Ballpark estimates',['../md_docs_2why-cpp.html#autotoc_md165',1,'']]],
  ['base_20class_1',['Choosing the Right Base Class',['../phases.html#autotoc_md117',1,'']]],
  ['basic_20forms_2',['Literals and Basic Forms',['../langref.html#lit',1,'']]],
  ['basics_3',['Basics',['../dev.html#autotoc_md31',1,'']]],
  ['become_20map_20lookups_4',['Pointers become map lookups',['../md_docs_2why-cpp.html#autotoc_md173',1,'']]],
  ['beta_5fred_5',['beta_red',['../compile.html#autotoc_md289',1,'']]],
  ['better_6',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['between_20iterations_7',['Reset Between Iterations',['../phases.html#autotoc_md93',1,'']]],
  ['bid_5fmap_8',['bid_map',['../tensor.html#autotoc_md564',1,'']]],
  ['binary_9',['binary',['../tensor.html#autotoc_md519',1,'']]],
  ['binary_5fimpl_10',['binary_impl',['../tensor.html#autotoc_md591',1,'']]],
  ['bindable_20types_11',['Bindable Types',['../python.html#python_bindable',1,'']]],
  ['binders_12',['Binders',['../dev.html#autotoc_md35',1,'Binders'],['../mimir.html#mimir_scopeless',1,'Scopeless Binders']]],
  ['bindings_13',['Bindings',['../python.html#python_extending',1,'Extending the Bindings'],['../python.html',1,'Python Bindings']]],
  ['bit1_14',['bit1',['../core.html#autotoc_md307',1,'']]],
  ['bit2_15',['bit2',['../core.html#autotoc_md308',1,'']]],
  ['bitcast_16',['bitcast',['../core.html#autotoc_md317',1,'']]],
  ['block_20alloc_20asyn_17',['alloc(block) / alloc(asyn)',['../gpu.html#autotoc_md348',1,'']]],
  ['block_20alloc_5fcopy_20asyn_18',['alloc_copy(block) / alloc_copy(asyn)',['../gpu.html#autotoc_md352',1,'']]],
  ['block_20copy_5fto_5fdevice_20asyn_19',['copy_to_device(block) / copy_to_device(asyn)',['../gpu.html#autotoc_md350',1,'']]],
  ['block_20copy_5fto_5fhost_20asyn_20',['copy_to_host(block) / copy_to_host(asyn)',['../gpu.html#autotoc_md351',1,'']]],
  ['block_20free_20asyn_21',['free(block) / free(asyn)',['../gpu.html#autotoc_md349',1,'']]],
  ['blocking_20async_20memory_20operations_22',['Blocking / Async Memory Operations',['../gpu.html#autotoc_md347',1,'']]],
  ['blocks_23',['Local Declaration Blocks',['../langref.html#autotoc_md69',1,'']]],
  ['bmm_24',['bmm',['../tensor.html#autotoc_md524',1,'']]],
  ['bmm_5fimpl_25',['bmm_impl',['../tensor.html#autotoc_md583',1,'']]],
  ['bootstrapping_26',['Bootstrapping',['../phases.html#autotoc_md97',1,'']]],
  ['branch_5fclos_27',['branch_clos',['../clos.html#autotoc_md276',1,'']]],
  ['branch_5fnormalize_28',['branch_normalize',['../compile.html#autotoc_md290',1,'']]],
  ['breakpoints_29',['Breakpoints',['../coding.html#autotoc_md27',1,'Conditional Breakpoints'],['../coding.html#autotoc_md30',1,'Triggering Breakpoints']]],
  ['broadcast_30',['broadcast',['../btensor.html#autotoc_md231',1,'broadcast'],['../tensor.html#autotoc_md504',1,'broadcast']]],
  ['broadcast_5fin_5fdim_31',['broadcast_in_dim',['../tensor.html#autotoc_md505',1,'']]],
  ['broadcast_5fin_5fdim_5fimpl_32',['broadcast_in_dim_impl',['../tensor.html#autotoc_md565',1,'']]],
  ['btensor_20plugin_33',['The btensor Plugin',['../btensor.html',1,'']]],
  ['btensor_5fcopy_34',['btensor_copy',['../btensor.html#autotoc_md234',1,'']]],
  ['buf_35',['Buf',['../buffer.html#autotoc_md254',1,'']]],
  ['buf_36',['buf',['../tensor.html#autotoc_md493',1,'']]],
  ['buf_5falloc_5fcopy_37',['buf_alloc_copy',['../gpu.html#autotoc_md354',1,'']]],
  ['buf_5fcopy_5fto_5fhost_38',['buf_copy_to_host',['../gpu.html#autotoc_md355',1,'']]],
  ['buffer_20operations_39',['Buffer Operations',['../gpu.html#autotoc_md353',1,'']]],
  ['buffer_20plugin_40',['The buffer Plugin',['../buffer.html',1,'']]],
  ['bufptr_41',['BufPtr',['../clos.html#autotoc_md267',1,'']]],
  ['build_42',['Configure and build',['../playground.html#autotoc_md125',1,'']]],
  ['building_43',['Building',['../playground.html#autotoc_md122',1,'']]],
  ['builds_44',['Standalone Third-Party Builds',['../plugins.html#autotoc_md138',1,'']]],
  ['built_20ins_45',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['builtin_20types_46',['Kinds and Builtin Types',['../langref.html#autotoc_md66',1,'']]]
];
