var searchData=
[
  ['base_20class_0',['Choosing the Right Base Class',['../phases.html#autotoc_md94',1,'']]],
  ['basic_20forms_1',['Literals and Basic Forms',['../langref.html#autotoc_md54',1,'']]],
  ['basics_2',['Basics',['../dev.html#autotoc_md20',1,'']]],
  ['between_20iterations_3',['Reset Between Iterations',['../phases.html#autotoc_md77',1,'']]],
  ['binary_4',['%tensor.binary',['../tensor.html#autotoc_md412',1,'']]],
  ['bindable_20types_5',['Bindable Types',['../python.html#python_bindable',1,'']]],
  ['binders_6',['Binders',['../dev.html#autotoc_md24',1,'Binders'],['../mimir.html#mimir_scopeless',1,'Scopeless Binders']]],
  ['bindings_7',['Bindings',['../python.html#python_extending',1,'Extending the Bindings'],['../python.html',1,'Python Bindings']]],
  ['bit1_8',['bit1',['../core.html#autotoc_md204',1,'%core.bit1'],['../todo.html#_todo000001',1,'%core.bit1']]],
  ['bit2_9',['bit2',['../core.html#autotoc_md205',1,'%core.bit2'],['../todo.html#_todo000002',1,'%core.bit2']]],
  ['bitcast_10',['%core.bitcast',['../core.html#autotoc_md214',1,'']]],
  ['block_11',['block',['../gpu.html#autotoc_md242',1,'%gpu.alloc(block)'],['../gpu.html#autotoc_md246',1,'%gpu.alloc_copy(block)'],['../gpu.html#autotoc_md244',1,'%gpu.copy_to_device(block)'],['../gpu.html#autotoc_md245',1,'%gpu.copy_to_host(block)'],['../gpu.html#autotoc_md243',1,'%gpu.free(block)']]],
  ['blocking_20memory_20operations_12',['Blocking Memory Operations',['../gpu.html#autotoc_md241',1,'']]],
  ['blocks_13',['Local Declaration Blocks',['../langref.html#autotoc_md57',1,'']]],
  ['bmm_14',['%tensor.bmm',['../tensor.html#autotoc_md405',1,'']]],
  ['bootstrapping_15',['Bootstrapping',['../phases.html#autotoc_md82',1,'']]],
  ['breakpoints_16',['Breakpoints',['../coding.html#autotoc_md16',1,'Conditional Breakpoints'],['../coding.html#autotoc_md19',1,'Triggering Breakpoints']]],
  ['broadcast_17',['broadcast',['../matrix.html#autotoc_md294',1,'%matrix.broadcast'],['../tensor.html#autotoc_md408',1,'%tensor.broadcast']]],
  ['broadcast_5fin_5fdim_18',['broadcast_in_dim',['../tensor.html#autotoc_md409',1,'%tensor.broadcast_in_dim'],['../todo.html#_todo000003',1,'%tensor.broadcast_in_dim']]],
  ['buf_19',['%buffer.Buf',['../buffer.html#autotoc_md166',1,'']]],
  ['buffer_20alloc_20',['%buffer.alloc',['../buffer.html#autotoc_md168',1,'']]],
  ['buffer_20buf_21',['%buffer.Buf',['../buffer.html#autotoc_md166',1,'']]],
  ['buffer_20constant_22',['%buffer.constant',['../buffer.html#autotoc_md172',1,'']]],
  ['buffer_20copy_23',['%buffer.copy',['../buffer.html#autotoc_md174',1,'']]],
  ['buffer_20init_24',['%buffer.init',['../buffer.html#autotoc_md171',1,'']]],
  ['buffer_20lower_5fptr_25',['%buffer.lower_ptr',['../buffer.html#autotoc_md176',1,'']]],
  ['buffer_20plugin_26',['The buffer Plugin',['../buffer.html',1,'']]],
  ['buffer_20read_27',['%buffer.read',['../buffer.html#autotoc_md169',1,'']]],
  ['buffer_20shape_28',['%buffer.shape',['../buffer.html#autotoc_md173',1,'']]],
  ['buffer_20write_29',['%buffer.write',['../buffer.html#autotoc_md170',1,'']]],
  ['bufptr_30',['%clos.BufPtr',['../clos.html#autotoc_md179',1,'']]],
  ['builds_31',['Standalone Third-Party Builds',['../plugins.html#autotoc_md107',1,'']]],
  ['built_20ins_32',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['builtin_20types_33',['Kinds and Builtin Types',['../langref.html#autotoc_md53',1,'']]]
];
