var searchData=
[
  ['a_20four_20way_20sum_20type_20in_20one_20machine_20word_0',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['a_20new_20in_20tree_20plugin_1',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md111',1,'']]],
  ['a_20taste_20of_20mim_2',['✨ A Taste of Mim',['../index.html#autotoc_md122',1,'']]],
  ['a_20third_20party_20plugin_3',['Create a Third-Party Plugin',['../plugins.html#autotoc_md112',1,'']]],
  ['a_20tour_20of_20mimir_4',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['abs_5',['abs',['../core.html#autotoc_md250',1,'%core.abs'],['../math.html#autotoc_md316',1,'%math.abs']]],
  ['absl_3a_3aflat_5fhash_5f_6',['&lt;span class=&quot;tt&quot;&gt;absl::flat_hash_*&lt;/span&gt;',['../md_docs_2why-cpp.html#autotoc_md144',1,'']]],
  ['actually_20relies_20on_7',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md143',1,'']]],
  ['ad_8',['%autodiff.AD',['../autodiff.html#autotoc_md181',1,'']]],
  ['ad_9',['%autodiff.ad',['../autodiff.html#autotoc_md182',1,'']]],
  ['add_10',['%autodiff.add',['../autodiff.html#autotoc_md184',1,'']]],
  ['add_20sub_11',['%affine.op(add,sub)',['../affine.html#autotoc_md166',1,'']]],
  ['add_5fmim_5fplugin_12',['add_mim_plugin',['../add_mim_plugin_cmake.html',1,'']]],
  ['add_5fmim_5fruntime_13',['add_mim_runtime',['../add_mim_runtime_cmake.html',1,'']]],
  ['address_20spaces_14',['Address Spaces',['../gpu.html#autotoc_md267',1,'']]],
  ['affine_20constant_15',['%affine.constant',['../affine.html#autotoc_md165',1,'']]],
  ['affine_20delinearize_16',['%affine.delinearize',['../affine.html#autotoc_md173',1,'']]],
  ['affine_20for_17',['%affine.For',['../affine.html#autotoc_md162',1,'']]],
  ['affine_20id_18',['%affine.id',['../affine.html#autotoc_md171',1,'']]],
  ['affine_20index_19',['%affine.index',['../affine.html#autotoc_md164',1,'']]],
  ['affine_20index_20operations_20',['Affine Index Operations',['../affine.html#autotoc_md163',1,'']]],
  ['affine_20linearize_21',['%affine.linearize',['../affine.html#autotoc_md172',1,'']]],
  ['affine_20lower_5ffor_22',['%affine.lower_for',['../affine.html#autotoc_md175',1,'']]],
  ['affine_20lower_5findex_23',['%affine.lower_index',['../affine.html#autotoc_md176',1,'']]],
  ['affine_20map_24',['%affine.map',['../affine.html#autotoc_md170',1,'']]],
  ['affine_20op_20add_20sub_25',['%affine.op(add,sub)',['../affine.html#autotoc_md166',1,'']]],
  ['affine_20op_20mul_26',['%affine.op.mul',['../affine.html#autotoc_md169',1,'']]],
  ['affine_20op_20neg_27',['%affine.op(neg)',['../affine.html#autotoc_md167',1,'']]],
  ['affine_20plugin_28',['The affine Plugin',['../affine.html',1,'']]],
  ['affine_20semiop_20mul_20ceildiv_20floordiv_20mod_29',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md168',1,'']]],
  ['aggr_30',['%compile.aggr',['../compile.html#autotoc_md231',1,'']]],
  ['all_31',['Why the guard exists at all',['../phases.html#autotoc_md96',1,'']]],
  ['alloc_32',['alloc',['../buffer.html#autotoc_md207',1,'%buffer.alloc'],['../mem.html#autotoc_md333',1,'%mem.alloc']]],
  ['alloc_20asyn_33',['%gpu.alloc(asyn)',['../gpu.html#autotoc_md287',1,'']]],
  ['alloc_20block_34',['%gpu.alloc(block)',['../gpu.html#autotoc_md281',1,'']]],
  ['alloc_5fcopy_20asyn_35',['%gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md291',1,'']]],
  ['alloc_5fcopy_20block_36',['%gpu.alloc_copy(block)',['../gpu.html#autotoc_md285',1,'']]],
  ['alloc_5fjmpbuf_37',['%clos.alloc_jmpbuf',['../clos.html#autotoc_md219',1,'']]],
  ['an_20existing_20in_20tree_20plugin_38',['Extract an Existing In-Tree Plugin',['../plugins.html#autotoc_md114',1,'']]],
  ['analysis_39',['Analysis',['../phases.html#phases_analysis',1,'Analysis'],['../phases.html#autotoc_md95',1,'Analysis'],['../phases.html#autotoc_md80',1,'Optional Pre-Analysis']]],
  ['analysis_20results_40',['Analysis Results',['../phases.html#autotoc_md81',1,'']]],
  ['and_20basic_20forms_41',['Literals and Basic Forms',['../langref.html#autotoc_md54',1,'']]],
  ['and_20builtin_20types_42',['Kinds and Builtin Types',['../langref.html#autotoc_md53',1,'']]],
  ['and_20continuations_43',['Functions and Continuations',['../langref.html#autotoc_md55',1,'']]],
  ['and_20how_20defs_20are_20placed_20in_20them_44',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['and_20types_45',['Summary: Functions and Types',['../langref.html#autotoc_md60',1,'']]],
  ['and_20why_20it_20defeats_20the_20purpose_46',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['annex_47',['Annex',['../langref.html#autotoc_md67',1,'']]],
  ['annexes_48',['Annexes',['../mimir.html#autotoc_md70',1,'Annexes'],['../dev.html#autotoc_md22',1,'Calling Annexes']]],
  ['any_49',['%regex.any',['../regex.html#autotoc_md399',1,'']]],
  ['api_50',['Lattice API',['../phases.html#autotoc_md75',1,'']]],
  ['append_20tuple_20prepend_51',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md438',1,'']]],
  ['applications_52',['Applications',['../langref.html#autotoc_md63',1,'']]],
  ['apply_20here_53',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['are_20placed_20in_20them_54',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['are_20values_55',['Types Are Values',['../mimir.html#mimir_dep',1,'']]],
  ['arena_20rollback_56',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md148',1,'']]],
  ['arenas_20and_20how_20defs_20are_20placed_20in_20them_57',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['argument_58',['The empirical argument',['../md_docs_2why-cpp.html#autotoc_md154',1,'']]],
  ['arguments_59',['Arguments',['../compile.html#compile_cli_args',1,'Command-Line Arguments'],['../ll.html#ll_cli_args',1,'Command-Line Arguments'],['../ll_nvptx.html#ll_nvptx_cli_args',1,'Command-Line Arguments'],['../cli.html#autotoc_md1',1,'Known Arguments']]],
  ['arguments_20to_20plugins_60',['Passing Arguments to Plugins',['../cli.html#clipluginargs',1,'']]],
  ['arith_61',['%math.arith',['../math.html#autotoc_md308',1,'']]],
  ['arity_62',['Arity',['../dev.html#autotoc_md41',1,'']]],
  ['asyn_63',['asyn',['../gpu.html#autotoc_md287',1,'%gpu.alloc(asyn)'],['../gpu.html#autotoc_md291',1,'%gpu.alloc_copy(asyn)'],['../gpu.html#autotoc_md289',1,'%gpu.copy_to_device(asyn)'],['../gpu.html#autotoc_md290',1,'%gpu.copy_to_host(asyn)'],['../gpu.html#autotoc_md288',1,'%gpu.free(asyn)']]],
  ['async_20memory_20operations_64',['Async Memory Operations',['../gpu.html#autotoc_md286',1,'']]],
  ['at_20all_65',['Why the guard exists at all',['../phases.html#autotoc_md96',1,'']]],
  ['attr_66',['%clos.attr',['../clos.html#autotoc_md223',1,'']]],
  ['attribute_67',['Closure Attribute',['../clos.html#autotoc_md222',1,'']]],
  ['autodiff_20ad_68',['%autodiff.AD',['../autodiff.html#autotoc_md181',1,'']]],
  ['autodiff_20ad_69',['%autodiff.ad',['../autodiff.html#autotoc_md182',1,'']]],
  ['autodiff_20add_70',['%autodiff.add',['../autodiff.html#autotoc_md184',1,'']]],
  ['autodiff_20diff_71',['%autodiff.diff',['../autodiff.html#autotoc_md188',1,'']]],
  ['autodiff_20diff_20core_5ficmp_5fxygle_72',['%autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md189',1,'']]],
  ['autodiff_20diff_20core_5fwrap_5fadd_73',['%autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md190',1,'']]],
  ['autodiff_20diff_20core_5fwrap_5fmul_74',['%autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md191',1,'']]],
  ['autodiff_20sum_75',['%autodiff.sum',['../autodiff.html#autotoc_md185',1,'']]],
  ['autodiff_20tangent_76',['%autodiff.Tangent',['../autodiff.html#autotoc_md179',1,'']]],
  ['autodiff_20zero_77',['%autodiff.zero',['../autodiff.html#autotoc_md183',1,'']]],
  ['automatic_20differentiation_20plugin_78',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['axioms_79',['Axioms',['../mimir.html#autotoc_md71',1,'Axioms'],['../dev.html#cast_axm',1,'Matching Axioms']]]
];
