var searchData=
[
  ['gamma_0',['%math.gamma',['../math.html#autotoc_md339',1,'']]],
  ['gdb_1',['Valgrind &amp;amp; GDB',['../coding.html#autotoc_md29',1,'']]],
  ['general_20downcast_2',['General Downcast',['../dev.html#autotoc_md43',1,'']]],
  ['generated_20header_3',['Generated Header',['../plugins.html#plugin_h',1,'']]],
  ['generated_20interfaces_4',['Generated Interfaces',['../plugins.html#plugin_codegen',1,'']]],
  ['generated_20markdown_20page_5',['Generated Markdown Page',['../plugins.html#autotoc_md120',1,'']]],
  ['generated_20python_20module_6',['Generated Python Module',['../plugins.html#autotoc_md119',1,'']]],
  ['genuinely_20wins_7',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md171',1,'']]],
  ['get_8',['get',['../ord.html#autotoc_md393',1,'%ord.get'],['../tensor.html#autotoc_md434',1,'%tensor.get']]],
  ['gid_9',['%refly.gid',['../refly.html#autotoc_md405',1,'']]],
  ['global_10',['Local vs. Global',['../dev.html#autotoc_md38',1,'']]],
  ['gpu_20alloc_20asyn_11',['%gpu.alloc(asyn)',['../gpu.html#autotoc_md309',1,'']]],
  ['gpu_20alloc_20block_12',['%gpu.alloc(block)',['../gpu.html#autotoc_md300',1,'']]],
  ['gpu_20alloc_5fcopy_20asyn_13',['%gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md313',1,'']]],
  ['gpu_20alloc_5fcopy_20block_14',['%gpu.alloc_copy(block)',['../gpu.html#autotoc_md304',1,'']]],
  ['gpu_20auto_5fdeinit_15',['%gpu.auto_init / %gpu.auto_deinit',['../gpu.html#autotoc_md293',1,'']]],
  ['gpu_20auto_5finit_20gpu_20auto_5fdeinit_16',['%gpu.auto_init / %gpu.auto_deinit',['../gpu.html#autotoc_md293',1,'']]],
  ['gpu_20buf_5falloc_5fcopy_17',['%gpu.buf_alloc_copy',['../gpu.html#autotoc_md306',1,'']]],
  ['gpu_20buf_5fcopy_5fto_5fhost_18',['%gpu.buf_copy_to_host',['../gpu.html#autotoc_md307',1,'']]],
  ['gpu_20copy_5fto_5fdevice_20asyn_19',['%gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md311',1,'']]],
  ['gpu_20copy_5fto_5fdevice_20block_20',['%gpu.copy_to_device(block)',['../gpu.html#autotoc_md302',1,'']]],
  ['gpu_20copy_5fto_5fhost_20asyn_21',['%gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md312',1,'']]],
  ['gpu_20copy_5fto_5fhost_20block_22',['%gpu.copy_to_host(block)',['../gpu.html#autotoc_md303',1,'']]],
  ['gpu_20deinit_23',['%gpu.deinit',['../gpu.html#autotoc_md292',1,'']]],
  ['gpu_20free_20asyn_24',['%gpu.free(asyn)',['../gpu.html#autotoc_md310',1,'']]],
  ['gpu_20free_20block_25',['%gpu.free(block)',['../gpu.html#autotoc_md301',1,'']]],
  ['gpu_20init_26',['%gpu.init',['../gpu.html#autotoc_md291',1,'']]],
  ['gpu_20launch_27',['%gpu.launch',['../gpu.html#autotoc_md315',1,'']]],
  ['gpu_20plugin_28',['The gpu Plugin',['../gpu.html',1,'']]],
  ['gpu_20stream_5fdeinit_29',['%gpu.stream_deinit',['../gpu.html#autotoc_md296',1,'']]],
  ['gpu_20stream_5finit_30',['%gpu.stream_init',['../gpu.html#autotoc_md295',1,'']]],
  ['gpu_20stream_5fsync_31',['%gpu.stream_sync',['../gpu.html#autotoc_md297',1,'']]],
  ['gpu_20sync_5fwork_5fitems_32',['%gpu.sync_work_items',['../gpu.html#autotoc_md317',1,'']]],
  ['gpu_20synced_5fscope_33',['%gpu.synced_scope',['../gpu.html#autotoc_md318',1,'']]],
  ['gpu_20with_5fstreams_34',['%gpu.with_streams',['../gpu.html#autotoc_md298',1,'']]],
  ['grammar_35',['Grammar',['../langref.html#grammar',1,'']]],
  ['graphs_36',['Displaying DOT Graphs',['../coding.html#autotoc_md26',1,'']]],
  ['gt_37',['gt',['../cli.html#xarg_compile',1,'-X compile:&amp;lt;arg&amp;gt;'],['../cli.html#xarg_ll',1,'-X ll:&amp;lt;arg&amp;gt;'],['../cli.html#xarg_ll_nvptx',1,'-X ll_nvptx:&amp;lt;arg&amp;gt;'],['../cli.html#xarg_tensor',1,'-X tensor:&amp;lt;arg&amp;gt;']]],
  ['guard_20exists_20at_20all_38',['Why the guard exists at all',['../phases.html#autotoc_md107',1,'']]],
  ['guide_39',['Developer Guide',['../dev.html',1,'']]]
];
