var searchData=
[
  ['scan_0',['%vec.scan',['../vec.html#autotoc_md483',1,'']]],
  ['scanning_1',['Scanning',['../vec.html#autotoc_md482',1,'']]],
  ['scatter_2',['scatter',['../btensor.html#autotoc_md220',1,'%btensor.scatter'],['../tensor.html#autotoc_md468',1,'%tensor.scatter']]],
  ['sccp_3',['Example: SCCP',['../phases.html#autotoc_md105',1,'']]],
  ['schedules_4',['Schedules',['../tensor.html#autotoc_md447',1,'']]],
  ['scope_20nesting_5',['Scope &amp;amp; Nesting',['../dev.html#autotoc_md40',1,'']]],
  ['scoped_20substitution_6',['Scoped Substitution',['../rewriting.html#autotoc_md148',1,'']]],
  ['scopeless_20binders_7',['Scopeless Binders',['../mimir.html#mimir_scopeless',1,'']]],
  ['scoping_8',['Scoping',['../langref.html#autotoc_md76',1,'Scoping'],['../rewriting.html#autotoc_md144',1,'Scoping']]],
  ['sea_20of_20nodes_9',['🌊 Sea of Nodes',['../index.html#autotoc_md138',1,'']]],
  ['search_20paths_10',['Search Paths',['../cli.html#autotoc_md12',1,'']]],
  ['secondary_20terminals_11',['Secondary Terminals',['../langref.html#autotoc_md60',1,'']]],
  ['select_12',['%core.Select',['../core.html#autotoc_md277',1,'']]],
  ['select_13',['select',['../core.html#autotoc_md276',1,'%core.select'],['../tensor.html#autotoc_md466',1,'%tensor.select']]],
  ['semiop_20mul_20ceildiv_20floordiv_20mod_14',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md183',1,'']]],
  ['set_15',['%tensor.set',['../tensor.html#autotoc_md437',1,'']]],
  ['set_20ord_20map_16',['%ord.Set / %ord.Map',['../ord.html#autotoc_md387',1,'']]],
  ['setjmp_17',['%clos.setjmp',['../clos.html#autotoc_md239',1,'']]],
  ['sgn_18',['%math.sgn',['../math.html#autotoc_md349',1,'']]],
  ['shape_19',['Shape',['../dev.html#autotoc_md55',1,'Shape'],['../phases.html#autotoc_md85',1,'Typical Shape'],['../phases.html#autotoc_md97',1,'Typical Shape'],['../phases.html#autotoc_md102',1,'Typical Shape'],['../phases.html#autotoc_md103',1,'Typical Shape'],['../phases.html#autotoc_md104',1,'Typical Shape']]],
  ['shape_20',['shape',['../buffer.html#autotoc_md231',1,'%buffer.shape'],['../tensor.html#autotoc_md439',1,'%tensor.shape']]],
  ['shr_21',['%core.shr',['../core.html#autotoc_md264',1,'']]],
  ['side_20effects_22',['Side Effects',['../mem.html#autotoc_md354',1,'Operations w/ Side Effects'],['../mem.html#autotoc_md364',1,'Operations w/o Side Effects']]],
  ['sigmas_23',['Field Names of Sigmas',['../langref.html#autotoc_md79',1,'']]],
  ['size_24',['%ord.size',['../ord.html#autotoc_md392',1,'']]],
  ['slf_25',['%math.slf',['../math.html#autotoc_md348',1,'']]],
  ['slice_26',['%tensor.slice',['../tensor.html#autotoc_md450',1,'']]],
  ['slot_27',['%mem.slot',['../mem.html#autotoc_md360',1,'']]],
  ['some_28',['%option.some',['../option.html#autotoc_md377',1,'']]],
  ['some_5fif_29',['%option.some_if',['../option.html#autotoc_md379',1,'']]],
  ['spaces_30',['Address Spaces',['../gpu.html#autotoc_md287',1,'']]],
  ['sparse_20fixed_20point_20iteration_31',['Sparse Fixed-Point Iteration',['../phases.html#autotoc_md88',1,'']]],
  ['specifically_32',['Haskell specifically',['../md_docs_2why-cpp.html#autotoc_md163',1,'']]],
  ['speculative_20construction_20with_20arena_20rollback_33',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['splat_34',['%tensor.splat',['../tensor.html#autotoc_md438',1,'']]],
  ['ssa_20via_20cps_35',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['ssa_20without_20dominance_36',['SSA without Dominance',['../index.html#autotoc_md139',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['standalone_20third_20party_20builds_37',['Standalone Third-Party Builds',['../plugins.html#autotoc_md125',1,'']]],
  ['start_38',['Start',['../index.html#autotoc_md134',1,'🚀 Quick Start'],['../coding.html#building',1,'Contributor Quick Start']]],
  ['steps_39',['First Steps',['../python.html#autotoc_md127',1,'']]],
  ['store_40',['%mem.store',['../mem.html#autotoc_md356',1,'']]],
  ['story_20is_20worse_20not_20better_41',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md172',1,'']]],
  ['stream_5fdeinit_42',['%gpu.stream_deinit',['../gpu.html#autotoc_md298',1,'']]],
  ['stream_5finit_43',['%gpu.stream_init',['../gpu.html#autotoc_md297',1,'']]],
  ['stream_5fsync_44',['%gpu.stream_sync',['../gpu.html#autotoc_md299',1,'']]],
  ['streams_45',['Streams',['../gpu.html#autotoc_md290',1,'Streams'],['../gpu.html#autotoc_md296',1,'Streams'],['../nvptx.html#autotoc_md369',1,'Streams']]],
  ['strip_20mining_46',['Strip-Mining',['../tensor.html#autotoc_md446',1,'']]],
  ['structure_47',['Lexical Structure',['../langref.html#lex',1,'']]],
  ['style_48',['Style',['../coding.html#autotoc_md17',1,'C++ Style'],['../coding.html#autotoc_md20',1,'CMake Style'],['../coding.html#autotoc_md16',1,'Coding Style'],['../coding.html#autotoc_md18',1,'Doxygen Style'],['../coding.html#includes',1,'Include Style'],['../coding.html#autotoc_md22',1,'M⁠im Coding Style'],['../coding.html#autotoc_md21',1,'Markdown Style']]],
  ['style_20is_20much_20worse_49',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md159',1,'']]],
  ['sub_50',['%affine.op(add,sub)',['../affine.html#autotoc_md181',1,'']]],
  ['substitution_51',['Scoped Substitution',['../rewriting.html#autotoc_md148',1,'']]],
  ['subtags_52',['Subtags',['../dev.html#autotoc_md49',1,'With Subtags'],['../dev.html#autotoc_md48',1,'Without Subtags']]],
  ['sum_53',['%autodiff.sum',['../autodiff.html#autotoc_md200',1,'']]],
  ['sum_20type_20in_20one_20machine_20word_54',['&lt;span class=&quot;tt&quot;&gt;XTrie::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['summary_55',['Summary',['../dev.html#autotoc_md46',1,'Summary'],['../dev.html#autotoc_md50',1,'Summary'],['../dev.html#autotoc_md56',1,'Summary'],['../phases.html#autotoc_md117',1,'Summary'],['../md_docs_2why-cpp.html#autotoc_md174',1,'Summary']]],
  ['summary_3a_20functions_20and_20types_56',['Summary: Functions and Types',['../langref.html#autotoc_md71',1,'']]],
  ['sync_5fwork_5fitems_57',['%gpu.sync_work_items',['../gpu.html#autotoc_md319',1,'']]],
  ['synced_5fscope_58',['%gpu.synced_scope',['../gpu.html#autotoc_md320',1,'']]],
  ['synchronization_59',['Work-Item Synchronization',['../gpu.html#autotoc_md318',1,'']]],
  ['syntax_60',['Syntax',['../mimir.html#autotoc_md80',1,'']]],
  ['syntax_20highlighting_61',['Syntax Highlighting',['../coding.html#autotoc_md23',1,'']]]
];
