var searchData=
[
  ['tail_0',['%tuple.head / %tuple.tail',['../tuple.html#autotoc_md400',1,'']]],
  ['taste_20of_20mim_1',['✨ A Taste of Mim',['../index.html#autotoc_md108',1,'']]],
  ['tensor_20binary_2',['%tensor.binary',['../tensor.html#autotoc_md392',1,'']]],
  ['tensor_20bmm_3',['%tensor.bmm',['../tensor.html#autotoc_md385',1,'']]],
  ['tensor_20broadcast_4',['%tensor.broadcast',['../tensor.html#autotoc_md388',1,'']]],
  ['tensor_20broadcast_5fin_5fdim_5',['tensor broadcast_in_dim',['../tensor.html#autotoc_md389',1,'%tensor.broadcast_in_dim'],['../todo.html#_todo000003',1,'%tensor.broadcast_in_dim']]],
  ['tensor_20concat_6',['%tensor.concat',['../tensor.html#autotoc_md380',1,'']]],
  ['tensor_20conv_7',['%tensor.conv',['../tensor.html#autotoc_md381',1,'']]],
  ['tensor_20dot_5fproduct_8',['%tensor.dot_product',['../tensor.html#autotoc_md383',1,'']]],
  ['tensor_20flip_9',['%tensor.flip',['../tensor.html#autotoc_md378',1,'']]],
  ['tensor_20get_10',['%tensor.get',['../tensor.html#autotoc_md371',1,'']]],
  ['tensor_20map_11',['%tensor.map',['../tensor.html#autotoc_md390',1,'']]],
  ['tensor_20map_5freduce_12',['%tensor.map_reduce',['../tensor.html#autotoc_md374',1,'']]],
  ['tensor_20pad_13',['%tensor.pad',['../tensor.html#autotoc_md379',1,'']]],
  ['tensor_20plugin_14',['The tensor Plugin',['../tensor.html',1,'']]],
  ['tensor_20pool_15',['%tensor.pool',['../tensor.html#autotoc_md382',1,'']]],
  ['tensor_20product_5f2d_16',['%tensor.product_2d',['../tensor.html#autotoc_md384',1,'']]],
  ['tensor_20repeat_17',['%tensor.repeat',['../tensor.html#autotoc_md375',1,'']]],
  ['tensor_20reshape_18',['%tensor.reshape',['../tensor.html#autotoc_md376',1,'']]],
  ['tensor_20ring_19',['%tensor.Ring',['../tensor.html#autotoc_md369',1,'']]],
  ['tensor_20select_20',['%tensor.select',['../tensor.html#autotoc_md393',1,'']]],
  ['tensor_20set_21',['%tensor.set',['../tensor.html#autotoc_md372',1,'']]],
  ['tensor_20shape_22',['%tensor.shape',['../tensor.html#autotoc_md373',1,'']]],
  ['tensor_20slice_23',['%tensor.slice',['../tensor.html#autotoc_md377',1,'']]],
  ['tensor_20transpose_24',['%tensor.transpose',['../tensor.html#autotoc_md386',1,'']]],
  ['tensor_20transpose_5f2d_25',['%tensor.transpose_2d',['../tensor.html#autotoc_md387',1,'']]],
  ['tensor_20unary_26',['%tensor.unary',['../tensor.html#autotoc_md391',1,'']]],
  ['terminals_27',['Terminals',['../langref.html#autotoc_md46',1,'Pattern Terminals'],['../langref.html#autotoc_md43',1,'Primary Terminals'],['../langref.html#autotoc_md44',1,'Secondary Terminals'],['../langref.html#terminals',1,'Terminals']]],
  ['testing_28',['Testing',['../coding.html#testing',1,'Testing'],['../refly.html#autotoc_md342',1,'Testing']]],
  ['tests_29',['lit Tests',['../coding.html#autotoc_md3',1,'']]],
  ['the_20affine_20plugin_30',['The affine Plugin',['../affine.html',1,'']]],
  ['the_20automatic_20differentiation_20plugin_31',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['the_20buffer_20plugin_32',['The buffer Plugin',['../buffer.html',1,'']]],
  ['the_20classical_20picture_33',['The classical picture',['../phases.html#autotoc_md84',1,'']]],
  ['the_20clos_20plugin_34',['The clos Plugin',['../clos.html',1,'']]],
  ['the_20compile_20plugin_35',['The compile Plugin',['../compile.html',1,'']]],
  ['the_20core_20plugin_36',['The core Plugin',['../core.html',1,'']]],
  ['the_20cps_20plugin_37',['The CPS Plugin',['../cps.html',1,'']]],
  ['the_20default_20pipeline_38',['The default pipeline',['../opt.html#autotoc_md306',1,'']]],
  ['the_20demo_20plugin_39',['The demo Plugin',['../demo.html',1,'']]],
  ['the_20gpu_20plugin_40',['The gpu Plugin',['../gpu.html',1,'']]],
  ['the_20guard_20exists_20at_20all_41',['Why the guard exists at all',['../phases.html#autotoc_md83',1,'']]],
  ['the_20ll_20plugin_42',['The ll Plugin',['../ll.html',1,'']]],
  ['the_20math_20plugin_43',['The math Plugin',['../math.html',1,'']]],
  ['the_20matrix_20plugin_44',['The matrix Plugin',['../matrix.html',1,'']]],
  ['the_20mem_20plugin_45',['The mem Plugin',['../mem.html',1,'']]],
  ['the_20mimir_20picture_46',['The MimIR picture',['../phases.html#autotoc_md85',1,'']]],
  ['the_20opt_20plugin_47',['The opt Plugin',['../opt.html',1,'']]],
  ['the_20option_20plugin_48',['The option Plugin',['../option.html',1,'']]],
  ['the_20ord_20plugin_49',['The ord Plugin',['../ord.html',1,'']]],
  ['the_20program_50',['Iterating over the Program',['../dev.html#autotoc_md41',1,'']]],
  ['the_20refly_20plugin_51',['The refly Plugin',['../refly.html',1,'']]],
  ['the_20regex_20plugin_52',['The regex Plugin',['../regex.html',1,'']]],
  ['the_20right_20base_20class_53',['Choosing the Right Base Class',['../phases.html#autotoc_md89',1,'']]],
  ['the_20tensor_20plugin_54',['The tensor Plugin',['../tensor.html',1,'']]],
  ['the_20tuple_20plugin_55',['The tuple Plugin',['../tuple.html',1,'']]],
  ['the_20vec_20plugin_56',['The vec Plugin',['../vec.html',1,'']]],
  ['third_20party_20builds_57',['Standalone Third-Party Builds',['../plugins.html#autotoc_md99',1,'']]],
  ['third_20party_20plugin_58',['Create a Third-Party Plugin',['../plugins.html#autotoc_md96',1,'']]],
  ['third_20party_20plugin_20discovery_59',['Third-Party Plugin Discovery',['../plugins.html#autotoc_md97',1,'']]],
  ['this_20is_20hard_20elsewhere_60',['Why this is hard elsewhere',['../phases.html#autotoc_md86',1,'']]],
  ['thresholded_20variants_61',['Thresholded Variants',['../dev.html#autotoc_md38',1,'']]],
  ['to_20immutables_62',['Downcast to Immutables',['../dev.html#autotoc_md28',1,'']]],
  ['to_20longjmp_63',['Operations related to longjmp',['../clos.html#autotoc_md171',1,'']]],
  ['to_20mutables_64',['Downcast to Mutables',['../dev.html#autotoc_md29',1,'']]],
  ['to_20plugins_20phases_65',['Passing Arguments to Plugins &amp;amp; Phases',['../cli.html#clipluginargs',1,'']]],
  ['todo_20list_66',['Todo List',['../todo.html',1,'']]],
  ['tour_20of_20mimir_67',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['trait_68',['%core.trait',['../core.html#autotoc_md204',1,'']]],
  ['transformation_69',['Transformation',['../phases.html#autotoc_md87',1,'']]],
  ['translations_70',['Registered translations',['../autodiff.html#autotoc_md153',1,'']]],
  ['transpose_71',['transpose',['../matrix.html#autotoc_md275',1,'%matrix.transpose'],['../tensor.html#autotoc_md386',1,'%tensor.transpose'],['../matrix.html#autotoc_md284',1,'transpose']]],
  ['transpose_5f2d_72',['%tensor.transpose_2d',['../tensor.html#autotoc_md387',1,'']]],
  ['tree_20plugin_73',['Tree Plugin',['../plugins.html#autotoc_md95',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md98',1,'Extract an Existing In-Tree Plugin']]],
  ['tri_74',['%math.tri',['../math.html#autotoc_md256',1,'']]],
  ['triggering_20breakpoints_75',['Triggering Breakpoints',['../coding.html#autotoc_md19',1,'']]],
  ['tuple_20append_20tuple_20prepend_76',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md399',1,'']]],
  ['tuple_20cat_77',['%tuple.cat',['../tuple.html#autotoc_md398',1,'']]],
  ['tuple_20contains_78',['%tuple.contains',['../tuple.html#autotoc_md401',1,'']]],
  ['tuple_20head_20tuple_20tail_79',['%tuple.head / %tuple.tail',['../tuple.html#autotoc_md400',1,'']]],
  ['tuple_20plugin_80',['The tuple Plugin',['../tuple.html',1,'']]],
  ['tuple_20prepend_81',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md399',1,'']]],
  ['tuple_20tail_82',['%tuple.head / %tuple.tail',['../tuple.html#autotoc_md400',1,'']]],
  ['tuple_20typecat_83',['%tuple.typecat',['../tuple.html#autotoc_md397',1,'']]],
  ['tuple_20zip_84',['%tuple.zip',['../tuple.html#autotoc_md402',1,'']]],
  ['type_85',['%refly.type',['../refly.html#autotoc_md339',1,'']]],
  ['typecat_86',['%tuple.typecat',['../tuple.html#autotoc_md397',1,'']]],
  ['types_87',['Types',['../langref.html#autotoc_md58',1,'Function Types'],['../langref.html#autotoc_md48',1,'Kinds and Builtin Types'],['../gpu.html#autotoc_md217',1,'Memory Types'],['../gpu.html#autotoc_md218',1,'Pointer Types'],['../langref.html#autotoc_md54',1,'Summary: Functions and Types'],['../autodiff.html#autotoc_md145',1,'Types'],['../buffer.html#autotoc_md158',1,'Types'],['../compile.html#autotoc_md174',1,'Types'],['../gpu.html#autotoc_md215',1,'Types'],['../math.html#autotoc_md251',1,'Types'],['../matrix.html#autotoc_md272',1,'Types'],['../mem.html#autotoc_md291',1,'Types'],['../option.html#autotoc_md308',1,'Types'],['../ord.html#autotoc_md318',1,'Types'],['../refly.html#autotoc_md333',1,'Types'],['../regex.html#autotoc_md350',1,'Types'],['../tensor.html#autotoc_md368',1,'Types']]],
  ['types_20are_20values_88',['Types Are Values',['../mimir.html#mimir_dep',1,'']]],
  ['typical_20shape_89',['Typical Shape',['../phases.html#autotoc_md68',1,'Typical Shape'],['../phases.html#autotoc_md78',1,'Typical Shape'],['../phases.html#autotoc_md79',1,'Typical Shape'],['../phases.html#autotoc_md80',1,'Typical Shape']]],
  ['typical_20usage_90',['Typical Usage',['../rewriting.html#autotoc_md123',1,'Typical Usage'],['../rewriting.html#autotoc_md125',1,'Typical Usage']]]
];
