var searchData=
[
  ['a_20four_20way_20sum_20type_20in_20one_20machine_20word_0',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['a_20new_20in_20tree_20plugin_1',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md111',1,'']]],
  ['a_20taste_20of_20mim_2',['✨ A Taste of Mim',['../index.html#autotoc_md122',1,'']]],
  ['a_20third_20party_20plugin_3',['Create a Third-Party Plugin',['../plugins.html#autotoc_md112',1,'']]],
  ['a_20tour_20of_20mimir_4',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['about_20rust_5',['What about Rust?',['../md_docs_2why-cpp.html#autotoc_md159',1,'']]],
  ['abs_6',['abs',['../core.html#autotoc_md255',1,'%core.abs'],['../math.html#autotoc_md321',1,'%math.abs']]],
  ['absl_3a_3aflat_5fhash_5f_7',['&lt;span class=&quot;tt&quot;&gt;absl::flat_hash_*&lt;/span&gt;',['../md_docs_2why-cpp.html#autotoc_md144',1,'']]],
  ['actually_20relies_20on_8',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md143',1,'']]],
  ['ad_9',['%autodiff.AD',['../autodiff.html#autotoc_md186',1,'']]],
  ['ad_10',['%autodiff.ad',['../autodiff.html#autotoc_md187',1,'']]],
  ['add_11',['%autodiff.add',['../autodiff.html#autotoc_md189',1,'']]],
  ['add_20sub_12',['%affine.op(add,sub)',['../affine.html#autotoc_md171',1,'']]],
  ['add_5fmim_5fplugin_13',['add_mim_plugin',['../add_mim_plugin_cmake.html',1,'']]],
  ['add_5fmim_5fruntime_14',['add_mim_runtime',['../add_mim_runtime_cmake.html',1,'']]],
  ['address_20spaces_15',['Address Spaces',['../gpu.html#autotoc_md272',1,'']]],
  ['affine_20constant_16',['%affine.constant',['../affine.html#autotoc_md170',1,'']]],
  ['affine_20delinearize_17',['%affine.delinearize',['../affine.html#autotoc_md178',1,'']]],
  ['affine_20for_18',['%affine.For',['../affine.html#autotoc_md167',1,'']]],
  ['affine_20id_19',['%affine.id',['../affine.html#autotoc_md176',1,'']]],
  ['affine_20index_20',['%affine.index',['../affine.html#autotoc_md169',1,'']]],
  ['affine_20index_20operations_21',['Affine Index Operations',['../affine.html#autotoc_md168',1,'']]],
  ['affine_20linearize_22',['%affine.linearize',['../affine.html#autotoc_md177',1,'']]],
  ['affine_20lower_5ffor_23',['%affine.lower_for',['../affine.html#autotoc_md180',1,'']]],
  ['affine_20lower_5findex_24',['%affine.lower_index',['../affine.html#autotoc_md181',1,'']]],
  ['affine_20map_25',['%affine.map',['../affine.html#autotoc_md175',1,'']]],
  ['affine_20op_20add_20sub_26',['%affine.op(add,sub)',['../affine.html#autotoc_md171',1,'']]],
  ['affine_20op_20mul_27',['%affine.op.mul',['../affine.html#autotoc_md174',1,'']]],
  ['affine_20op_20neg_28',['%affine.op(neg)',['../affine.html#autotoc_md172',1,'']]],
  ['affine_20plugin_29',['The affine Plugin',['../affine.html',1,'']]],
  ['affine_20semiop_20mul_20ceildiv_20floordiv_20mod_30',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md173',1,'']]],
  ['aggr_31',['%compile.aggr',['../compile.html#autotoc_md236',1,'']]],
  ['all_32',['Why the guard exists at all',['../phases.html#autotoc_md96',1,'']]],
  ['alloc_33',['alloc',['../buffer.html#autotoc_md212',1,'%buffer.alloc'],['../mem.html#autotoc_md338',1,'%mem.alloc']]],
  ['alloc_20asyn_34',['%gpu.alloc(asyn)',['../gpu.html#autotoc_md292',1,'']]],
  ['alloc_20block_35',['%gpu.alloc(block)',['../gpu.html#autotoc_md286',1,'']]],
  ['alloc_5fcopy_20asyn_36',['%gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md296',1,'']]],
  ['alloc_5fcopy_20block_37',['%gpu.alloc_copy(block)',['../gpu.html#autotoc_md290',1,'']]],
  ['alloc_5fjmpbuf_38',['%clos.alloc_jmpbuf',['../clos.html#autotoc_md224',1,'']]],
  ['an_20existing_20in_20tree_20plugin_39',['Extract an Existing In-Tree Plugin',['../plugins.html#autotoc_md114',1,'']]],
  ['analysis_40',['Analysis',['../phases.html#phases_analysis',1,'Analysis'],['../phases.html#autotoc_md95',1,'Analysis'],['../phases.html#autotoc_md80',1,'Optional Pre-Analysis']]],
  ['analysis_20results_41',['Analysis Results',['../phases.html#autotoc_md81',1,'']]],
  ['and_20basic_20forms_42',['Literals and Basic Forms',['../langref.html#autotoc_md54',1,'']]],
  ['and_20builtin_20types_43',['Kinds and Builtin Types',['../langref.html#autotoc_md53',1,'']]],
  ['and_20continuations_44',['Functions and Continuations',['../langref.html#autotoc_md55',1,'']]],
  ['and_20how_20defs_20are_20placed_20in_20them_45',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['and_20types_46',['Summary: Functions and Types',['../langref.html#autotoc_md60',1,'']]],
  ['and_20why_20it_20defeats_20the_20purpose_47',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['annex_48',['Annex',['../langref.html#autotoc_md67',1,'']]],
  ['annexes_49',['Annexes',['../mimir.html#autotoc_md70',1,'Annexes'],['../dev.html#autotoc_md22',1,'Calling Annexes']]],
  ['any_50',['%regex.any',['../regex.html#autotoc_md404',1,'']]],
  ['api_51',['Lattice API',['../phases.html#autotoc_md75',1,'']]],
  ['append_20tuple_20prepend_52',['%tuple.append / %tuple.prepend',['../tuple.html#autotoc_md443',1,'']]],
  ['applications_53',['Applications',['../langref.html#autotoc_md63',1,'']]],
  ['apply_20here_54',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['are_20placed_20in_20them_55',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['are_20values_56',['Types Are Values',['../mimir.html#mimir_dep',1,'']]],
  ['arena_20rollback_57',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md148',1,'']]],
  ['arenas_20and_20how_20defs_20are_20placed_20in_20them_58',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md147',1,'']]],
  ['argument_59',['The empirical argument',['../md_docs_2why-cpp.html#autotoc_md154',1,'']]],
  ['arguments_60',['Arguments',['../compile.html#compile_cli_args',1,'Command-Line Arguments'],['../ll.html#ll_cli_args',1,'Command-Line Arguments'],['../ll_nvptx.html#ll_nvptx_cli_args',1,'Command-Line Arguments'],['../cli.html#autotoc_md1',1,'Known Arguments']]],
  ['arguments_20to_20plugins_61',['Passing Arguments to Plugins',['../cli.html#clipluginargs',1,'']]],
  ['arith_62',['%math.arith',['../math.html#autotoc_md313',1,'']]],
  ['arity_63',['Arity',['../dev.html#autotoc_md41',1,'']]],
  ['asyn_64',['asyn',['../gpu.html#autotoc_md292',1,'%gpu.alloc(asyn)'],['../gpu.html#autotoc_md296',1,'%gpu.alloc_copy(asyn)'],['../gpu.html#autotoc_md294',1,'%gpu.copy_to_device(asyn)'],['../gpu.html#autotoc_md295',1,'%gpu.copy_to_host(asyn)'],['../gpu.html#autotoc_md293',1,'%gpu.free(asyn)']]],
  ['async_20memory_20operations_65',['Async Memory Operations',['../gpu.html#autotoc_md291',1,'']]],
  ['at_20all_66',['Why the guard exists at all',['../phases.html#autotoc_md96',1,'']]],
  ['at_20roughly_20performance_20parity_67',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md160',1,'']]],
  ['attr_68',['%clos.attr',['../clos.html#autotoc_md228',1,'']]],
  ['attribute_69',['Closure Attribute',['../clos.html#autotoc_md227',1,'']]],
  ['autodiff_20ad_70',['%autodiff.AD',['../autodiff.html#autotoc_md186',1,'']]],
  ['autodiff_20ad_71',['%autodiff.ad',['../autodiff.html#autotoc_md187',1,'']]],
  ['autodiff_20add_72',['%autodiff.add',['../autodiff.html#autotoc_md189',1,'']]],
  ['autodiff_20diff_73',['%autodiff.diff',['../autodiff.html#autotoc_md193',1,'']]],
  ['autodiff_20diff_20core_5ficmp_5fxygle_74',['%autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md194',1,'']]],
  ['autodiff_20diff_20core_5fwrap_5fadd_75',['%autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md195',1,'']]],
  ['autodiff_20diff_20core_5fwrap_5fmul_76',['%autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md196',1,'']]],
  ['autodiff_20sum_77',['%autodiff.sum',['../autodiff.html#autotoc_md190',1,'']]],
  ['autodiff_20tangent_78',['%autodiff.Tangent',['../autodiff.html#autotoc_md184',1,'']]],
  ['autodiff_20zero_79',['%autodiff.zero',['../autodiff.html#autotoc_md188',1,'']]],
  ['automatic_20differentiation_20plugin_80',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['axioms_81',['Axioms',['../mimir.html#autotoc_md71',1,'Axioms'],['../dev.html#cast_axm',1,'Matching Axioms']]]
];
