var searchData=
[
  ['c_0',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['c_20implementation_20actually_20relies_20on_1',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md150',1,'']]],
  ['c_20style_2',['C++ Style',['../coding.html#autotoc_md17',1,'']]],
  ['caches_20must_20move_20out_20of_20the_20node_3',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['calling_20annexes_4',['Calling Annexes',['../dev.html#autotoc_md33',1,'']]],
  ['capacity_5',['Capacity',['../ord.html#autotoc_md423',1,'']]],
  ['casts_6',['Further Casts',['../dev.html#autotoc_md47',1,'']]],
  ['cat_7',['cat',['../tuple.html#autotoc_md552',1,'cat'],['../vec.html#autotoc_md567',1,'cat']]],
  ['catching_20exceptions_8',['Catching Exceptions',['../coding.html#autotoc_md28',1,'']]],
  ['caveats_9',['Two honest caveats',['../md_docs_2why-cpp.html#autotoc_md163',1,'']]],
  ['ceildiv_20floordiv_20rem_10',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md179',1,'']]],
  ['check_11',['check',['../refly.html#autotoc_md444',1,'']]],
  ['check_5faddr_5fspaces_5frepl_12',['check_addr_spaces_repl',['../gpu.html#autotoc_md340',1,'']]],
  ['check_5fbot_13',['check_bot',['../refly.html#autotoc_md443',1,'']]],
  ['choosing_20the_20right_20base_20class_14',['Choosing the Right Base Class',['../phases.html#autotoc_md110',1,'']]],
  ['class_15',['Choosing the Right Base Class',['../phases.html#autotoc_md110',1,'']]],
  ['classical_20picture_16',['The classical picture',['../phases.html#autotoc_md105',1,'']]],
  ['cleanup_17',['Cleanup',['../phases.html#autotoc_md93',1,'']]],
  ['cleanup_18',['cleanup',['../compile.html#autotoc_md269',1,'']]],
  ['clos_20plugin_19',['The clos Plugin',['../clos.html',1,'']]],
  ['clos2sjlj_20',['clos2sjlj',['../clos.html#autotoc_md256',1,'']]],
  ['clos_5fconv_21',['clos_conv',['../clos.html#autotoc_md253',1,'']]],
  ['clos_5fconv_5fprep_22',['clos_conv_prep',['../clos.html#autotoc_md252',1,'']]],
  ['closedmutphase_23',['ClosedMutPhase',['../phases.html#phases_closed_mut_phase',1,'']]],
  ['closure_20attribute_24',['Closure Attribute',['../clos.html#autotoc_md249',1,'']]],
  ['cls_25',['cls.*',['../regex.html#autotoc_md458',1,'']]],
  ['cmake_20style_26',['CMake Style',['../coding.html#autotoc_md20',1,'']]],
  ['cmp_27',['cmp',['../math.html#autotoc_md371',1,'']]],
  ['code_28',['Code',['../refly.html#autotoc_md433',1,'']]],
  ['coding_20style_29',['Coding Style',['../coding.html#autotoc_md16',1,'Coding Style'],['../coding.html#autotoc_md22',1,'M⁠im Coding Style']]],
  ['command_20line_20reference_30',['Command-Line Reference',['../cli.html',1,'']]],
  ['comments_31',['Comments',['../langref.html#autotoc_md63',1,'']]],
  ['community_32',['💬 Community',['../index.html#autotoc_md138',1,'']]],
  ['compilation_20pipelines_20in_20m⁠im_33',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md113',1,'']]],
  ['compile_34',['compile',['../cli.html#xarg_compile',1,'']]],
  ['compile_20plugin_35',['The compile Plugin',['../compile.html',1,'']]],
  ['concat_36',['concat',['../btensor.html#autotoc_md216',1,'concat'],['../tensor.html#autotoc_md484',1,'concat']]],
  ['cond_37',['cond',['../compile.html#autotoc_md262',1,'']]],
  ['conditional_20breakpoints_38',['Conditional Breakpoints',['../coding.html#autotoc_md27',1,'']]],
  ['conj_39',['conj',['../regex.html#autotoc_md451',1,'']]],
  ['consing_20is_20inherently_20impure_40',['Hash-consing is inherently impure',['../md_docs_2why-cpp.html#autotoc_md157',1,'']]],
  ['const_5fidx_41',['const_idx',['../demo.html#autotoc_md308',1,'']]],
  ['construction_20with_20arena_20rollback_42',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md154',1,'']]],
  ['constructors_43',['Constructors',['../option.html#autotoc_md408',1,'Constructors'],['../ord.html#autotoc_md420',1,'Constructors'],['../tensor.html#autotoc_md468',1,'Constructors']]],
  ['contains_44',['contains',['../ord.html#autotoc_md428',1,'contains'],['../tuple.html#autotoc_md555',1,'contains']]],
  ['context_45',['Context',['../gpu.html#autotoc_md316',1,'']]],
  ['continuations_46',['Functions and Continuations',['../langref.html#autotoc_md67',1,'']]],
  ['contributing_20debugging_47',['Contributing &amp;amp; Debugging',['../coding.html',1,'']]],
  ['contributor_20quick_20start_48',['Contributor Quick Start',['../coding.html#building',1,'']]],
  ['conv_49',['conv',['../core.html#autotoc_md294',1,'conv'],['../cps.html#autotoc_md306',1,'conv'],['../math.html#autotoc_md373',1,'conv'],['../tensor.html#autotoc_md499',1,'conv']]],
  ['conv_5fimpl_50',['conv_impl',['../tensor.html#autotoc_md533',1,'']]],
  ['conv_5fschedule_51',['conv_schedule',['../tensor.html#autotoc_md520',1,'']]],
  ['conversions_52',['Conversions',['../core.html#autotoc_md293',1,'']]],
  ['copy_53',['copy',['../buffer.html#autotoc_md240',1,'']]],
  ['copy_5fto_5fdevice_20asyn_54',['copy_to_device(block) / copy_to_device(asyn)',['../gpu.html#autotoc_md328',1,'']]],
  ['copy_5fto_5fdevice_20block_20copy_5fto_5fdevice_20asyn_55',['copy_to_device(block) / copy_to_device(asyn)',['../gpu.html#autotoc_md328',1,'']]],
  ['copy_5fto_5fhost_20asyn_56',['copy_to_host(block) / copy_to_host(asyn)',['../gpu.html#autotoc_md329',1,'']]],
  ['copy_5fto_5fhost_20block_20copy_5fto_5fhost_20asyn_57',['copy_to_host(block) / copy_to_host(asyn)',['../gpu.html#autotoc_md329',1,'']]],
  ['core_20plugin_58',['The core Plugin',['../core.html',1,'']]],
  ['core_5ficmp_5fxygle_59',['autodiff.diff.core_icmp_xYgLE',['../autodiff.html#autotoc_md202',1,'']]],
  ['core_5fwrap_5fadd_60',['autodiff.diff.core_wrap_add',['../autodiff.html#autotoc_md203',1,'']]],
  ['core_5fwrap_5fmul_61',['autodiff.diff.core_wrap_mul',['../autodiff.html#autotoc_md204',1,'']]],
  ['costs_62',['Non-performance costs',['../md_docs_2why-cpp.html#autotoc_md162',1,'']]],
  ['coverage_63',['Coverage',['../python.html#autotoc_md126',1,'']]],
  ['cps_64',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['cps_20plugin_65',['The CPS Plugin',['../cps.html',1,'']]],
  ['cps2ds_66',['cps2ds',['../cps.html#autotoc_md304',1,'']]],
  ['create_67',['create',['../ord.html#autotoc_md422',1,'']]],
  ['create_20a_20new_20in_20tree_20plugin_68',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md119',1,'']]],
  ['create_20a_20third_20party_20plugin_69',['Create a Third-Party Plugin',['../plugins.html#autotoc_md120',1,'']]]
];
