var searchData=
[
  ['range_0',['range',['../regex.html#autotoc_md475',1,'']]],
  ['range_5fnest_1',['range_nest',['../btensor.html#autotoc_md246',1,'']]],
  ['range_5funroll_2',['range_unroll',['../btensor.html#autotoc_md247',1,'']]],
  ['re_3',['RE',['../regex.html#autotoc_md470',1,'']]],
  ['read_4',['read',['../buffer.html#autotoc_md257',1,'']]],
  ['reassoc_5',['reassoc',['../tensor.html#autotoc_md595',1,'']]],
  ['recommended_20design_20pattern_6',['Recommended Design Pattern',['../phases.html#autotoc_md118',1,'']]],
  ['reduce_7',['Reduce',['../btensor.html#autotoc_md224',1,'Map-Reduce'],['../tensor.html#autotoc_md496',1,'Map-Reduce']]],
  ['reductions_8',['Reductions',['../btensor.html#autotoc_md236',1,'Reductions'],['../tensor.html#autotoc_md523',1,'Reductions']]],
  ['reference_9',['Reference',['../cli.html',1,'Command-Line Reference'],['../langref.html',1,'Mim Language Reference']]],
  ['reflect_10',['Reify / Reflect',['../refly.html#autotoc_md454',1,'']]],
  ['reflect_11',['reflect',['../refly.html#autotoc_md456',1,'']]],
  ['reflection_12',['Reflection',['../tensor.html#autotoc_md534',1,'']]],
  ['refly_20plugin_13',['The refly Plugin',['../refly.html',1,'']]],
  ['regex_20plugin_14',['The regex Plugin',['../regex.html',1,'']]],
  ['registered_20translations_15',['Registered translations',['../autodiff.html#autotoc_md216',1,'']]],
  ['registry_16',['Plugin Registry',['../plugins.html#autotoc_md134',1,'']]],
  ['reify_17',['reify',['../refly.html#autotoc_md455',1,'']]],
  ['reify_20reflect_18',['Reify / Reflect',['../refly.html#autotoc_md454',1,'']]],
  ['relies_20on_19',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md166',1,'']]],
  ['rem_20',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md196',1,'']]],
  ['remove_5fdbg_5frepl_21',['remove_dbg_repl',['../refly.html#autotoc_md467',1,'']]],
  ['remove_5fdouble_5fsyncs_22',['remove_double_syncs',['../gpu.html#autotoc_md365',1,'']]],
  ['repeat_23',['repeat',['../tensor.html#autotoc_md512',1,'']]],
  ['repeat_5fimpl_24',['repeat_impl',['../tensor.html#autotoc_md574',1,'']]],
  ['repeat_5fmap_25',['repeat_map',['../tensor.html#autotoc_md573',1,'']]],
  ['reset_20between_20iterations_26',['Reset Between Iterations',['../phases.html#autotoc_md93',1,'']]],
  ['reshape_27',['reshape',['../tensor.html#autotoc_md513',1,'']]],
  ['reshape_5fimpl_28',['reshape_impl',['../tensor.html#autotoc_md576',1,'']]],
  ['reshape_5fmap_29',['reshape_map',['../tensor.html#autotoc_md575',1,'']]],
  ['restrictions_30',['Restrictions',['../phases.html#autotoc_md102',1,'']]],
  ['results_31',['Analysis Results',['../phases.html#autotoc_md96',1,'']]],
  ['ret_5fwrap_32',['ret_wrap',['../compile.html#autotoc_md295',1,'']]],
  ['rewriter_33',['Rewriter',['../rewriting.html#rewriter',1,'']]],
  ['rewriter_20vs_20varrewriter_34',['Rewriter vs. VarRewriter',['../rewriting.html#autotoc_md163',1,'']]],
  ['rewrites_35',['Rewrites',['../phases.html#autotoc_md99',1,'Deferred Rewrites'],['../rewriting.html#autotoc_md158',1,'Mutable Rewrites']]],
  ['rewriting_36',['Rewriting',['../rewriting.html',1,'']]],
  ['right_20base_20class_37',['Choosing the Right Base Class',['../phases.html#autotoc_md117',1,'']]],
  ['ring_38',['Ring',['../btensor.html#autotoc_md223',1,'Ring'],['../tensor.html#autotoc_md488',1,'Ring']]],
  ['rollback_39',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md171',1,'']]],
  ['roots_40',['Roots',['../phases.html#autotoc_md98',1,'Roots'],['../phases.html#autotoc_md104',1,'Roots']]],
  ['roughly_20performance_20parity_41',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md183',1,'']]],
  ['round_42',['round',['../math.html#autotoc_md391',1,'']]],
  ['rrt_43',['rrt',['../math.html#autotoc_md398',1,'']]],
  ['rt_44',['rt',['../math.html#autotoc_md386',1,'']]],
  ['running_45',['Running',['../playground.html#autotoc_md126',1,'']]],
  ['runtime_20wrappers_46',['Runtime Wrappers',['../plugins.html#plugin_runtime',1,'']]],
  ['rust_47',['What about Rust?',['../md_docs_2why-cpp.html#autotoc_md182',1,'']]],
  ['rust_20genuinely_20wins_48',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md184',1,'']]],
  ['rust_20would_20land_20at_20roughly_20performance_20parity_49',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md183',1,'']]],
  ['rwbase_50',['RWBase',['../phases.html#phases_rwbase',1,'']]],
  ['rwphase_51',['RWPhase',['../phases.html#phases_rwphase',1,'']]]
];
