var searchData=
[
  ['f_0',['F',['../math.html#autotoc_md362',1,'']]],
  ['fastest_5faxis_1',['fastest_axis',['../tensor.html#autotoc_md518',1,'']]],
  ['field_20names_20of_20sigmas_2',['Field Names of Sigmas',['../langref.html#field',1,'']]],
  ['files_20and_20imports_3',['Files and Imports',['../langref.html#module',1,'']]],
  ['first_20last_4',['first / last',['../vec.html#autotoc_md598',1,'']]],
  ['first_20steps_5',['First Steps',['../python.html#autotoc_md124',1,'']]],
  ['fixed_20point_20iteration_6',['Sparse Fixed-Point Iteration',['../phases.html#autotoc_md85',1,'']]],
  ['fixed_20points_7',['Fixed Points',['../phases.html#autotoc_md98',1,'']]],
  ['flip_8',['flip',['../tensor.html#autotoc_md492',1,'']]],
  ['flip_5fimpl_9',['flip_impl',['../tensor.html#autotoc_md550',1,'']]],
  ['flip_5fmap_10',['flip_map',['../tensor.html#autotoc_md549',1,'']]],
  ['floordiv_20rem_11',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md180',1,'']]],
  ['fold_12',['fold',['../vec.html#autotoc_md594',1,'']]],
  ['for_13',['For',['../affine.html#autotoc_md174',1,'']]],
  ['for_20built_20ins_14',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['forms_15',['Literals and Basic Forms',['../langref.html#lit',1,'']]],
  ['fort_16',['ForT',['../btensor.html#autotoc_md227',1,'']]],
  ['four_20way_20sum_20type_20in_20one_20machine_20word_17',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md152',1,'']]],
  ['free_18',['free',['../mem.html#autotoc_md394',1,'']]],
  ['free_20asyn_19',['free(block) / free(asyn)',['../gpu.html#autotoc_md333',1,'']]],
  ['free_20block_20free_20asyn_20',['free(block) / free(asyn)',['../gpu.html#autotoc_md333',1,'']]],
  ['free_20variables_21',['Free Variables',['../dev.html#free_vars',1,'']]],
  ['fresh_22',['fresh',['../mem.html#autotoc_md390',1,'']]],
  ['function_20types_23',['Function Types',['../langref.html#autotoc_md74',1,'']]],
  ['functions_20and_20continuations_24',['Functions and Continuations',['../langref.html#autotoc_md67',1,'']]],
  ['functions_20and_20types_25',['Summary: Functions and Types',['../langref.html#autotoc_md70',1,'']]],
  ['further_20casts_26',['Further Casts',['../dev.html#autotoc_md47',1,'']]],
  ['fuse_5ftensor_27',['fuse_tensor',['../tensor.html#autotoc_md582',1,'']]]
];
