var searchData=
[
  ['m⁠im_0',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md113',1,'']]],
  ['m⁠im_20coding_20style_1',['M⁠im Coding Style',['../coding.html#autotoc_md22',1,'']]],
  ['m_2',['M',['../mem.html#memM',1,'']]],
  ['machine_20word_3',['&lt;span class=&quot;tt&quot;&gt;Patricia::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md152',1,'']]],
  ['malloc_4',['malloc',['../mem.html#autotoc_md388',1,'']]],
  ['map_5',['Set / Map',['../ord.html#autotoc_md419',1,'']]],
  ['map_6',['map',['../affine.html#autotoc_md181',1,'map'],['../tensor.html#autotoc_md494',1,'map']]],
  ['map_20lookups_7',['Pointers become map lookups',['../md_docs_2why-cpp.html#autotoc_md156',1,'']]],
  ['map_20reduce_8',['Map Reduce',['../btensor.html#autotoc_md208',1,'Map-Reduce'],['../tensor.html#autotoc_md475',1,'Map-Reduce']]],
  ['map_5fimpl_9',['map_impl',['../tensor.html#autotoc_md529',1,'']]],
  ['map_5freduce_10',['map_reduce',['../btensor.html#autotoc_md210',1,'map_reduce'],['../tensor.html#autotoc_md479',1,'map_reduce']]],
  ['map_5freduce_5fpost_11',['map_reduce_post',['../btensor.html#autotoc_md211',1,'map_reduce_post'],['../tensor.html#autotoc_md477',1,'map_reduce_post']]],
  ['markdown_20page_12',['Generated Markdown Page',['../plugins.html#autotoc_md117',1,'']]],
  ['markdown_20style_13',['Markdown Style',['../coding.html#autotoc_md21',1,'']]],
  ['matching_20axioms_14',['Matching Axioms',['../dev.html#cast_axm',1,'']]],
  ['matching_20ir_15',['Matching IR',['../dev.html#autotoc_md42',1,'']]],
  ['matching_20literals_16',['Matching Literals',['../dev.html#cast_lit',1,'']]],
  ['materialize_17',['materialize',['../tensor.html#autotoc_md512',1,'']]],
  ['math_20plugin_18',['The math Plugin',['../math.html',1,'']]],
  ['mem_20plugin_19',['The mem Plugin',['../mem.html',1,'']]],
  ['mem_5fchecks_20',['mem_checks',['../gpu.html#autotoc_md342',1,'']]],
  ['memory_20operations_21',['Blocking / Async Memory Operations',['../gpu.html#autotoc_md325',1,'']]],
  ['memory_20types_22',['Memory Types',['../gpu.html#autotoc_md312',1,'']]],
  ['meta_23',['Meta',['../regex.html#autotoc_md450',1,'']]],
  ['metadata_24',['Preserving Metadata',['../rewriting.html#autotoc_md143',1,'']]],
  ['mim_25',['Mim',['../index.html#autotoc_md129',1,'✨ A Taste of Mim'],['../index.html#autotoc_md137',1,'🐉 Naming: MimIR vs. Mim']]],
  ['mim_20language_20reference_26',['Mim Language Reference',['../langref.html',1,'']]],
  ['mimir_27',['MimIR',['../index.html#autotoc_md130',1,'💡 Why MimIR?'],['../mimir.html',1,'A Tour of MimIR'],['../index.html',1,'MimIR']]],
  ['mimir_20implemented_20in_20c_28',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['mimir_20picture_29',['The MimIR picture',['../phases.html#autotoc_md106',1,'']]],
  ['mimir_20vs_20mim_30',['🐉 Naming: MimIR vs. Mim',['../index.html#autotoc_md137',1,'']]],
  ['minimal_20examples_31',['Minimal Examples',['../phases.html#autotoc_md112',1,'']]],
  ['mining_32',['Strip-Mining',['../tensor.html#autotoc_md516',1,'']]],
  ['mk_5fsched_33',['mk_sched',['../btensor.html#autotoc_md212',1,'mk_sched'],['../tensor.html#autotoc_md478',1,'mk_sched']]],
  ['mode_34',['Mode',['../core.html#autotoc_md282',1,'Mode'],['../math.html#autotoc_md357',1,'Mode']]],
  ['mode_35',['mode',['../math.html#autotoc_md358',1,'']]],
  ['model_36',['Execution Model',['../phases.html#autotoc_md87',1,'']]],
  ['modifiers_37',['Modifiers',['../langref.html#autotoc_md64',1,'Modifiers'],['../ord.html#autotoc_md429',1,'Modifiers'],['../vec.html#autotoc_md566',1,'Modifiers']]],
  ['module_38',['Generated Python Module',['../plugins.html#autotoc_md116',1,'']]],
  ['modules_39',['Paths and Modules',['../langref.html#path',1,'']]],
  ['move_20out_20of_20the_20node_40',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['mr_5fnest_41',['mr_nest',['../btensor.html#autotoc_md227',1,'']]],
  ['mr_5ftileable_42',['mr_tileable',['../tensor.html#autotoc_md513',1,'']]],
  ['mslot_43',['mslot',['../mem.html#autotoc_md390',1,'']]],
  ['much_20worse_44',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md155',1,'']]],
  ['mul_45',['affine.op.mul',['../affine.html#autotoc_md180',1,'']]],
  ['mul_20ceildiv_20floordiv_20rem_46',['semiop(mul,ceildiv,floordiv,rem)',['../affine.html#autotoc_md179',1,'']]],
  ['must_20move_20out_20of_20the_20node_47',['Caches must move out of the node',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['mutable_20rewrites_48',['Mutable Rewrites',['../rewriting.html#autotoc_md142',1,'']]],
  ['mutables_49',['Mutables',['../dev.html#autotoc_md45',1,'Downcast to Mutables'],['../phases.html#autotoc_md84',1,'Handling of Mutables'],['../dev.html#mut',1,'Immutables vs. Mutables'],['../dev.html#autotoc_md34',1,'Mutables']]]
];
