var searchData=
[
  ['f_0',['%math.F',['../math.html#autotoc_md315',1,'']]],
  ['fastest_5faxis_1',['%tensor.fastest_axis',['../tensor.html#autotoc_md426',1,'']]],
  ['features_2',['Debugging Features',['../cli.html#clidebug',1,'']]],
  ['field_20names_20of_20sigmas_3',['Field Names of Sigmas',['../langref.html#autotoc_md68',1,'']]],
  ['first_20class_20functions_4',['Schedules as first-class functions',['../tensor.html#autotoc_md430',1,'']]],
  ['first_20class_20ir_20values_5',['Loop nests as first-class IR values',['../btensor.html#autotoc_md200',1,'']]],
  ['first_20steps_6',['First Steps',['../python.html#autotoc_md117',1,'']]],
  ['first_20vec_20last_7',['%vec.first / %vec.last',['../vec.html#autotoc_md465',1,'']]],
  ['fixed_20point_20iteration_8',['Sparse Fixed-Point Iteration',['../phases.html#autotoc_md77',1,'']]],
  ['fixed_20points_9',['Fixed Points',['../phases.html#autotoc_md90',1,'']]],
  ['flip_10',['%tensor.flip',['../tensor.html#autotoc_md434',1,'']]],
  ['floordiv_20mod_11',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md173',1,'']]],
  ['fold_12',['%vec.fold',['../vec.html#autotoc_md461',1,'']]],
  ['for_13',['%affine.For',['../affine.html#autotoc_md167',1,'']]],
  ['for_20built_20ins_14',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['forms_15',['Literals and Basic Forms',['../langref.html#autotoc_md54',1,'']]],
  ['four_20way_20sum_20type_20in_20one_20machine_20word_16',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['free_17',['%mem.free',['../mem.html#autotoc_md345',1,'']]],
  ['free_20asyn_18',['%gpu.free(asyn)',['../gpu.html#autotoc_md295',1,'']]],
  ['free_20block_19',['%gpu.free(block)',['../gpu.html#autotoc_md289',1,'']]],
  ['free_20variables_20',['Free Variables',['../dev.html#free_vars',1,'']]],
  ['fresh_21',['%mem.fresh',['../mem.html#autotoc_md341',1,'']]],
  ['function_20types_22',['Function Types',['../langref.html#autotoc_md64',1,'']]],
  ['functions_23',['Schedules as first-class functions',['../tensor.html#autotoc_md430',1,'']]],
  ['functions_20and_20continuations_24',['Functions and Continuations',['../langref.html#autotoc_md55',1,'']]],
  ['functions_20and_20types_25',['Summary: Functions and Types',['../langref.html#autotoc_md60',1,'']]],
  ['further_20casts_26',['Further Casts',['../dev.html#autotoc_md36',1,'']]]
];
