var searchData=
[
  ['c_20style_0',['C++ Style',['../coding.html#autotoc_md5',1,'']]],
  ['capacity_1',['Capacity',['../ord.html#autotoc_md309',1,'']]],
  ['casts_2',['Further Casts',['../dev.html#autotoc_md30',1,'']]],
  ['cat_3',['%tuple.cat',['../tuple.html#autotoc_md374',1,'']]],
  ['catching_20exceptions_4',['Catching Exceptions',['../coding.html#autotoc_md16',1,'']]],
  ['ceildiv_20floordiv_20mod_5',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md134',1,'']]],
  ['check_6',['%refly.check',['../refly.html#autotoc_md329',1,'']]],
  ['check_5fbot_7',['%refly.check_bot',['../refly.html#autotoc_md328',1,'']]],
  ['choosing_20the_20right_20base_20class_8',['Choosing the Right Base Class',['../phases.html#autotoc_md88',1,'']]],
  ['class_9',['Choosing the Right Base Class',['../phases.html#autotoc_md88',1,'']]],
  ['classical_20picture_10',['The classical picture',['../phases.html#autotoc_md83',1,'']]],
  ['cleanup_11',['Cleanup',['../phases.html#autotoc_md72',1,'']]],
  ['clos_20plugin_12',['The clos Plugin',['../clos.html',1,'']]],
  ['closedmutphase_13',['ClosedMutPhase',['../phases.html#phases_closed_mut_phase',1,'']]],
  ['closure_20attribute_14',['Closure Attribute',['../clos.html#autotoc_md155',1,'']]],
  ['cls_15',['%regex.cls.*',['../regex.html#autotoc_md345',1,'']]],
  ['cmake_20style_16',['CMake Style',['../coding.html#autotoc_md8',1,'']]],
  ['cmp_17',['%math.cmp',['../math.html#autotoc_md248',1,'']]],
  ['coding_20style_18',['Coding Style',['../coding.html#autotoc_md4',1,'Coding Style'],['../coding.html#autotoc_md10',1,'M⁠im Coding Style']]],
  ['command_20line_20reference_19',['Command-Line Reference',['../cli.html',1,'']]],
  ['comments_20',['Comments',['../langref.html#autotoc_md46',1,'']]],
  ['community_21',['💬 Community',['../index.html#autotoc_md116',1,'']]],
  ['compilation_20pipelines_20in_20m⁠im_22',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md91',1,'']]],
  ['compile_20cond_23',['%compile.cond',['../compile.html#autotoc_md163',1,'']]],
  ['compile_20is_5floaded_24',['%compile.is_loaded',['../compile.html#autotoc_md161',1,'']]],
  ['compile_20named_25',['%compile.named',['../compile.html#autotoc_md162',1,'']]],
  ['compile_20phase_26',['%compile.Phase',['../compile.html#autotoc_md159',1,'']]],
  ['compile_20phases_27',['%compile.phases',['../compile.html#autotoc_md165',1,'']]],
  ['compile_20plugin_28',['The compile Plugin',['../compile.html',1,'']]],
  ['cond_29',['%compile.cond',['../compile.html#autotoc_md163',1,'']]],
  ['conditional_20breakpoints_30',['Conditional Breakpoints',['../coding.html#autotoc_md15',1,'']]],
  ['conj_31',['%regex.conj',['../regex.html#autotoc_md338',1,'']]],
  ['const_32',['%matrix.const',['../matrix.html#autotoc_md260',1,'']]],
  ['const_5fidx_33',['%demo.const_idx',['../demo.html#autotoc_md194',1,'']]],
  ['constant_34',['%affine.constant',['../affine.html#autotoc_md131',1,'']]],
  ['constructors_35',['Constructors',['../compile.html#autotoc_md164',1,'Constructors'],['../option.html#autotoc_md295',1,'Constructors'],['../ord.html#autotoc_md306',1,'Constructors']]],
  ['contains_36',['contains',['../ord.html#autotoc_md314',1,'%ord.contains'],['../tuple.html#autotoc_md375',1,'%tuple.contains']]],
  ['context_37',['Context',['../gpu.html#autotoc_md202',1,'']]],
  ['continuations_38',['Functions and Continuations',['../langref.html#autotoc_md49',1,'']]],
  ['contributing_20debugging_39',['Contributing &amp;amp; Debugging',['../coding.html',1,'']]],
  ['contributor_20quick_20start_40',['Contributor Quick Start',['../coding.html#building',1,'']]],
  ['conv_41',['conv',['../core.html#autotoc_md183',1,'%core.conv'],['../math.html#autotoc_md250',1,'%math.conv']]],
  ['conversions_42',['Conversions',['../core.html#autotoc_md182',1,'']]],
  ['copy_5fto_5fdevice_20asyn_43',['%gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md219',1,'']]],
  ['copy_5fto_5fdevice_20block_44',['%gpu.copy_to_device(block)',['../gpu.html#autotoc_md213',1,'']]],
  ['copy_5fto_5fhost_20asyn_45',['%gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md220',1,'']]],
  ['copy_5fto_5fhost_20block_46',['%gpu.copy_to_host(block)',['../gpu.html#autotoc_md214',1,'']]],
  ['core_20abs_47',['%core.abs',['../core.html#autotoc_md181',1,'']]],
  ['core_20bit1_48',['core bit1',['../core.html#autotoc_md174',1,'%core.bit1'],['../todo.html#_todo000001',1,'%core.bit1']]],
  ['core_20bit2_49',['core bit2',['../core.html#autotoc_md175',1,'%core.bit2'],['../todo.html#_todo000002',1,'%core.bit2']]],
  ['core_20bitcast_50',['%core.bitcast',['../core.html#autotoc_md184',1,'']]],
  ['core_20conv_51',['%core.conv',['../core.html#autotoc_md183',1,'']]],
  ['core_20div_52',['%core.div',['../core.html#autotoc_md178',1,'']]],
  ['core_20extrema_53',['%core.extrema',['../core.html#autotoc_md180',1,'']]],
  ['core_20icmp_54',['%core.icmp',['../core.html#autotoc_md179',1,'']]],
  ['core_20icmp_20xygle_20eq_55',['%core.icmp.xYgLE (eq)',['../autodiff.html#autotoc_md150',1,'']]],
  ['core_20idx_56',['%core.idx',['../core.html#autotoc_md173',1,'']]],
  ['core_20nat_57',['%core.nat',['../core.html#autotoc_md169',1,'']]],
  ['core_20ncmp_58',['%core.ncmp',['../core.html#autotoc_md170',1,'']]],
  ['core_20pe_59',['%core.pe',['../core.html#autotoc_md187',1,'']]],
  ['core_20plugin_60',['The core Plugin',['../core.html',1,'']]],
  ['core_20select_61',['%core.select',['../core.html#autotoc_md188',1,'']]],
  ['core_20shr_62',['%core.shr',['../core.html#autotoc_md176',1,'']]],
  ['core_20trait_63',['%core.trait',['../core.html#autotoc_md186',1,'']]],
  ['core_20wrap_64',['%core.wrap',['../core.html#autotoc_md177',1,'']]],
  ['core_20wrap_20add_65',['%core.wrap.add',['../autodiff.html#autotoc_md151',1,'']]],
  ['core_20wrap_20mul_66',['%core.wrap.mul',['../autodiff.html#autotoc_md152',1,'']]],
  ['cps_67',['SSA via CPS',['../mimir.html#mimir_cps',1,'']]],
  ['cps_20cps2ds_68',['%cps.cps2ds',['../cps.html#autotoc_md191',1,'']]],
  ['cps_20plugin_69',['The CPS Plugin',['../cps.html',1,'']]],
  ['cps2ds_70',['%cps.cps2ds',['../cps.html#autotoc_md191',1,'']]],
  ['create_71',['%ord.create',['../ord.html#autotoc_md308',1,'']]],
  ['create_20a_20new_20in_20tree_20plugin_72',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md94',1,'']]],
  ['create_20a_20third_20party_20plugin_73',['Create a Third-Party Plugin',['../plugins.html#autotoc_md95',1,'']]],
  ['current_20scope_74',['Current Scope',['../python.html#autotoc_md104',1,'']]]
];
