var searchData=
[
  ['w_20o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md351',1,'']]],
  ['w_20side_20effects_1',['Operations w/ Side Effects',['../mem.html#autotoc_md341',1,'']]],
  ['way_20sum_20type_20in_20one_20machine_20word_2',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['what_20about_20rust_3',['What about Rust?',['../md_docs_2why-cpp.html#autotoc_md159',1,'']]],
  ['what_20the_20c_20implementation_20actually_20relies_20on_4',['What the C++ implementation actually relies on',['../md_docs_2why-cpp.html#autotoc_md143',1,'']]],
  ['where_20rust_20genuinely_20wins_5',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md161',1,'']]],
  ['why_20idiomatic_20style_20is_20much_20worse_6',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md149',1,'']]],
  ['why_20is_20mimir_20implemented_20in_20c_7',['Why is MimIR implemented in C++?',['../md_docs_2why-cpp.html',1,'']]],
  ['why_20it_20defeats_20the_20purpose_8',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md158',1,'']]],
  ['why_20mimir_9',['💡 Why MimIR?',['../index.html#autotoc_md123',1,'']]],
  ['why_20the_20guard_20exists_20at_20all_10',['Why the guard exists at all',['../phases.html#autotoc_md96',1,'']]],
  ['why_20this_20is_20hard_20elsewhere_11',['Why this is hard elsewhere',['../phases.html#autotoc_md99',1,'']]],
  ['wins_12',['Where Rust genuinely wins',['../md_docs_2why-cpp.html#autotoc_md161',1,'']]],
  ['with_20arena_20rollback_13',['Speculative construction with arena rollback',['../md_docs_2why-cpp.html#autotoc_md148',1,'']]],
  ['with_20indices_14',['Working with Indices',['../dev.html#autotoc_md40',1,'']]],
  ['with_20subtags_15',['With Subtags',['../dev.html#autotoc_md38',1,'']]],
  ['with_5fstreams_16',['%gpu.with_streams',['../gpu.html#autotoc_md287',1,'']]],
  ['without_20dominance_17',['without Dominance',['../index.html#autotoc_md129',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['without_20subtags_18',['Without Subtags',['../dev.html#autotoc_md37',1,'']]],
  ['word_19',['&lt;span class=&quot;tt&quot;&gt;Sets::Set&lt;/span&gt; — a four-way sum type in one machine word',['../md_docs_2why-cpp.html#autotoc_md145',1,'']]],
  ['work_20item_20synchronization_20',['Work-Item Synchronization',['../gpu.html#autotoc_md305',1,'']]],
  ['working_20with_20indices_21',['Working with Indices',['../dev.html#autotoc_md40',1,'']]],
  ['worse_22',['Why idiomatic style is much worse',['../md_docs_2why-cpp.html#autotoc_md149',1,'']]],
  ['worse_20not_20better_23',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md162',1,'']]],
  ['would_20land_20at_20roughly_20performance_20parity_24',['Rust would land at roughly performance parity',['../md_docs_2why-cpp.html#autotoc_md160',1,'']]],
  ['wrap_25',['%core.wrap',['../core.html#autotoc_md253',1,'']]],
  ['wrappers_26',['Runtime Wrappers',['../plugins.html#plugin_runtime',1,'']]],
  ['write_27',['%buffer.write',['../buffer.html#autotoc_md216',1,'']]]
];
