var searchData=
[
  ['effects_0',['Effects',['../mem.html#autotoc_md308',1,'Operations w/ Side Effects'],['../mem.html#autotoc_md318',1,'Operations w/o Side Effects']]],
  ['elsewhere_1',['Why this is hard elsewhere',['../phases.html#autotoc_md98',1,'']]],
  ['embedded_20python_20dsl_2',['Embedded Python DSL',['../python.html#autotoc_md119',1,'']]],
  ['emit_3',['emit',['../ll.html#autotoc_md281',1,'%ll.emit'],['../ll_nvptx.html#autotoc_md284',1,'%ll_nvptx.emit']]],
  ['empty_4',['%regex.empty',['../regex.html#autotoc_md382',1,'']]],
  ['equiv_5',['%refly.equiv',['../refly.html#autotoc_md363',1,'']]],
  ['er_6',['%math.er',['../math.html#autotoc_md294',1,'']]],
  ['error_20handling_20helpers_7',['Error Handling Helpers',['../python.html#autotoc_md117',1,'']]],
  ['evaluation_8',['Partial Evaluation',['../dev.html#autotoc_md25',1,'']]],
  ['example_9',['Example',['../coding.html#autotoc_md8',1,'']]],
  ['example_3a_20demo_20plugin_10',['Example: demo Plugin',['../plugins.html#autotoc_md106',1,'']]],
  ['example_3a_20sccp_11',['Example: SCCP',['../phases.html#autotoc_md93',1,'']]],
  ['examples_12',['Minimal Examples',['../phases.html#autotoc_md103',1,'']]],
  ['exceptions_13',['Catching Exceptions',['../coding.html#autotoc_md17',1,'']]],
  ['execution_20model_14',['Execution Model',['../phases.html#autotoc_md78',1,'']]],
  ['existing_20in_20tree_20plugin_15',['Extract an Existing In-Tree Plugin',['../plugins.html#autotoc_md113',1,'']]],
  ['exists_20at_20all_16',['Why the guard exists at all',['../phases.html#autotoc_md95',1,'']]],
  ['exp_17',['%math.exp',['../math.html#autotoc_md293',1,'']]],
  ['expressions_18',['Expressions',['../langref.html#expr',1,'Expressions'],['../langref.html#autotoc_md61',1,'Expressions']]],
  ['extending_20the_20bindings_19',['Extending the Bindings',['../python.html#python_extending',1,'']]],
  ['extract_20an_20existing_20in_20tree_20plugin_20',['Extract an Existing In-Tree Plugin',['../plugins.html#autotoc_md113',1,'']]],
  ['extrema_21',['extrema',['../core.html#autotoc_md229',1,'%core.extrema'],['../math.html#autotoc_md289',1,'%math.extrema']]]
];
