var searchData=
[
  ['scan_0',['%vec.scan',['../vec.html#autotoc_md371',1,'']]],
  ['scanning_1',['Scanning',['../vec.html#autotoc_md370',1,'']]],
  ['sccp_2',['Example: SCCP',['../phases.html#autotoc_md74',1,'']]],
  ['scope_3',['Current Scope',['../python.html#autotoc_md94',1,'']]],
  ['scoped_20substitution_4',['Scoped Substitution',['../rewriting.html#autotoc_md112',1,'']]],
  ['scoping_5',['Scoping',['../langref.html#autotoc_md58',1,'Scoping'],['../rewriting.html#autotoc_md108',1,'Scoping']]],
  ['sea_20of_20nodes_6',['🌊 Sea of Nodes',['../index.html#autotoc_md102',1,'']]],
  ['secondary_20terminals_7',['Secondary Terminals',['../langref.html#autotoc_md43',1,'']]],
  ['select_8',['select',['../core.html#autotoc_md179',1,'%core.select'],['../tensor.html#autotoc_md358',1,'%tensor.select']]],
  ['semiop_20mul_20ceildiv_20floordiv_20mod_9',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md123',1,'']]],
  ['sequences_20unions_20and_20matching_10',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md50',1,'']]],
  ['set_11',['tensor.set',['../tensor.html#autotoc_md345',1,'']]],
  ['set_20ord_20map_12',['%ord.Set / %ord.Map',['../ord.html#autotoc_md293',1,'']]],
  ['sgn_13',['%math.sgn',['../math.html#autotoc_md235',1,'']]],
  ['shape_14',['Shape',['../dev.html#autotoc_md38',1,'Shape'],['../phases.html#autotoc_md63',1,'Typical Shape'],['../phases.html#autotoc_md71',1,'Typical Shape'],['../phases.html#autotoc_md72',1,'Typical Shape'],['../phases.html#autotoc_md73',1,'Typical Shape']]],
  ['shape_15',['%matrix.shape',['../matrix.html#autotoc_md241',1,'']]],
  ['shr_16',['%core.shr',['../core.html#autotoc_md167',1,'']]],
  ['side_20effects_17',['Side Effects',['../mem.html#autotoc_md260',1,'Operations w/ Side Effects'],['../mem.html#autotoc_md269',1,'Operations w/o Side Effects']]],
  ['sigmas_18',['Field Names of Sigmas',['../langref.html#autotoc_md61',1,'']]],
  ['size_19',['%ord.size',['../ord.html#autotoc_md298',1,'']]],
  ['slf_20',['%math.slf',['../math.html#autotoc_md234',1,'']]],
  ['slot_21',['%mem.slot',['../mem.html#autotoc_md265',1,'']]],
  ['some_22',['%option.some',['../option.html#autotoc_md284',1,'']]],
  ['spaces_23',['Address Spaces',['../gpu.html#autotoc_md188',1,'']]],
  ['ssa_20without_20dominance_24',['🪾 SSA without Dominance',['../index.html#autotoc_md103',1,'']]],
  ['stages_25',['Stages',['../autodiff.html#autotoc_md135',1,'Stages'],['../gpu.html#autotoc_md215',1,'Stages'],['../mem.html#autotoc_md271',1,'Stages'],['../refly.html#autotoc_md321',1,'Stages']]],
  ['standalone_20third_20party_20builds_26',['Standalone Third-Party Builds',['../plugins.html#autotoc_md88',1,'']]],
  ['start_27',['Start',['../index.html#autotoc_md98',1,'🚀 Quick Start'],['../coding.html#building',1,'Contributor Quick Start']]],
  ['steps_28',['First Steps',['../python.html#autotoc_md91',1,'']]],
  ['store_29',['%mem.store',['../mem.html#autotoc_md262',1,'']]],
  ['stream_5fdeinit_30',['%gpu.stream_deinit',['../gpu.html#autotoc_md195',1,'']]],
  ['stream_5finit_31',['%gpu.stream_init',['../gpu.html#autotoc_md194',1,'']]],
  ['stream_5fsync_32',['%gpu.stream_sync',['../gpu.html#autotoc_md196',1,'']]],
  ['streams_33',['Streams',['../gpu.html#autotoc_md191',1,'Streams'],['../gpu.html#autotoc_md193',1,'Streams']]],
  ['structure_34',['Lexical Structure',['../langref.html#lex',1,'']]],
  ['style_35',['Style',['../coding.html#autotoc_md5',1,'C++ Style'],['../coding.html#autotoc_md8',1,'CMake Style'],['../coding.html#autotoc_md4',1,'Coding Style'],['../coding.html#autotoc_md6',1,'Doxygen Style'],['../coding.html#autotoc_md10',1,'M⁠im Coding Style'],['../coding.html#autotoc_md9',1,'Markdown Style']]],
  ['style_20plugin_36',['The direct style Plugin',['../direct.html',1,'']]],
  ['sub_37',['%affine.op(add,sub)',['../affine.html#autotoc_md121',1,'']]],
  ['substitution_38',['Scoped Substitution',['../rewriting.html#autotoc_md112',1,'']]],
  ['subtags_39',['Subtags',['../dev.html#autotoc_md32',1,'With Subtags'],['../dev.html#autotoc_md31',1,'Without Subtags']]],
  ['sum_40',['sum',['../matrix.html#autotoc_md253',1,'']]],
  ['summary_41',['Summary',['../dev.html#autotoc_md29',1,'Summary'],['../dev.html#autotoc_md33',1,'Summary'],['../dev.html#autotoc_md39',1,'Summary'],['../phases.html#autotoc_md82',1,'Summary']]],
  ['summary_3a_20functions_20and_20types_42',['Summary: Functions and Types',['../langref.html#autotoc_md53',1,'']]],
  ['sync_5fwork_5fitems_43',['%gpu.sync_work_items',['../gpu.html#autotoc_md213',1,'']]],
  ['synced_5fscope_44',['%gpu.synced_scope',['../gpu.html#autotoc_md214',1,'']]],
  ['synchronization_45',['Work-Item Synchronization',['../gpu.html#autotoc_md212',1,'']]],
  ['syntax_20highlighting_46',['Syntax Highlighting',['../coding.html#autotoc_md11',1,'']]]
];
