var searchData=
[
  ['icmp_0',['%core.icmp',['../core.html#autotoc_md195',1,'']]],
  ['icmp_20xygle_20eq_1',['%core.icmp.xYgLE (eq)',['../autodiff.html#autotoc_md153',1,'']]],
  ['id_2',['%affine.id',['../affine.html#autotoc_md137',1,'']]],
  ['idx_3',['%core.idx',['../core.html#autotoc_md189',1,'']]],
  ['immutables_4',['Immutables',['../dev.html#autotoc_md27',1,'Downcast to Immutables'],['../dev.html#autotoc_md20',1,'Immutables']]],
  ['immutables_20vs_20mutables_5',['Immutables vs. Mutables',['../dev.html#mut',1,'']]],
  ['in_20m⁠im_6',['Compilation Pipelines in M⁠im',['../phases.html#autotoc_md91',1,'']]],
  ['in_20tree_20plugin_7',['In Tree Plugin',['../plugins.html#autotoc_md94',1,'Create a New In-Tree Plugin'],['../plugins.html#autotoc_md97',1,'Extract an Existing In-Tree Plugin']]],
  ['index_8',['%affine.index',['../affine.html#autotoc_md130',1,'']]],
  ['index_20operations_9',['Affine Index Operations',['../affine.html#autotoc_md129',1,'']]],
  ['indices_10',['Working with Indices',['../dev.html#autotoc_md34',1,'']]],
  ['init_11',['init',['../buffer.html#autotoc_md163',1,'%buffer.init'],['../gpu.html#autotoc_md219',1,'%gpu.init'],['../ord.html#autotoc_md317',1,'%ord.init']]],
  ['innovations_12',['🔥 Key Innovations',['../index.html#autotoc_md111',1,'']]],
  ['ins_13',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['insert_14',['%ord.insert',['../ord.html#autotoc_md326',1,'']]],
  ['inspect_15',['Inspect',['../refly.html#autotoc_md332',1,'']]],
  ['install_20optional_16',['📦 Install (Optional)',['../index.html#autotoc_md110',1,'']]],
  ['integer_20operations_17',['Integer Operations',['../core.html#autotoc_md187',1,'']]],
  ['ir_18',['Matching IR',['../dev.html#autotoc_md25',1,'']]],
  ['is_20hard_20elsewhere_19',['Why this is hard elsewhere',['../phases.html#autotoc_md85',1,'']]],
  ['is_5fempty_20',['%ord.is_empty',['../ord.html#autotoc_md321',1,'']]],
  ['is_5ffinite_21',['%math.is_finite',['../math.html#autotoc_md265',1,'']]],
  ['is_5floaded_22',['%compile.is_loaded',['../compile.html#autotoc_md177',1,'']]],
  ['is_5fsome_23',['%option.is_some',['../option.html#autotoc_md309',1,'']]],
  ['is_5funique_24',['%vec.is_unique',['../vec.html#autotoc_md404',1,'']]],
  ['item_20synchronization_25',['Work-Item Synchronization',['../gpu.html#autotoc_md240',1,'']]],
  ['iterating_20over_20the_20program_26',['Iterating over the Program',['../dev.html#autotoc_md40',1,'']]],
  ['iteration_27',['Iteration',['../phases.html#autotoc_md70',1,'Fixed-Point Iteration'],['../mimir.html#mimir_iter',1,'Polymorphic Iteration']]],
  ['iterations_28',['Reset Between Iterations',['../phases.html#autotoc_md71',1,'']]],
  ['iterators_29',['Iterators',['../vec.html#autotoc_md397',1,'']]]
];
