var searchData=
[
  ['ballpark_20estimates_0',['Ballpark estimates',['../md_docs_2why-cpp.html#autotoc_md149',1,'']]],
  ['base_20class_1',['Choosing the Right Base Class',['../phases.html#autotoc_md110',1,'']]],
  ['basic_20forms_2',['Literals and Basic Forms',['../langref.html#lit',1,'']]],
  ['basics_3',['Basics',['../dev.html#autotoc_md31',1,'']]],
  ['become_20map_20lookups_4',['Pointers become map lookups',['../md_docs_2why-cpp.html#autotoc_md157',1,'']]],
  ['better_5',['The plugin story is worse, not better',['../md_docs_2why-cpp.html#autotoc_md169',1,'']]],
  ['between_20iterations_6',['Reset Between Iterations',['../phases.html#autotoc_md86',1,'']]],
  ['binary_7',['binary',['../tensor.html#autotoc_md456',1,'']]],
  ['bindable_20types_8',['Bindable Types',['../python.html#python_bindable',1,'']]],
  ['binders_9',['Binders',['../dev.html#autotoc_md35',1,'Binders'],['../mimir.html#mimir_scopeless',1,'Scopeless Binders']]],
  ['bindings_10',['Bindings',['../python.html#python_extending',1,'Extending the Bindings'],['../python.html',1,'Python Bindings']]],
  ['bit1_11',['core.bit1',['../core.html#autotoc_md259',1,'']]],
  ['bit2_12',['core.bit2',['../core.html#autotoc_md260',1,'']]],
  ['bitcast_13',['core.bitcast',['../core.html#autotoc_md269',1,'']]],
  ['block_20gpu_20alloc_20asyn_14',['gpu.alloc(block) / gpu.alloc(asyn)',['../gpu.html#autotoc_md299',1,'']]],
  ['block_20gpu_20alloc_5fcopy_20asyn_15',['gpu.alloc_copy(block) / gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md303',1,'']]],
  ['block_20gpu_20copy_5fto_5fdevice_20asyn_16',['gpu.copy_to_device(block) / gpu.copy_to_device(asyn)',['../gpu.html#autotoc_md301',1,'']]],
  ['block_20gpu_20copy_5fto_5fhost_20asyn_17',['gpu.copy_to_host(block) / gpu.copy_to_host(asyn)',['../gpu.html#autotoc_md302',1,'']]],
  ['block_20gpu_20free_20asyn_18',['gpu.free(block) / gpu.free(asyn)',['../gpu.html#autotoc_md300',1,'']]],
  ['blocking_20async_20memory_20operations_19',['Blocking / Async Memory Operations',['../gpu.html#autotoc_md298',1,'']]],
  ['blocks_20',['Local Declaration Blocks',['../langref.html#autotoc_md68',1,'']]],
  ['bmm_21',['bmm',['../tensor.html#autotoc_md449',1,'']]],
  ['bootstrapping_22',['Bootstrapping',['../phases.html#autotoc_md90',1,'']]],
  ['breakpoints_23',['Breakpoints',['../coding.html#autotoc_md27',1,'Conditional Breakpoints'],['../coding.html#autotoc_md30',1,'Triggering Breakpoints']]],
  ['broadcast_24',['broadcast',['../btensor.html#autotoc_md213',1,'broadcast'],['../tensor.html#autotoc_md452',1,'broadcast']]],
  ['broadcast_5fin_5fdim_25',['broadcast_in_dim',['../tensor.html#autotoc_md453',1,'']]],
  ['btensor_20plugin_26',['The btensor Plugin',['../btensor.html',1,'']]],
  ['buf_27',['buffer.Buf',['../buffer.html#autotoc_md221',1,'']]],
  ['buf_5falloc_5fcopy_28',['gpu.buf_alloc_copy',['../gpu.html#autotoc_md305',1,'']]],
  ['buf_5fcopy_5fto_5fhost_29',['gpu.buf_copy_to_host',['../gpu.html#autotoc_md306',1,'']]],
  ['buffer_20alloc_30',['buffer.alloc',['../buffer.html#autotoc_md223',1,'']]],
  ['buffer_20buf_31',['buffer.Buf',['../buffer.html#autotoc_md221',1,'']]],
  ['buffer_20copy_32',['buffer.copy',['../buffer.html#autotoc_md229',1,'']]],
  ['buffer_20init_33',['buffer.init',['../buffer.html#autotoc_md226',1,'']]],
  ['buffer_20lit_34',['buffer.lit',['../buffer.html#autotoc_md227',1,'']]],
  ['buffer_20lower_5fptr_35',['buffer.lower_ptr',['../buffer.html#autotoc_md231',1,'']]],
  ['buffer_20operations_36',['Buffer Operations',['../gpu.html#autotoc_md304',1,'']]],
  ['buffer_20plugin_37',['The buffer Plugin',['../buffer.html',1,'']]],
  ['buffer_20read_38',['buffer.read',['../buffer.html#autotoc_md224',1,'']]],
  ['buffer_20shape_39',['buffer.shape',['../buffer.html#autotoc_md228',1,'']]],
  ['buffer_20write_40',['buffer.write',['../buffer.html#autotoc_md225',1,'']]],
  ['bufptr_41',['clos.BufPtr',['../clos.html#autotoc_md234',1,'']]],
  ['builds_42',['Standalone Third-Party Builds',['../plugins.html#autotoc_md122',1,'']]],
  ['built_20ins_43',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['builtin_20types_44',['Kinds and Builtin Types',['../langref.html#autotoc_md64',1,'']]]
];
