var searchData=
[
  ['dark_20mode_0',['Dark mode',['../playground.html#autotoc_md134',1,'']]],
  ['dbg_1',['dbg',['../refly.html#autotoc_md488',1,'']]],
  ['debugging_2',['Debugging',['../coding.html',1,'Contributing &amp; Debugging'],['../coding.html#autotoc_md24',1,'Debugging']]],
  ['declaration_20blocks_3',['Local Declaration Blocks',['../langref.html#autotoc_md69',1,'']]],
  ['declarations_4',['Declarations',['../langref.html#decl',1,'Declarations'],['../langref.html#autotoc_md71',1,'Declarations']]],
  ['default_20pipeline_5',['The default pipeline',['../opt.html#autotoc_md452',1,'']]],
  ['defeats_20the_20purpose_6',['The escape hatch, and why it defeats the purpose',['../md_docs_2why-cpp.html#autotoc_md188',1,'']]],
  ['deferred_20rewrites_7',['Deferred Rewrites',['../phases.html#autotoc_md102',1,'']]],
  ['definitions_8',['Other Definitions',['../mimir.html#autotoc_md90',1,'']]],
  ['defs_20are_20placed_20in_20them_9',['Arenas, and how &lt;span class=&quot;tt&quot;&gt;Def&lt;/span&gt;s are placed in them',['../md_docs_2why-cpp.html#autotoc_md177',1,'']]],
  ['deinit_10',['deinit',['../gpu.html#autotoc_md366',1,'']]],
  ['delinearize_11',['delinearize',['../affine.html#autotoc_md223',1,'']]],
  ['demo_20plugin_12',['demo Plugin',['../plugins.html#autotoc_md136',1,'Example: demo Plugin'],['../demo.html',1,'The demo Plugin']]],
  ['dep_13',['&lt;span class=&quot;tt&quot;&gt;Dep&lt;/span&gt;',['../dev.html#autotoc_md41',1,'']]],
  ['dependencies_14',['Dependencies',['../coding.html#autotoc_md12',1,'Dependencies'],['../affine.html#autotoc_md211',1,'Dependencies'],['../autodiff.html#autotoc_md227',1,'Dependencies'],['../btensor.html#autotoc_md242',1,'Dependencies'],['../buffer.html#autotoc_md274',1,'Dependencies'],['../clos.html#autotoc_md287',1,'Dependencies'],['../core.html#autotoc_md325',1,'Dependencies'],['../cps.html#autotoc_md350',1,'Dependencies'],['../gpu.html#autotoc_md357',1,'Dependencies'],['../ll.html#autotoc_md395',1,'Dependencies'],['../ll_nvptx.html#autotoc_md401',1,'Dependencies'],['../mem.html#autotoc_md428',1,'Dependencies'],['../nvptx.html#autotoc_md446',1,'Dependencies'],['../opt.html#autotoc_md451',1,'Dependencies'],['../option.html#autotoc_md453',1,'Dependencies'],['../ord.html#autotoc_md464',1,'Dependencies'],['../refly.html#autotoc_md479',1,'Dependencies'],['../regex.html#autotoc_md496',1,'Dependencies'],['../tensor.html#autotoc_md514',1,'Dependencies'],['../tuple.html#autotoc_md632',1,'Dependencies'],['../vec.html#autotoc_md640',1,'Dependencies']]],
  ['dependent_20tuple_20types_15',['Dependent Tuple Types',['../langref.html#mutsigma',1,'Dependent Tuple Types'],['../tutorial.html#autotoc_md200',1,'Dependent Tuple Types']]],
  ['deprecated_20list_16',['Deprecated List',['../deprecated.html',1,'']]],
  ['design_20pattern_17',['Recommended Design Pattern',['../phases.html#autotoc_md123',1,'']]],
  ['developer_20guide_18',['Developer Guide',['../dev.html',1,'']]],
  ['developer_20options_19',['Developer Options',['../cli.html#autotoc_md8',1,'']]],
  ['diagnostics_20',['Diagnostics',['../cli.html#autotoc_md5',1,'Diagnostics'],['../cli.html#clidiag',1,'Diagnostics']]],
  ['diff_21',['diff',['../autodiff.html#autotoc_md241',1,'autodiff.diff'],['../autodiff.html#autotoc_md240',1,'diff'],['../vec.html#autotoc_md651',1,'diff']]],
  ['differentiation_20plugin_22',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['discovery_23',['Third-Party Plugin Discovery',['../plugins.html#extra_plugins',1,'']]],
  ['discussion_24',['Discussion',['../phases.html#autotoc_md121',1,'']]],
  ['disj_25',['disj',['../regex.html#autotoc_md501',1,'']]],
  ['displaying_20dot_20graphs_26',['Displaying DOT Graphs',['../coding.html#autotoc_md26',1,'']]],
  ['div_27',['div',['../core.html#autotoc_md337',1,'']]],
  ['dividend_20does_20not_20apply_20here_28',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['does_20not_20apply_20here_29',['The idiomatic dividend does not apply here',['../md_docs_2why-cpp.html#autotoc_md185',1,'']]],
  ['dominance_30',['Dominance',['../index.html#autotoc_md157',1,'🪾 SSA without Dominance'],['../phases.html#ssa-without-dominance',1,'SSA without Dominance']]],
  ['dominance_3a_20contification_31',['A second dominance: contification',['../phases.html#autotoc_md119',1,'']]],
  ['dot_20graphs_32',['Displaying DOT Graphs',['../coding.html#autotoc_md26',1,'']]],
  ['dot_20output_33',['DOT Output',['../cli.html#autotoc_md3',1,'']]],
  ['dot_5fgeneral_5ffun_34',['dot_general_fun',['../tensor.html#autotoc_md613',1,'']]],
  ['dot_5fgeneral_5fpick_35',['dot_general_pick',['../tensor.html#autotoc_md614',1,'']]],
  ['dot_5fgeneral_5fshape_36',['dot_general_shape',['../tensor.html#autotoc_md555',1,'']]],
  ['dot_5fproduct_37',['dot_product',['../tensor.html#autotoc_md556',1,'']]],
  ['dot_5fproduct_5fimpl_38',['dot_product_impl',['../tensor.html#autotoc_md615',1,'']]],
  ['dot_5fschedule_39',['dot_schedule',['../tensor.html#autotoc_md588',1,'']]],
  ['dot_5fschedule_5fkvec_40',['dot_schedule_kvec',['../tensor.html#autotoc_md589',1,'']]],
  ['downcast_41',['General Downcast',['../dev.html#autotoc_md43',1,'']]],
  ['downcast_20to_20immutables_42',['Downcast to Immutables',['../dev.html#autotoc_md44',1,'']]],
  ['downcast_20to_20mutables_43',['Downcast to Mutables',['../dev.html#autotoc_md45',1,'']]],
  ['downcasts_20for_20built_20ins_44',['Downcasts for Built-ins',['../dev.html#cast_builtin',1,'']]],
  ['doxygen_20style_45',['Doxygen Style',['../coding.html#autotoc_md18',1,'']]],
  ['dsl_46',['Embedded Python DSL',['../python.html#autotoc_md148',1,'']]],
  ['dumping_47',['Dumping',['../coding.html#autotoc_md25',1,'']]]
];
