var searchData=
[
  ['o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md281',1,'']]],
  ['of_20mim_1',['✨ A Taste of Mim',['../index.html#autotoc_md100',1,'']]],
  ['of_20mimir_2',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['of_20mutables_3',['Handling of Mutables',['../phases.html#autotoc_md67',1,'']]],
  ['of_20nodes_4',['🌊 Sea of Nodes',['../index.html#autotoc_md106',1,'']]],
  ['of_20sigmas_5',['Field Names of Sigmas',['../langref.html#autotoc_md61',1,'']]],
  ['op_20add_20sub_6',['%affine.op(add,sub)',['../affine.html#autotoc_md125',1,'']]],
  ['op_20mul_7',['%affine.op(mul)',['../affine.html#autotoc_md128',1,'']]],
  ['op_20neg_8',['%affine.op(neg)',['../affine.html#autotoc_md126',1,'']]],
  ['operations_9',['Operations',['../affine.html#autotoc_md122',1,'Affine Index Operations'],['../gpu.html#autotoc_md213',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md207',1,'Blocking Memory Operations'],['../core.html#autotoc_md168',1,'Integer Operations'],['../core.html#autotoc_md165',1,'Nat Operations'],['../math.html#autotoc_md231',1,'Numerical Operations'],['../affine.html#autotoc_md120',1,'Operations'],['../autodiff.html#autotoc_md135',1,'Operations'],['../demo.html#autotoc_md186',1,'Operations'],['../direct.html#autotoc_md189',1,'Operations'],['../gpu.html#autotoc_md198',1,'Operations'],['../matrix.html#autotoc_md252',1,'Operations'],['../option.html#autotoc_md298',1,'Operations'],['../tensor.html#autotoc_md354',1,'Operations'],['../tuple.html#autotoc_md372',1,'Operations'],['../core.html#autotoc_md182',1,'Other Operations'],['../math.html#autotoc_md242',1,'Other Operations']]],
  ['operations_10',['High-level matrix operations',['../matrix.html#autotoc_md261',1,'']]],
  ['operations_20related_20to_20longjmp_11',['Operations related to longjmp',['../clos.html#autotoc_md147',1,'']]],
  ['operations_20w_20o_20side_20effects_12',['Operations w/o Side Effects',['../mem.html#autotoc_md281',1,'']]],
  ['operations_20w_20side_20effects_13',['Operations w/ Side Effects',['../mem.html#autotoc_md272',1,'']]],
  ['opt_20plugin_14',['The opt Plugin',['../opt.html',1,'']]],
  ['option_15',['option.Option',['../option.html#autotoc_md294',1,'']]],
  ['option_20is_5fsome_16',['%option.is_some',['../option.html#autotoc_md299',1,'']]],
  ['option_20none_17',['%option.none',['../option.html#autotoc_md297',1,'']]],
  ['option_20option_18',['option.Option',['../option.html#autotoc_md294',1,'']]],
  ['option_20plugin_19',['The option Plugin',['../option.html',1,'']]],
  ['option_20some_20',['%option.some',['../option.html#autotoc_md296',1,'']]],
  ['option_20unwrap_5for_21',['%option.unwrap_or',['../option.html#autotoc_md301',1,'']]],
  ['option_20unwrap_5funsafe_22',['%option.unwrap_unsafe',['../option.html#autotoc_md300',1,'']]],
  ['optional_23',['📦 Install (Optional)',['../index.html#autotoc_md103',1,'']]],
  ['optional_20pre_20analysis_24',['Optional Pre-Analysis',['../phases.html#autotoc_md71',1,'']]],
  ['ord_20contains_25',['%ord.contains',['../ord.html#autotoc_md314',1,'']]],
  ['ord_20create_26',['%ord.create',['../ord.html#autotoc_md308',1,'']]],
  ['ord_20get_27',['%ord.get',['../ord.html#autotoc_md313',1,'']]],
  ['ord_20init_28',['%ord.init',['../ord.html#autotoc_md307',1,'']]],
  ['ord_20insert_29',['%ord.insert',['../ord.html#autotoc_md316',1,'']]],
  ['ord_20is_5fempty_30',['%ord.is_empty',['../ord.html#autotoc_md311',1,'']]],
  ['ord_20key_31',['%ord.Key',['../ord.html#autotoc_md304',1,'']]],
  ['ord_20map_32',['%ord.Set / %ord.Map',['../ord.html#autotoc_md305',1,'']]],
  ['ord_20plugin_33',['The ord Plugin',['../ord.html',1,'']]],
  ['ord_20set_20ord_20map_34',['%ord.Set / %ord.Map',['../ord.html#autotoc_md305',1,'']]],
  ['ord_20size_35',['%ord.size',['../ord.html#autotoc_md310',1,'']]],
  ['other_20definitions_36',['Other Definitions',['../mimir.html#autotoc_md64',1,'']]],
  ['other_20operations_37',['Other Operations',['../core.html#autotoc_md182',1,'Other Operations'],['../math.html#autotoc_md242',1,'Other Operations']]],
  ['over_20the_20program_38',['Iterating over the Program',['../dev.html#autotoc_md40',1,'']]],
  ['overview_39',['Overview',['../phases.html#autotoc_md65',1,'']]]
];
