var searchData=
[
  ['a_20new_20in_20tree_20plugin_0',['Create a New In-Tree Plugin',['../plugins.html#autotoc_md84',1,'']]],
  ['a_20third_20party_20plugin_1',['Create a Third-Party Plugin',['../plugins.html#autotoc_md85',1,'']]],
  ['abs_2',['abs',['../core.html#autotoc_md174',1,'%core.abs'],['../math.html#autotoc_md236',1,'%math.abs']]],
  ['ad_3',['%autodiff.ad',['../autodiff.html#autotoc_md132',1,'']]],
  ['add_4',['add',['../autodiff.html#autotoc_md134',1,'%autodiff.add'],['../autodiff.html#autotoc_md140',1,'%core.wrap.add']]],
  ['add_20sub_5',['%affine.op(add,sub)',['../affine.html#autotoc_md121',1,'']]],
  ['add_5fmim_5fplugin_6',['add_mim_plugin',['../add_mim_plugin_cmake.html',1,'']]],
  ['address_20spaces_7',['Address Spaces',['../gpu.html#autotoc_md190',1,'']]],
  ['affine_20constant_8',['%affine.constant',['../affine.html#autotoc_md120',1,'']]],
  ['affine_20for_9',['%affine.For',['../affine.html#autotoc_md117',1,'']]],
  ['affine_20index_10',['%affine.index',['../affine.html#autotoc_md119',1,'']]],
  ['affine_20index_20operations_11',['Affine Index Operations',['../affine.html#autotoc_md118',1,'']]],
  ['affine_20lower_5ffor_5fpass_12',['%affine.lower_for_pass',['../affine.html#autotoc_md127',1,'']]],
  ['affine_20lower_5findex_5fphase_13',['%affine.lower_index_phase',['../affine.html#autotoc_md128',1,'']]],
  ['affine_20map_14',['%affine.map',['../affine.html#autotoc_md125',1,'']]],
  ['affine_20op_20add_20sub_15',['%affine.op(add,sub)',['../affine.html#autotoc_md121',1,'']]],
  ['affine_20op_20mul_16',['%affine.op(mul)',['../affine.html#autotoc_md124',1,'']]],
  ['affine_20op_20neg_17',['%affine.op(neg)',['../affine.html#autotoc_md122',1,'']]],
  ['affine_20plugin_18',['The affine Plugin',['../affine.html',1,'']]],
  ['affine_20semiop_20mul_20ceildiv_20floordiv_20mod_19',['%affine.semiop(mul,ceildiv,floordiv,mod)',['../affine.html#autotoc_md123',1,'']]],
  ['alloc_20',['%mem.alloc',['../mem.html#autotoc_md272',1,'']]],
  ['alloc_20asyn_21',['%gpu.alloc(asyn)',['../gpu.html#autotoc_md210',1,'']]],
  ['alloc_20block_22',['%gpu.alloc(block)',['../gpu.html#autotoc_md204',1,'']]],
  ['alloc_5fcopy_20asyn_23',['%gpu.alloc_copy(asyn)',['../gpu.html#autotoc_md214',1,'']]],
  ['alloc_5fcopy_20block_24',['%gpu.alloc_copy(block)',['../gpu.html#autotoc_md208',1,'']]],
  ['an_20existing_20in_20tree_20plugin_25',['Extract an Existing In-Tree Plugin',['../plugins.html#autotoc_md87',1,'']]],
  ['analysis_26',['Analysis',['../phases.html#phases_analysis',1,'Analysis'],['../phases.html#autotoc_md75',1,'Analysis'],['../phases.html#autotoc_md68',1,'Optional Pre-Analysis']]],
  ['analysis_20results_27',['Analysis Results',['../phases.html#autotoc_md69',1,'']]],
  ['and_20basic_20forms_28',['Literals and Basic Forms',['../langref.html#autotoc_md48',1,'']]],
  ['and_20builtin_20types_29',['Kinds and Builtin Types',['../langref.html#autotoc_md47',1,'']]],
  ['and_20continuations_30',['Functions and Continuations',['../langref.html#autotoc_md49',1,'']]],
  ['and_20matching_31',['Products, Sequences, Unions, and Matching',['../langref.html#autotoc_md50',1,'']]],
  ['and_20phases_32',['and Phases',['../affine.html#autotoc_md126',1,'Passes and Phases'],['../clos.html#autotoc_md145',1,'Passes and Phases'],['../matrix.html#autotoc_md262',1,'Passes and Phases'],['../regex.html#autotoc_md346',1,'Passes and Phases']]],
  ['and_20types_33',['Summary: Functions and Types',['../langref.html#autotoc_md53',1,'']]],
  ['annex_34',['Annex',['../langref.html#autotoc_md60',1,'']]],
  ['annexes_35',['Pre-applied pass annexes',['../mem.html#autotoc_md284',1,'']]],
  ['any_36',['%regex.any',['../regex.html#autotoc_md342',1,'']]],
  ['applications_37',['Applications',['../langref.html#autotoc_md56',1,'']]],
  ['applied_20pass_20annexes_38',['Pre-applied pass annexes',['../mem.html#autotoc_md284',1,'']]],
  ['arith_39',['%math.arith',['../math.html#autotoc_md228',1,'']]],
  ['arity_40',['Arity',['../dev.html#autotoc_md35',1,'']]],
  ['asyn_41',['asyn',['../gpu.html#autotoc_md210',1,'%gpu.alloc(asyn)'],['../gpu.html#autotoc_md214',1,'%gpu.alloc_copy(asyn)'],['../gpu.html#autotoc_md212',1,'%gpu.copy_to_device(asyn)'],['../gpu.html#autotoc_md213',1,'%gpu.copy_to_host(asyn)'],['../gpu.html#autotoc_md211',1,'%gpu.free(asyn)']]],
  ['asynchronous_20memory_20operations_42',['Asynchronous Memory Operations',['../gpu.html#autotoc_md209',1,'']]],
  ['attribute_43',['Closure Attribute',['../clos.html#autotoc_md144',1,'']]],
  ['autodiff_20ad_44',['%autodiff.ad',['../autodiff.html#autotoc_md132',1,'']]],
  ['autodiff_20add_45',['%autodiff.add',['../autodiff.html#autotoc_md134',1,'']]],
  ['autodiff_20zero_46',['%autodiff.zero',['../autodiff.html#autotoc_md133',1,'']]],
  ['automatic_20differentiation_20plugin_47',['The automatic differentiation Plugin',['../autodiff.html',1,'']]],
  ['axioms_48',['Matching Axioms',['../dev.html#cast_axm',1,'']]]
];
