var searchData=
[
  ['o_20side_20effects_0',['Operations w/o Side Effects',['../mem.html#autotoc_md300',1,'']]],
  ['of_20mim_1',['✨ A Taste of Mim',['../index.html#autotoc_md107',1,'']]],
  ['of_20mimir_2',['A Tour of MimIR',['../mimir.html',1,'']]],
  ['of_20mutables_3',['Handling of Mutables',['../phases.html#autotoc_md69',1,'']]],
  ['of_20nodes_4',['🌊 Sea of Nodes',['../index.html#autotoc_md113',1,'']]],
  ['of_20sigmas_5',['Field Names of Sigmas',['../langref.html#autotoc_md61',1,'']]],
  ['op_20add_20sub_6',['%affine.op(add,sub)',['../affine.html#autotoc_md132',1,'']]],
  ['op_20mul_7',['%affine.op.mul',['../affine.html#autotoc_md135',1,'']]],
  ['op_20neg_8',['%affine.op(neg)',['../affine.html#autotoc_md133',1,'']]],
  ['operations_9',['Operations',['../affine.html#autotoc_md129',1,'Affine Index Operations'],['../gpu.html#autotoc_md233',1,'Asynchronous Memory Operations'],['../gpu.html#autotoc_md227',1,'Blocking Memory Operations'],['../core.html#autotoc_md186',1,'Integer Operations'],['../core.html#autotoc_md183',1,'Nat Operations'],['../math.html#autotoc_md251',1,'Numerical Operations'],['../affine.html#autotoc_md127',1,'Operations'],['../autodiff.html#autotoc_md145',1,'Operations'],['../buffer.html#autotoc_md159',1,'Operations'],['../cps.html#autotoc_md206',1,'Operations'],['../demo.html#autotoc_md210',1,'Operations'],['../gpu.html#autotoc_md218',1,'Operations'],['../option.html#autotoc_md311',1,'Operations'],['../tensor.html#autotoc_md368',1,'Operations'],['../tuple.html#autotoc_md394',1,'Operations'],['../core.html#autotoc_md201',1,'Other Operations'],['../math.html#autotoc_md262',1,'Other Operations']]],
  ['operations_10',['High-level matrix operations',['../matrix.html#autotoc_md271',1,'']]],
  ['operations_20related_20to_20longjmp_11',['Operations related to longjmp',['../clos.html#autotoc_md170',1,'']]],
  ['operations_20w_20o_20side_20effects_12',['Operations w/o Side Effects',['../mem.html#autotoc_md300',1,'']]],
  ['operations_20w_20side_20effects_13',['Operations w/ Side Effects',['../mem.html#autotoc_md291',1,'']]],
  ['opt_14',['%option.Opt',['../option.html#autotoc_md307',1,'']]],
  ['opt_20plugin_15',['The opt Plugin',['../opt.html',1,'']]],
  ['option_20is_5fsome_16',['%option.is_some',['../option.html#autotoc_md312',1,'']]],
  ['option_20none_17',['%option.none',['../option.html#autotoc_md310',1,'']]],
  ['option_20opt_18',['%option.Opt',['../option.html#autotoc_md307',1,'']]],
  ['option_20plugin_19',['The option Plugin',['../option.html',1,'']]],
  ['option_20some_20',['%option.some',['../option.html#autotoc_md309',1,'']]],
  ['option_20unwrap_5for_21',['%option.unwrap_or',['../option.html#autotoc_md314',1,'']]],
  ['option_20unwrap_5funsafe_22',['%option.unwrap_unsafe',['../option.html#autotoc_md313',1,'']]],
  ['optional_23',['📦 Install (Optional)',['../index.html#autotoc_md110',1,'']]],
  ['optional_20pre_20analysis_24',['Optional Pre-Analysis',['../phases.html#autotoc_md74',1,'']]],
  ['ord_20contains_25',['%ord.contains',['../ord.html#autotoc_md327',1,'']]],
  ['ord_20create_26',['%ord.create',['../ord.html#autotoc_md321',1,'']]],
  ['ord_20get_27',['%ord.get',['../ord.html#autotoc_md326',1,'']]],
  ['ord_20init_28',['%ord.init',['../ord.html#autotoc_md320',1,'']]],
  ['ord_20insert_29',['%ord.insert',['../ord.html#autotoc_md329',1,'']]],
  ['ord_20is_5fempty_30',['%ord.is_empty',['../ord.html#autotoc_md324',1,'']]],
  ['ord_20key_31',['%ord.Key',['../ord.html#autotoc_md317',1,'']]],
  ['ord_20map_32',['%ord.Set / %ord.Map',['../ord.html#autotoc_md318',1,'']]],
  ['ord_20plugin_33',['The ord Plugin',['../ord.html',1,'']]],
  ['ord_20set_20ord_20map_34',['%ord.Set / %ord.Map',['../ord.html#autotoc_md318',1,'']]],
  ['ord_20size_35',['%ord.size',['../ord.html#autotoc_md323',1,'']]],
  ['other_20definitions_36',['Other Definitions',['../mimir.html#autotoc_md65',1,'']]],
  ['other_20operations_37',['Other Operations',['../core.html#autotoc_md201',1,'Other Operations'],['../math.html#autotoc_md262',1,'Other Operations']]],
  ['over_20the_20program_38',['Iterating over the Program',['../dev.html#autotoc_md40',1,'']]],
  ['overview_39',['Overview',['../phases.html#autotoc_md66',1,'']]]
];
